### ISSUE TITLE
HelloWorldScene.h:36:5: error: redefinition of 'pause'

### ISSUE THREAD

**Issue by lvdpower** [axmolengine/axmol#1015]
On mac mini m1 there is error HelloWorldScene.h:36:5: error: redefinition of 'pause'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/unistd.h:468:6: note: previous definition is here
int      pause(void) __DARWIN_ALIAS_C(pause);

timur123@gmail.com

**Comment by rh101** [comment]
The `myGameState` enum is causing this issue.  

It should really be named differently, or preferably use use `enum class`. I'll see if I can put a PR to fix it.
