### ISSUE TITLE
Want use "Angle': Set define AX_USE_COMPAT_GL 1 on windows raised an error (GLFWError #65542 Happen, EGL: Library not found)

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#1024]
- axmol version: [100a688](https://github.com/axmolengine/axmol/commit/100a688ce5083da54d22dda0685d269cd24038f2)

build cpp-tests with  (use Angle): 
axmol\core\platform\CCPlatformConfig.h  => define AX_USE_COMPAT_GL 1
```
#ifndef AX_USE_COMPAT_GL
#    define AX_USE_COMPAT_GL 1
#endif
```
Windows 10

![image](https://user-images.githubusercontent.com/8652787/211546241-08df11ce-173d-4cfe-bb9c-4bae99f1a2ec.png)

```
---------------------------
Error launch application
---------------------------
Can't create window
More info: 
GLFWError #65542 Happen, EGL: Library not found

---------------------------
OK   
---------------------------
```

**Comment by halx99** [comment]
Does the `libEGL.dll`, `libGLESv2.dll`, `d3dcompiler_47.dll` in exe dir?

**Comment by DelinWorks** [comment]
I got this same error and to fix it i had to copy the missing dlls that @halx99 mentioned above from the thirdparty angle folder.

**Comment by halx99** [comment]
> * axmol version: [100a688](https://github.com/axmolengine/axmol/commit/100a688ce5083da54d22dda0685d269cd24038f2)
> 
> build cpp-tests with (use Angle): axmol\core\platform\CCPlatformConfig.h => define AX_USE_COMPAT_GL 1
> 
> ```
> #ifndef AX_USE_COMPAT_GL
> #    define AX_USE_COMPAT_GL 1
> #endif
> ```
> 
> Windows 10
> 
> ![image](https://user-images.githubusercontent.com/8652787/211546241-08df11ce-173d-4cfe-bb9c-4bae99f1a2ec.png)
> 
> ```
> ---------------------------
> Error launch application
> ---------------------------
> Can't create window
> More info: 
> GLFWError #65542 Happen, EGL: Library not found
> 
> ---------------------------
> OK   
> ---------------------------
> ```

You should tell cmake to auto copy dll to target binary dir, not change defination in CCPlatformConfig.h

**Comment by halx99** [comment]
i.e.
```cmake
cmake -B build -DAX_USE_COMPAT_GL=TRUE
```

**Comment by aismann** [comment]
> i.e.
> 
> ```cmake
> cmake -B build -DAX_USE_COMPAT_GL=TRUE
> ```

Compiling from Visual Studio directly should also be an option.
Its nice to build with angle or OpenGL directly.
Maybe some more "Solution Configurations" is a good choice?

![image](https://user-images.githubusercontent.com/8652787/211748362-bd8d3fb0-d1ad-4f6f-9104-15c5536f8563.png)
Debug Angle
Release Angle

**Comment by halx99** [comment]
Refer to: https://github.com/axmolengine/axmol/blob/dev/CMakeOptions.md

**Comment by aismann** [comment]
Should we add a sentence about coping the  libEGL.dll, libGLESv2.dll, d3dcompiler_47.dll in exe dir?
like:
... libEGL.dll, libGLESv2.dll, d3dcompiler_47.dll will not auytomaticvly in exe dir...
```
AX_USE_COMPAT_GL: whether use compat gl as renderer backend, default: FALSE
windows: whether use angleproject as GLES2 backend
apple: whether use GLES instead Metal backend
```

**Comment by halx99** [comment]
When you use cmake to config it, it's automatically compy to exe dir, that the  only recommand way for switching render backend to `angle`
