### ISSUE TITLE
Support for VS Code?

### ISSUE THREAD

**Issue by lavara123** [axmolengine/axmol#1028]
How-to document for VS Code etc. is there? Or can you create a document on how to do it?
(Linux)

**Comment by halx99** [comment]
Easy, actually I already build the cpp-tests and run/debug it on ubuntu 22.0.4, Just install vscode extension `cmake`, then the vscode will prompt you to auto generate cmake and build it.

**Comment by halx99** [comment]
No document yet, will create in the future.

**Comment by lavara123** [comment]
> No document yet, will create in the future.

Yes that would be great 👍 I did it in Qt Creator but I don't know how to do it in VS Code

**Comment by aismann** [comment]
> No document yet, will create in the future.

@halx99 
Maybe add it to an existing project (axmol-1.0/axmol-2.0,,.. (so this issue can be closed/moved)

**Comment by halx99** [comment]
axmol support vscode on Linux, just needs document, maybe somebody have time to do it

**Comment by halx99** [comment]
done: https://github.com/axmolengine/axmol/blob/dev/docs/DevSetup.md#linux-vscode
