### ISSUE TITLE
 Visible artifacts on DrawNode::drawCircle() with a corresponding lineWidth > 5 

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#1046]
Steps to Reproduce:
![image](https://user-images.githubusercontent.com/8652787/217216261-b9ebe4b0-7829-4f7d-80de-f978afca850c.png)

**Comment by aismann** [comment]
With this fix:
cpp_test  has a scale_factor bug (i belive) -> if window is resizing.
https://user-images.githubusercontent.com/8652787/217228819-9371f0cd-e935-4418-8a4e-6bc714d8421c.png

**Comment by aismann** [comment]
Or another possible reason:
cpp_tests Node::Draw: 3. Rendering drawCircle itself has a bug ;)

**Comment by aismann** [comment]
works corrcet now:
![image](https://user-images.githubusercontent.com/8652787/217739178-7aacb0c2-4096-4bf8-a4da-a82b6a0b2876.png)

**Comment by halx99** [comment]
seems correct in current version: 
![image](https://user-images.githubusercontent.com/6977319/218024895-7084862d-0fa9-48bf-963f-fc054d95c60c.png)

**Comment by aismann** [comment]
> seems correct in current version: ![image](https://user-images.githubusercontent.com/6977319/218024895-7084862d-0fa9-48bf-963f-fc054d95c60c.png)

The green rings looks bigger (nearer on the subtitle)
I can clicking the mousebutton on the window title and the "rendering is stopping for better comparing)

**Comment by halx99** [comment]
Seems it's the drawPolygon behavior, when the border large, the circle looks large

**Comment by aismann** [comment]
the current implementaion:
![image](https://user-images.githubusercontent.com/8652787/218034771-d90cdc07-e9a0-4501-b799-59009185c017.png)

the PR
![image](https://user-images.githubusercontent.com/8652787/218034415-48b289bb-91d7-472d-b347-5afc1043dfdc.png)

**Comment by aismann** [comment]
@halx99  and @rh101 look here for description of the "internal: drawCircle render improvement:

As long the "line width < 5" both using the same faster render method
![image](https://user-images.githubusercontent.com/8652787/218143196-36a8c719-ee28-4c6d-9370-9f05bc72dcab.png)
If the "line width >= 5" left (GREEN) using the smoother internal method (automaticfly) RED use the faster but ugly method. 
![image](https://user-images.githubusercontent.com/8652787/218143980-d62562b1-3292-40a8-92a5-3895aecb3cbb.png)

**Comment by aismann** [comment]
New tester:
![image](https://user-images.githubusercontent.com/8652787/218194159-81843419-ca1b-4ca2-9a85-f58b19700a0f.png)
![image](https://user-images.githubusercontent.com/8652787/218194221-c331aaef-ae9d-4eb0-8a60-cba3ae891588.png)

**Comment by rh101** [comment]
Adding optimization for drawing a circle when line width is below a certain threshold is, in my opinion, completely fine, as long as the circle being drawn has no visible artifacts.

**Comment by aismann** [comment]
see comments on the PR

**Comment by aismann** [comment]
solved with [1b4c7b9](https://github.com/axmolengine/axmol/commit/1b4c7b99764d31b3f5651d88e0ec7a5956604da8)
