### ISSUE TITLE
cant create a new project

### ISSUE THREAD

**Issue by 10100010010001001010** [axmolengine/axmol#1055]
- devices test on: PC, windows 10
- developing environments
   -both requirement python versions from the description

![image](https://user-images.githubusercontent.com/120378517/218153264-3cb6aa10-8e39-453f-aa80-666cd9c7c601.png)

i can't create a new project, after creation command, or just typing "axmol" in cmd, i get this error from the screenshot above

**Comment by aismann** [comment]
Ist this working?
``axmol new -p org.axmol.hellocpp -d D:\dev\projects\ -l cpp --portrait HelloCpp``

**Comment by aismann** [comment]
This have to adapt maybe:
`D:\dev\projects\`

**Comment by 10100010010001001010** [comment]
No, its doesnt work. I get the same error

**Comment by aismann** [comment]
You have the correct Python Version?

**Comment by 10100010010001001010** [comment]
![image](https://user-images.githubusercontent.com/120378517/218156841-d728aca1-47a3-4f54-b672-cf9990e78b66.png)

I'm not shure about 3.11 version. But in the description shows the version from 3.7 and above

**Comment by rh101** [comment]
Try making python 3.11.2 the default for the "py" and "python" commands.  If you're not sure how, then check [https://stackoverflow.com/questions/5087831/how-should-i-set-default-python-version-in-windows](https://stackoverflow.com/questions/5087831/how-should-i-set-default-python-version-in-windows).

**Comment by 10100010010001001010** [comment]
thanks, it worked. Is it possible to explicitly specify which version of python will be used?

**Comment by rh101** [comment]
> thanks, it worked. Is it possible to explicitly specify which version of python will be used?

I'm not sure. Perhaps @halx99 can answer that question.

**Comment by halx99** [comment]
The python2 support should be dropped

**Comment by rh101** [comment]
> The python2 support should be dropped

That's a good idea, and all mention of Python 2 should be removed from the setup instructions so there is no confusion.  The source of the problem for the OP in this thread seemed to be a bad installation of Python 3, and had nothing to do with Axmol.

**Comment by halx99** [comment]
Done https://github.com/axmolengine/axmol/commit/bc69b3e33afa086864dbea53f1f9db40b94e9c7e
