### ISSUE TITLE
axmolengine - python version issue.

### ISSUE THREAD

**Issue by ashK7** [axmolengine/axmol#1058]
Hello, I want to use the latest version of axmolengine. Now I wanted to know in my system has a python version is 2.7.17. So can I use axmolengine smoothly? I am using mac os big sur 11.3.1.

**Comment by halx99** [comment]
Please python3 via brew

**Comment by ashK7** [comment]
@halx99 Thank you for your all-time replay. Now I am using make M1 so do you have any references on how to use brew to update my Python version? And what will be the process I need to uninstall the older version of python or install a newer one? Or I can directly update my python. I didn't use a Brew. but I will use it if required  Again thank you for the reply and help..

**Comment by halx99** [comment]
```cpp
# install brew acoording to brew website
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# install python3
brew install python3
```

**Comment by halx99** [comment]
You don't need uninstall older one

**Comment by ashK7** [comment]
@halx99 brother
