### ISSUE TITLE
RichText text formatting issue

### ISSUE THREAD

**Issue by rh101** [axmolengine/axmol#1065]
- axmol version: [current](https://github.com/axmolengine/axmol/commit/b94890cf00b2505300a8d3daca4116538fb9cce9)
- devices test on:
- developing environments
   - NDK version: r19c
   - Xcode version: 12.4
   - Visual Studio: 
      - VS version: 2019 (16.11), 2022 (17.4)
      - MSVC version: 1929, 1934
      - Windows SDK version: 10.0.22621.0
   - cmake version: 
Steps to Reproduce:

Left-aligned text can result in spaces at the start of lines.  This issue is not present in center and right aligned text.

The issue is visible in the screenshots below (with label debug draw turned on):

Actual:
![image](https://user-images.githubusercontent.com/8603230/220237278-deeb44c3-184e-4fec-b009-4b501efa54d5.png)

Expected:
![image](https://user-images.githubusercontent.com/8603230/220237583-3a910cf7-2655-4f11-bbd3-7d2a867de0a0.png)

I've managed to fix the issue, but before I submit a PR, I need some input regarding the handling of text in this situation where there are spaces between words, like this:

`This is just simple text, with,    no           XML tags. Testing the basics. Testing word-wrapping. Testing, Testing, Testing`

In all text displays/editors I've entered that text into, the trailing spaces/leading spaces are always removed, but, if the spaces happen to be in the middle of a sentence, then they are not removed.  At the moment, the implementation of RichText (with plain text) will delete all spaces except 1, but is that the desired behavior?

To highlight this issue, this is the display in an external editor:
Sample 1:
![image](https://user-images.githubusercontent.com/8603230/220238516-71e8587b-f894-4bb1-b57f-2a7fb5f641f1.png)
Sample 2:
![image](https://user-images.githubusercontent.com/8603230/220238452-51e4f01b-96dc-4245-b606-d4cd7dd7cc61.png)
Sample 3:
![image](https://user-images.githubusercontent.com/8603230/220238482-9aa89147-1246-4635-8739-8ede5500ad41.png)

In Axmol/cocos2d-x, this is the result (regardless of alignment, always results in a max of 1 space between words):
![image](https://user-images.githubusercontent.com/8603230/220238701-615f209d-9e81-4778-b554-18e3c4991385.png)
![image](https://user-images.githubusercontent.com/8603230/220238775-aa8f063b-f59d-4122-bb90-f269a50cefa6.png)

Should this remain as-is, or should RichText reproduce the spaces between words (assuming the spaces are *not* at the start or end of a line)?

**Comment by halx99** [comment]
It's HTML standard, so I think the space behavior is correct

**Comment by rh101** [comment]
I understand, then the PR will just contain the fix for the space visible at the start of the line.
