### ISSUE TITLE
(Windows) Missing an "icon" for axmol => cocos2dx is still there (see screenshot)

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#1068]
![image](https://user-images.githubusercontent.com/8652787/220666748-c26fad29-e000-4850-8a46-18fa31841de4.png)

@halx99 
plz add help-wanted

**Comment by rh101** [comment]
@halx99 I can take care of this for Windows and iOS

**Comment by rh101** [comment]
It looks like there is something wrong with the `\templates\lua-template-default\frameworks\runtime-src\proj.ios_mac\ios\targets` folder. The iOS and tvos resources seem to be swapped compared to all of the other projects. Was that done on purpose, or is a mistake?

**Comment by halx99** [comment]
Maybe mistake

**Comment by halx99** [comment]
Maybe tvos support contributor @paulocoutinhox can help us

**Comment by rh101** [comment]
It does look like it was done by mistake, since the image sizes do not make sense for iOS or tvOS.  It was just a matter of switching them around.

**Comment by halx99** [comment]
Seems android icon still not update

**Comment by rh101** [comment]
Oh that's strange, it looked like they were already there. I'll take another look at it and create a new PR with any changes.

**Comment by rh101** [comment]
The template projects already have the icons, although transparent versions, but the test projects did not, so copied over the ones in the template project across to the test projects.  Let me know if you want them to be the black background versions of the logo.
