### ISSUE TITLE
`PhysicsBody::setDynamic(false)` performance issue with multiple colliders

### ISSUE THREAD

**Issue by DelinWorks** [axmolengine/axmol#1080]
I was making a map for my game using tiled until I noticed a huge drop in performance, after looking deeper I noticed that after creating a collider for each tile the performance drops below 40 fps when reaching 200 colliders `(PhysicsBody)`

https://user-images.githubusercontent.com/45469625/221382061-76d3e2a1-b210-48fc-83c0-cfa2b3e98580.mp4

This is the code I use to create a collider for each tile:
```
wall_body = ax::PhysicsBody::createBox({ 32, 32 });
wall_body->setDynamic(false);
wall_body->setGroup(9);
wall_body->setContactTestBitmask(9);

node = Node::create();
node->setPhysicsBody(wall_body);

addChild(node);
```

in my understating this lag is caused by each collider checking if it collides with every other collider, this calculation is O(n^2) which is quite expensive, isn't the `setDynamic(false)` supposed to stop checking if each static object collides with other static objects, and only check for dynamic moving objects like the player?

if not, then how can this be solved?
is there a way of creating static physical objects that don't tank performance?

I have tried making big batches of squares into one collider but that didn't work because I couldn't implement the algorithm, it was too complex for my case, I'd be better off writing my own physics system.

I also thought of creating a custom collider mesh but chipmunk only supports convex hulls which again, doesn't work because convex hulls have to be connected.

I also tried `setCollisionBitmask()` but to no avail.

I have also tried looking in chipmunk itself to find a function that would mask these collision but chipmunk doesn't seem to have it

I thought of minimizing collider count but that doesn't stop the system from being inefficient, even though I could reach stable framerates, I could reach this stable framerate with a much more efficient system that won't heat up a phone's CPU.

**Comment by DelinWorks** [comment]
I Figured it out! 

https://user-images.githubusercontent.com/45469625/221408355-393b0848-0d7f-4fad-a8ed-bac933388b08.mp4

turns out the functions `setCollisionBitmask()`, `setCategoryBitmask()` are virtualized into the engine itself and the according values are not set in chipmunk itself which is kinda weird.. Why reinvent the wheel and not use the masking engine of chipmunk itself?

`wall_body->getFirstShape()->_cpShapes[0]->filter = cpShapeFilterNew(1, 1, 1);`

I had to first import `#include "chipmunk/chipmunk_private.h"` and before that I had to expose the `_cpShapes` which the class doesn't have a getter function for that array weirdly enough, and then add my chipmunk filter manually and for each collider that has a group id of `1` which is the first parameter, their collision is ignored which is what I wanted, second and third parameters are used to interact with the player.

Maybe make the functions change chipmunks filter options for bodies as to not cause confusion in the future!

**Comment by aismann** [comment]
@DelinWorks 
Maybe a Q/A thema?

**Comment by aismann** [comment]
Have you tried this change:
```
    // bitmask check
    if ((shapeA->getCategoryBitmask() & shapeB->getContactTestBitmask()) == 0 ||
        (shapeA->getContactTestBitmask() & shapeB->getCategoryBitmask()) == 0)
    {
        contact.setNotificationEnable(false);
    }
```
I guess this is the bug，the code should be write like this:

```
    if ((shapeA->getCategoryBitmask() & shapeB->getContactTestBitmask()) == 0  
        && (shapeA->getContactTestBitmask() & shapeB->getCategoryBitmask()) == 0)  
    {  
        contact.setNotificationEnable(false);  
    }  
```
change || to &&

**Comment by aismann** [comment]
> @aismann it doesn't matter whether it sends notifications or not for contacts, when the group is set for two objects then they shouldn't perform expensive collision calculations on eachother as long as their group is not zero and the same, i had to hack my way around chipmunk and modify the group which the engine doesn't do. this solution boosted my fps by 99%

Ok. Great.
Maybe I can get your source code (as small as it needed to get the issue) to check what is the reason for this performance gap?

**Comment by DelinWorks** [comment]
Just create a few static colliders in a grid and you'll see what I'm talking about, I'll give you the source when I'm at my pc

**Comment by aismann** [comment]
> Just create a few static colliders in a grid and you'll see what I'm talking about, I'll give you the source when I'm at my pc

Thanks.

**Comment by aismann** [comment]
Another question.
Your "jump" function looks very smooth and nice.|
How did you do it.
The example on the chipmunk testbed look not so good.

**Comment by DelinWorks** [comment]
> Another question. Your "jump" function looks very smooth and nice.| How did you do it. The example on the chipmunk testbed look not so good.

For jumping to look smooth you'll need to do 4 things:

1. Don't move the object with `Node::setPosition` instead use `PhysicsBody::applyImpulse`
Example: `player_body->applyImpulse({ 0, 795 });`

2. Set both Collision Slop and Collision Bias to 0 so that chipmunk takes 0 seconds to correct a physics body overlap, and that in turn makes the jumping action more crisp.
Example:
```
    #include "chipmunk/chipmunk_private.h"
    bool GameplayScene::init() {
        initPhysicsWorld();

        // Note: _cpSpace is not available you'd have to expose it in the physics world class.
        cpSpaceSetCollisionSlop(getPhysicsWorld()->_cpSpace, 0);
        cpSpaceSetCollisionBias(getPhysicsWorld()->_cpSpace, 0);
    }
```

3. Use custom physics engine stepping, don't let the engine call `step(dt)` on every frame, instead let the engine call step() with a fixed value until it reaches the designated delta time.
Example:
```
    bool GameplayScene::init() {
        getPhysicsWorld()->setAutoStep(false);
    }
    void GameplayScene::update(float dt)
        currentPhysicsDt += dt;

    #ifdef WIN32
        // Get refresh rate of monitor
        int physicsTPS = glfwGetVideoMode(glfwGetPrimaryMonitor())->refreshRate;
    #else
        // if not a WIN32 machine then just use 120 tps.
        // make sure that tps be double the frame rate of any device.
        int physicsTPS = 120;
    #endif
        // Set physics ticks per second to be atleast 120 tps
        physicsTPS = physicsTPS < 120 ? 120 : physicsTPS;
    
        /* 1: LOW ACCURACY PHYSICS */
        /* 2: HIGH ACCURACY PHYSICS */
        /* 3: ULTRA ACCURACY PHYSICS */
        /* 4: EXTREME ACCURACY PHYSICS */
        physicsTPS *= 2;

        // Prevent big delta times that are over 2 seconds.
        if (lastPhysicsDt + 2 < currentPhysicsDt)
            lastPhysicsDt = currentPhysicsDt;

        while (lastPhysicsDt < currentPhysicsDt)
        {
            lastPhysicsDt += 1.0 / physicsTPS;
            // step the physics system.
            getPhysicsWorld()->step(1.0 / physicsTPS);
        }
    }
```

4. When modifying anything physical about the player, i.e speed checking, collision checking, etc. don't use the update function of the Node class instead create a function called `physicsTick(ax::PhysicsWorld world)` and add it to the physics system pre update callback.
Example:
```
    bool GameplayScene::init() {
        getPhysicsWorld()->setPreUpdateCallback([&] {
            p->physicsTick(getPhysicsWorld());
        }
    }
```

**Comment by aismann** [comment]
> Just create a few static colliders in a grid and you'll see what I'm talking about, I'll give you the source when I'm at my pc

Thanks for jumping source example.

Can I get the colliders stuff for test issue also?

**Comment by aismann** [comment]
> Just create a few static colliders in a grid and you'll see what I'm talking about, I'll give you the source when I'm at my pc
@DelinWorks 
Please dont forget it. Thanks.

**Comment by DelinWorks** [comment]
I don't know if I should give you the whole project because its just a mess and my fork has a modified axmol code `dev-2` branch, soo there ya go.. you've been warned 😅 https://github.com/DelinWorks/DarkDimensions

**Comment by aismann** [comment]
> I don't know if I should give you the whole project because its just a mess and my fork has a modified axmol code `dev-2` branch it won' compile without these changes, soo there ya go.. you've been warned 😅 https://github.com/DelinWorks/DarkDimensions
> 
> You can test this quickly by setting `useColliderBatching` to false in GameplayScene, it would break the physics of the player so yeah..

Its yours. I dont want doing anything which will break this.
Thanks.

**Comment by DelinWorks** [comment]
it's okay you won't break anything for me because technically it's just in your computer so doing what I said above won't hurt me in anyway
