### ISSUE TITLE
creating a new project (try to compile and get this error: LINK : fatal error LNK1104: cannot open file 'dep_zlib.lib

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#1082]
- axmol version:

Maybe a PR issue:  Update thirdparty prebuilts to v44 #1076

- I create a new projet and its fail ([prebuilt version)
```
LINK : fatal error LNK1104: cannot open file 'dep_zlib.lib' [D:\______\aismann\__private\axmol\Clipper2\build_64\Clippe
r2.vcxproj]
```

**Comment by aismann** [comment]
ther e are some more errors:
OpenSSL::Crypto.lib
OpenSSL::SSL.lib
dep_*

**Comment by aismann** [comment]
@halx99 
I got still the error using latest axmol:
```
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'dep_zlib.lib' [D:\______\aismann\__private\axmol\Clipper2Tester\build_64\Clipper2Tester.vcxproj
]
```

**Comment by halx99** [comment]
plz remove CMakeCache.txt from both engine and your project

**Comment by aismann** [comment]
It was a new download and newc build of axmol.
And a new Project of course

**Comment by aismann** [comment]
I will try it on another machine again

**Comment by aismann** [comment]
ok. Its works. but for me its look the whole axmol stuff is rebuild too:

**Comment by aismann** [comment]
I tried it again and i got this:  
![image](https://user-images.githubusercontent.com/8652787/221962673-e9122902-09b4-4d9e-9f6a-680fba9ee122.png)

**Comment by aismann** [comment]
It is VS2022 x64 build

**Comment by aismann** [comment]
Yes
