### ISSUE TITLE
iOS ClippingNode performance issue?

### ISSUE THREAD

**Issue by Yehsam23** [axmolengine/axmol#1094]
- axmol version: lastest
- devices test on: iPhone 7 plus
- developing environments
   - NDK version: r23
   - Xcode version: 14.2
   - cmake version: 22
Steps to Reproduce:
1. Download 
[TestClip.zip](https://github.com/axmolengine/axmol/files/10895370/TestClip.zip)

2. I used 30 ClippingNodes and 30 Sprites, and the FPS dropped to around 20.
![IMG_0143](https://user-images.githubusercontent.com/1954445/222662936-400120d9-3835-4c97-b4ad-f117851b1feb.png)

3. With cocos2d-x v3.17, the FPS is 60 even when using 30 ClippingNodes and 30 Sprites. 
![IMG_0142](https://user-images.githubusercontent.com/1954445/222662907-bfd12428-699a-4616-a65f-72f54587a770.png)

4. With cocos2d-x v4, using 200 ClippingNodes and 200 Sprites still results in an FPS around 60.
![IMG_0144](https://user-images.githubusercontent.com/1954445/222662941-219f9a24-ce4f-4397-8bf1-affba28398af.png)

All the same device

**Comment by rh101** [comment]
The test project you attached doesn't have code related to clipping nodes.

**Comment by Yehsam23** [comment]
Sorry, I misplaced the file
The above has been updated

HelloWorldScene.cpp:
```
    auto visibleSize = _director->getVisibleSize();
    auto origin      = _director->getVisibleOrigin();
    
    for (int i = 0 ; i < 30 ; i++)
    {
        auto stencil = Sprite::create("stars2.png");
        auto clipNode = ClippingNode::create(stencil);
        clipNode->setPosition(origin + Vec2(random(0, (int)visibleSize.width), random(0, (int)visibleSize.height)));
        clipNode->setAlphaThreshold(0.1f);
        clipNode->setInverted(true);
        this->addChild(clipNode);
        
        auto sprite = Sprite::create("grossini.png");
        clipNode->addChild(sprite);
    }
```

**Comment by rh101** [comment]
Just an FYI. You've noted `axmol version: lastest` in your post, but the project you attached is not using the latest template, so things may not work as expected.

Now, regarding the issue, setting the number of clipping nodes to 30 didn't show a problem on an old HTC One M7, but upping it to 200 managed to get the FPS down to ~10.

This is the profiler output:
![image](https://user-images.githubusercontent.com/8603230/222902191-d47585a9-9374-48c8-b254-a3b57b53372f.png)

I'm not sure if that helps at all, but it seems to be taking most of the time in the `flush2D()` calls, which are happening twice.  I'm not too familiar with the rendering code, so I'm not sure if it's supposed to be like that, but perhaps this may help someone else looking into it.

**Comment by rh101** [comment]
@Yehsam23 Something isn't quite right regarding your results.  The first two screenshots look like they're taken at the same design resolution, but the last one, which you've set to 200 clipping zones, isn't from the test project you've attached.  That last screenshot looks like it came from the cpp-tests, and it's at a completely different design resolution.  

Please do the 200 clipping zone test using Cocos2d-x v4 using a new project, similar to the one you've attached to your initial post, then take a screenshot and post the result here.  The scale of the images in the output should look exactly the same as the first two screenshots you posted.

**Comment by Yehsam23** [comment]
I change `RenderTarget.h`
```
    void setTargetFlags(TargetBufferFlags flags) { 
        _flags = flags; 
       _dirty = true;
    }
  ```
  to
  ```
      void setTargetFlags(TargetBufferFlags flags) { 
        _flags = flags; 
    }
  ```
FPS will surpass cocos2d-x v4.

I'm not sure if the modification is correct.
I see that there is already a flag check before the renderTarget->isDirty() check in CommandBufferMTL.

**Comment by rh101** [comment]
I'm not familiar with the rendering code, but just out of curiousity, what happens if you change the method:

    void setTargetFlags(TargetBufferFlags flags) { 
        _flags = flags; 
       _dirty = true;
    }

to:

    void setTargetFlags(TargetBufferFlags flags) { 
        if (_flags == flags)
            return;
       _flags = flags; 
       _dirty = true;
    }

Just so it's not setting it as dirty unnecessarily.

**Comment by Yehsam23** [comment]
Because there are cases where setTargetFlags may first set A, render, then set B, and then set back to A and render again, the final result of the flag is actually the same as the last time, but it is set as dirty.
Below is the order of one ClippingNode and 1 Sprite:

```
1.DEPTH_AND_STENCIL | COLOR0
2.COLOR0 | STENCIL
3.COLOR0 | STENCIL
4.DEPTH_AND_STENCIL | COLOR0
5.COLOR0 | STENCIL
6.COLOR0 | STENCIL
7.drawCustomCommand->beginRenderPass->CommandBufferMTL
8.drawBatchedTriangles->beginRenderPass->CommandBufferMTL (use old _mtlRenderEncoder)
9.DEPTH
10.DEPTH_AND_STENCIL | COLOR0
11.COLOR0 | STENCIL
12.drawBatchedTriangles->beginRenderPass->CommandBufferMTL (create new one if because flags dirty)
```

Based on the information provided, it seems that the flags set during the last execution of CommandBufferMTL are always COLOR0 | STENCIL, even though dirty is set to true.

Additionally, the CommandBufferMTL checks if `_currentRenderTargetFlags == renderTarget->getTargetFlags()`

Therefore, it seems that setTargetFlags does not need to be set as dirty.

**Comment by rh101** [comment]
@Yehsam23 I tried out your modification by commenting out the `_dirty = true;` in `setTargetFlags`, and I haven't noticed any negative side-effects at all.  What I have noticed is a significant increase in performance on iOS (much higher FPS).

Once again though, I don't know much about the rendering code, and @halx99 is the one who would understand all of this.

**Comment by Yehsam23** [comment]
@halx99 

Although Android has a similar FPS to cocos2d-x v4 under the same design resolution, there is a significant difference between it and cocos2d-x v3.17. 
For example, when using 200 ClippingNodes and Sprites, the FPS in Axmol is around 9, while in cocos2d-x v3.17 it is around 41 on an Android HTC U11 Plus device.

Is there a way to optimize this? Our project currently uses ClippingNodes extensively to handle some animation effects, so we are hoping to find a solution to improve performance.

**Comment by halx99** [comment]
The dirty can be remove from setRenderTarget

**Comment by rh101** [comment]
@Yehsam23 Are you able to submit the pull request with the modification to `setTargetFlags()` to remove the `_dirty = true;' line, or do you need someone else to submit it?  At least that will fix the iOS issue. 

For the Android clipping node performance improvement, perhaps create a separate issue created for it so it can be tracked separately, since it's unrelated to the iOS problem.
