### ISSUE TITLE
Drawing from one RenderTexture into another

### ISSUE THREAD

**Issue by stefan80** [axmolengine/axmol#1099]
- axmol version: latest
- devices test on: Macbook (Intel)
- developing environments
   - Xcode version: 14.2
Steps to Reproduce:

I have overwritten the draw method of my scene to render all sprites of the scene into first render texture. The output of the first render texture is used to be rendered into the second render texture

The code worked with cocos2d-x 3.17.2. Switched from cocos2d-x to amol, but it seems like it is not possible to solve it like that anymore:

```
void RenderUnit::Draw(cocos2d::Renderer* renderer, const cocos2d::Mat4& transform, uint32_t flags)
{
    mRTex2->beginWithClear(0, 0, 0, 0);
    mSpritesLayer->visit(renderer, Mat4::IDENTITY, 0);
    mRTex2->end();
 
    Sprite* lRTex2Sprite = mRTex2->getSprite();

    mRTex->beginWithClear(0, 0, 0, 0);
    lRTex2Sprite->visit(renderer, Mat4::IDENTITY, 0); // is not drawn.
    mRTex->end();
}
```

Thanks for your efforts you put into Axmol!

**Comment by stefan80** [comment]
I created an example for it:
[HelloWorld.zip](https://github.com/axmolengine/axmol/files/10903648/HelloWorld.zip)

**Comment by rh101** [comment]
Please provide screenshots of the expected output and the actual output you are seeing, otherwise it's hard to know what exactly isn't working.

**Comment by rh101** [comment]
In addition to the above changes, there may be no need to create a temporary sprite to render to the 2nd render texture, so try this in the `draw()` method that you've overriden:

```
    mRTex2->beginWithClear(0, 0, 0, 0);
    sprite->visit(renderer, ax::Mat4::IDENTITY, flags);
    mRTex2->end();

    mRTex->beginWithClear(0, 0, 0, 0);
    mRTex2->visit(renderer, ax::Mat4::IDENTITY, 0);
    mRTex->end();
```

**Comment by rh101** [comment]
Using this code:
```
bool HelloWorld::init()
{
...
    mRTex = RenderTexture::create(mScreenWidth, mScreenHeight, PixelFormat::RGB5A1, false);
    mRTex->setPositionNormalized(Vec2(0.25f, 0.5f));
    mRTex->getSprite()->getTexture()->setAntiAliasTexParameters();
    this->addChild(mRTex, 100);

    mRTex2 = RenderTexture::create(mScreenWidth, mScreenHeight, PixelFormat::RGB5A1, false);
    mRTex2->setPositionNormalized(Vec2(0.75f, 0.5f));
    mRTex2->getSprite()->getTexture()->setAntiAliasTexParameters();
    this->addChild(mRTex2, 90);
...
}
```
and 
```
void HelloWorld::draw(ax::Renderer* renderer, const ax::Mat4& transform, uint32_t flags)
{
    mRTex2->beginWithClear(1, 0, 0, 0);
    sprite->visit(renderer, ax::Mat4::IDENTITY, flags);
    mRTex2->end();

    mRTex->beginWithClear(0, 1, 0, 0);
    mRTex2->visit(renderer, ax::Mat4::IDENTITY, 0);
    mRTex->end();
}
```

Results in this:
![image](https://user-images.githubusercontent.com/8603230/223332016-672b8d29-23c1-4736-b837-cdcea04aa574.png)

That seems to be working.

**Comment by stefan80** [comment]
Hi @rh101,

thank you very much for your fast help!!!

I checked your code and found out that the new optional RenderTexture CTOR parameter "bool sharedRenderTarget = true" caused the behavior I faced. If set to false (as you did), everything works fine again.

Thanks again!

**Comment by aismann** [comment]
@stefan80 
Maybe a small example in cpp-test ist a nice Gift for all?
