### ISSUE TITLE
lua-bindings requires optional extensions

### ISSUE THREAD

**Issue by Xrysnow** [axmolengine/axmol#1109]
`lua-bindings` requires many optional extensions such as `cocostudio`, this prevents me from disabling some of them. I think it's better to add the `AX_ENABLE_EXT_` conditions to cmake.
https://github.com/axmolengine/axmol/blob/6427e6e53cbe8b75829f96887a23ca501632c062/extensions/scripting/lua-bindings/CMakeLists.txt#L81-L95

**Comment by halx99** [comment]
Could you post a merge request, and the extensions condtion of axmol should be `AX_ENABLE_EXT_`

**Comment by iAndyHD3** [comment]
this just happened to me, where i wanted to disable extensions but since i was using lua i could not
