### ISSUE TITLE
Change 'About text': "This is another more radical fork of Coc..."

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#1116]
Change 'About text': 
```
This is another more radical fork of Cocos2d-x-4.0, use OpenAL for all platforms, 
single texture multi GPU texture handler, C++17/20.
```

like:
```
AXMOL Engine – Multi-platform Game Engine for Desktop, XBOX (UWP) and Mobile games.
(A radical fork of Cocos2d-x-4.0)
```

@halx99 
Its your turn.

also add a tag for XBOX, UWP

**Comment by halx99** [comment]
Good catch

**Comment by aismann** [comment]
@halx99 
I think this is a better sentence:
AXMOL Engine – Multi-platform Game Engine for Desktop, XBOX (UWP) and Mobile.
(A radical fork of Cocos2d-x-4.0)

And use "AXMOL Engine" because it can be used for more as "games" only => Remove the "Game" on AXMOL Game Engine"

**Comment by aismann** [comment]
closed
