### ISSUE TITLE
[UWP] Some '*_APP.dll's be missing on (UWP XBOX)e.g.: VCRUNTIME140_APP.dll 

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#1119]
Edit:
The standalone bin have to start from `AppX` folder (there be the axmol dlls)

**Comment by aismann** [comment]
@halx99 
Can you fix the cmake stuff?

**Comment by aismann** [comment]
Hint:
Running on VisualStudio it works without having the dlls in the bin folder.

**Comment by aismann** [comment]
> UWP APP, you can't click the exe, instead use cmake to build you exe target with debug configuration, then will build a .msix package, you can double click it to run on your PC

Sorry dont understand

**Comment by halx99** [comment]
https://github.com/axmolengine/axmol/suites/11541021871/artifacts/597236474

**Comment by halx99** [comment]
you can download artifact to check it

**Comment by halx99** [comment]
I'm not sure doesn't work on directory `bin`, I never run it in `bin` when test UWP support, I run in Visual Studio or open `cpp_test.msix` in `bin/AppPackages/cpp_tests/cpp_tests.msix, then press launch button.

**Comment by aismann** [comment]
> I'm not sure doesn't work on directory `bin`, I never run it in `bin` when test UWP support, I run in Visual Studio or open `cpp_test.msix` in `bin/AppPackages/cpp_tests/cpp_tests.msix, then press launch button.

Try it. For me its not working (Dlls missing messages raising)

**Comment by aismann** [comment]
Still missing.

**Comment by solan-solan** [comment]
@aismann @halx99
I did not check this project, but there is similar issue and some info about these dlls and UWP project configuration for VS. May be it helps. To my understand there should be two versions of dlls, with/without '_APP' in the UWPDesktop Framework Package
https://developercommunity.visualstudio.com/t/vcruntime140dll-is-missing-on-uwp-xbox/1073368

**Comment by aismann** [comment]
@halx99 
please add category 'UWP XBOX"

**Comment by halx99** [comment]
Needs deploy, latest axmol: just simple run `axmol run -p winuwp` on your project root directory
