### ISSUE TITLE
Performance issue vs Cocos2d-x v3.17

### ISSUE THREAD

**Issue by Yehsam23** [axmolengine/axmol#1121]
Download Test Project:
[TestClip.zip](https://github.com/axmolengine/axmol/files/10976641/TestClip.zip)

The following tests were conducted using an Android HTC U11 Plus with the build release APK.

When using 200 ClippingNode and Sprite, there is a significant difference in performance between Axmol and Cocos2d-x v3.17. Axmol's FPS is approximately 9-10, while Cocos2d-x v3.17's FPS is approximately 37-40.

Axmol:
![ax_clip](https://user-images.githubusercontent.com/1954445/225224980-638d9d6e-b144-4410-8d4f-02f94ed31b51.png)

Cocos2d-x v3.17:
![v3_clip](https://user-images.githubusercontent.com/1954445/225225019-c1f2aed5-bdd2-4df4-8c5f-0ae936320fba.png)

When using 4000 Sprites with SpriteA->SpriteB->SpriteA->SpriteB repeating pattern, Axmol's FPS is approximately 28-30, while Cocos2d-x v3.17's FPS is approximately 38-39.

Axmol:
![ax_sprite](https://user-images.githubusercontent.com/1954445/225225266-6feb3152-cb81-4253-8ba9-11250fa8eee4.png)

Cocos2d-x v3.17:
![v3_sprite](https://user-images.githubusercontent.com/1954445/225225083-9e3f5fc2-332f-479b-a3cb-881ec9241ea2.png)

As can be seen from the above, there is a significant performance difference when using ClippingNode.
According to experiment #1094, it is indeed a problem with Cocos2d-x v4.

Cocos2d-x v4 also had a similar issue initially. [issue](https://github.com/cocos2d/cocos2d-x/issues/20668)

I know that Axmol is a fork from Cocos2d-x-4.0. While it may be unfair to compare its performance to Cocos2d-x v3.17, I also hope to find ways to improve its performance.

**Comment by aismann** [comment]
Please make an "official cpp-test" on clipping section too.
-> It can help to detect "issues" with changes in the future too

**Comment by Yehsam23** [comment]
@aismann 
Is to submit a Pull Request directly in "cpp-tests" to add a clipping node performance test?

**Comment by aismann** [comment]
> @aismann Is to submit a Pull Request directly in "cpp-tests" to add a clipping node performance test?

Yes. thas what I mean (Your test scenario will be part of regular tests then)

**Comment by aismann** [comment]
This is on my machine:
![image](https://user-images.githubusercontent.com/8652787/225542612-03f895fa-14cb-4201-8773-e970497f58ac.png)

**Comment by rh101** [comment]
> This is on my machine (win11, 64b, VS22):

The result is only meaningful when compared to the performance of Cocos2d-x v3.17, as it is the difference in performance of the OpenGL renderer in Cocos2d-x v4/Axmol that is the issue.  Do you have the result of this test on Cocos2d-x v3.17 using the exact same setup to compare?

On a mobile device, using the renderer in Cocos2d-x/Axmol, there is a limit on how many draw calls would be reasonable, and that limit is largely dependent on what the app is rendering.  Anything over a few hundred draw calls cannot be expected to perform well using the current rendering implementation, but the important question here is why there is such a big difference between Cocos2d-x v3.17 and Cocos2d-x v4/Axmol when using OpenGL.

**Comment by Yehsam23** [comment]
Here is the performance test result for 1 frame, using 200 ClippingNode and Sprite each. It seems that the biggest performance difference occurs in GlBufferData().
However, I am not sure what is happening and currently unable to locate the issue.

Axmol:
![capture 2023-03-16 下午4 22 07](https://user-images.githubusercontent.com/1954445/225558628-3533b425-774b-4b24-a706-28b3c6e7e050.png)

Cocos2d-x v3.17:
![capture 2023-03-16 下午4 27 44](https://user-images.githubusercontent.com/1954445/225558646-60facf1e-928d-475f-a837-950e74bd79de.png)

**Comment by rh101** [comment]
> It seems that the biggest performance difference occurs in GlBufferData().

Do you notice that the renderer in Axmol is also doing that twice, taking twice as much time, because of the two calls to `flush()`;  I wonder if that's required, or it's a mistake.  If one of those `flush` calls is eliminated, that alone would a significant performance boost.

**Comment by Yehsam23** [comment]
> Do you notice that the renderer in Axmol is also doing that twice, taking twice as much time, because of the two calls to `flush()`? I wonder if that's required, or it's a mistake. If one of those `flush` calls is eliminated, then that alone would be a significant performance boost.

Because Cocos2d-x v3 does not have a standalone processGroupCommand function, and instead directly uses visitRenderQueue, they are counted together, and in fact, the number of operations is the same: one for Stencil and one for Sprite.

**Comment by rh101** [comment]
> Because Cocos2d-x v3 does not have a standalone processGroupCommand function, and instead directly uses visitRenderQueue, they are counted together, and in fact, the number of operations is the same: one for Stencil and one for Sprite.

Fair enough, so in this case Axmol is taking ~118ms versus ~25ms for Cocos2dx v3.17 for the `GlBufferData()`, which is a massive difference.

**Comment by rh101** [comment]
@Yehsam23 If you have time, I'm curious to know what performance you get out of using round-robin buffering on your Android device.  The changes are to the `BufferGL.cpp` and `BufferGL.h` files in this zip (which go intothe path  `core/renderer/backend/opengl/`).  You can simply overwrite your files with these, with no other changes required.  

On my Android device it went from ~8 FPS to ~27 FPS for the ClippingNode test when using 5 buffers, and any more than that didn't seem to make a difference.  The SpriteA/SpriteB test FPS didn't change.

[BufferGL.zip](https://github.com/axmolengine/axmol/files/10996482/BufferGL.zip)

**Comment by Yehsam23** [comment]
I have started testing my project and it seems to be working normally with a significant improvement in performance. Today, I will try various methods to see if there are any issues.

The changes I made are similar to the issue mentioned earlier with Cocos2d-x [issue](https://github.com/cocos2d/cocos2d-x/issues/15652) 
I tried modifying "TriangleCommandBufferManager::createBuffer()" to not update the data at the beginning, but it resulted in a crash.

BTW, thank you for your help.

**Comment by rh101** [comment]
> I have started testing my project and it seems to be working normally with a significant improvement in performance. Today, I will try various methods to see if there are any issues.

I'm not actually sure if it's the correct way to improve the performance, and there may be other things we can do to also improve performance of the renderer.  If something like this is used as part of the improvements, then it may be best to limit any such modification to Android, and also make it configurable.  Using extra buffers does take up more memory, so leaving it up to the developer to configure whether they need the extra buffers may be the preferred option.


> BTW, thank you for your help.

It's no problem at all.  Any improvements we can make to this game engine benefit everyone using it.  For me personally, I don't mind investigating issues if and when time permits, and more often than not, it's a learning experience.

**Comment by Yehsam23** [comment]
I found something interesting.
I set the BufferCount generated by vertexBuffer in CCRenderer to 1 and set the BufferCount generated by indexBuffer to 10. The performance was great. 
Perhaps the real reason is that something happened with indexBuffer, and generating multiple Buffers happened to solve it.

So far, the @rh101 method that I have been testing has not revealed any issues.

**Comment by rh101** [comment]
That is interesting.  I assume that you've just added an extra parameter to the `Device::newBuffer()`, `DeviceGL::newBuffer` and related methods for the buffer count. I'll do more testing with such a change as well.

The only thing I was concerned about is the `BufferGL::getHandler()` method, which returns the currently used buffer.  As long as it's called within the same cycle as the currently used buffer before the buffer index changes (which I assume is the case, but I'll double check), then all is well.

**Comment by rh101** [comment]
Just noticed something else. With a single buffer for index and a single for vertex (default Axmol implementation), the GPU memory usage is all over the place, as can be seen here, varying from 60MB to 135MB or so (at 8-9FPS):
![image](https://user-images.githubusercontent.com/8603230/225874902-1dfb736b-740f-4a31-b95d-2130f1b1fa0b.png)

When using an index buffer count of 10, and a vertex buffer count of 1, the GPU memory usage is very stable, as follows (at 31-33FPS):
![image](https://user-images.githubusercontent.com/8603230/225875098-d71cb4e1-ee07-48a4-b53f-e792ccb882a0.png)

These tests were carried out on a Google Pixel 5a, using the code supplied in the first post (200 clipping nodes).

**Comment by aismann** [comment]
@rh101 
Will this changes also have affects on destop?

**Comment by rh101** [comment]
> Will this changes also have affects on destop?

I have noticed absolutely no difference in performance with or without the change on desktop, so if we do use these modifications, it should be limited to Android (or OpenGL ES).  

Also, on desktop, 200 clipping nodes don't cause any performance issues on my specific Windows PC, and I only managed to get the FPS to drop when I hit around 450+ clipping zones (still over 50 FPS @ 1350 draw calls).  I cannot imagine any good reason for someone to use that many clipping zones at all.

**Comment by aismann** [comment]
The comparing should be cocos2dx 3.17 vs axmol on desktop too

**Comment by rh101** [comment]
> The comparing should be cocos2dx 3.17 vs axmol on desktop.

On a Windows 10 PC:
At 400 clipping nodes, Axmol ~59 FPS, Cocos2dx v3.17.2 ~59FPS.
At 450 clipping nodes, Axmol ~50 FPS, Cocos2dx v3.17.2 ~58FPS.
At 600 clipping nodes Axmol ~40 FPS, Cocos2dx v3.17.2 ~48 FPS.

The Axmol tests, without or without the modifications listed earlier, give the same results when run on Windows 10.  The difference in FPS may not be solely related to the renderer.

**Comment by aismann** [comment]
> EDIT: Just in case anyone gets the wrong idea by looking at those figures, tests like this are not realistic, especially with the number of draw calls caused by these tests.

Thanks. Right!
But a stress test is also a nice test scenario ;)

**Comment by aismann** [comment]
Another idea to find some improvements:

Comparing the callstack between the axmol Android and Desktop.
Maybe the is something to check?

**Comment by rh101** [comment]
> Comparing the callstack between the axmol Android and Desktop.
> Maybe the is something to check?

It's OpenGL vs OpenGL ES, so there are different code paths due to different functionality, along with completely different GPUs (which are way more powerful on desktop), and that alone would be a reason the desktop rendering has better performance.  Also, `AX_ENABLE_CACHE_TEXTURE_DATA` is set to `true` for Android, but `false` for other platforms, which is extra code that is running for Android, but if I recall correctly, being enabled didn't impact the performance too much.

**Comment by rh101** [comment]
After modifying the code to only change the round-robin buffer index on each frame change (on `Renderer::beginFrame()` etc.), the frame rate improvement was the same as changing the index every time `BufferGL::updateData()` is called (as in my original test code).  Since 10 index buffers and 1 vertex buffer seem to improve this specific test case (200 clipping nodes), then the issue here is that the GPU is lagging behind by 10 frames, and this introduces other issues, such as input lag.  Depending on the type of app/game being created, you would have to factor in the impact this will have.

**Comment by Yehsam23** [comment]
While testing Cocos2d-x v3.17, I found that after the following changes, the FPS drops suddenly, just like the current Axmol.

1. Forcing to use only VBO, because Axmol currently only uses VBO on OpenGL ES.
```
bool Configuration::supportsShareableVAO() const
{
    return false;
    xxxx
}
```

2. Change CCRenderer.cpp
```
void Renderer::setupVBO()
{
    glGenBuffers(2, &_buffersVBO[0]);
    // Issue #15652
    // Should not initialize VBO with a large size (VBO_SIZE=65536),
    // it may cause low FPS on some Android devices like LG G4 & Nexus 5X.
    // It's probably because some implementations of OpenGLES driver will
    // copy the whole memory of VBO which initialized at the first time
    // once glBufferData/glBufferSubData is invoked.
    // For more discussion, please refer to https://github.com/cocos2d/cocos2d-x/issues/15652
    // mapBuffers();
}
```
To
```
void Renderer::setupVBO()
{
    glGenBuffers(2, &_buffersVBO[0]);
    // Issue #15652
    // Should not initialize VBO with a large size (VBO_SIZE=65536),
    // it may cause low FPS on some Android devices like LG G4 & Nexus 5X.
    // It's probably because some implementations of OpenGLES driver will
    // copy the whole memory of VBO which initialized at the first time
    // once glBufferData/glBufferSubData is invoked.
    // For more discussion, please refer to https://github.com/cocos2d/cocos2d-x/issues/15652
    mapBuffers();
}
```

As mentioned earlier, Cocos2d-x also encountered performance issues on Android. Perhaps the real problem lies here, and it may not be necessary to solve it through 10 index buffers.

However, currently, I have not been able to find a way to run it normally without initializing the buffer at the beginning.

**Comment by rh101** [comment]
> I modified the CCRenderer's Renderer::TriangleCommandBufferManager::createBuffer() in Axmol and found that the FPS increased significantly.

Can verify that this modification gives over 3.5x performance increase on Android.  Initialising with only a small chunk of memory seems to do the trick.  

If there are no concerns put forward regarding this change, and if there are no issues with the current cpp-tests, then please consider creating a PR with this modification.

**Comment by Yehsam23** [comment]
I ran cpp-tests for a while and didn't find any issues so far. However, I couldn't test it on Windows because I don't have PC.

**Comment by aismann** [comment]
> I However, I couldn't test it on Windows because I don't have PC.
@rh101 told thats has no effect on desktops (Windows 10/11)

**Comment by rh101** [comment]
> > @rh101 told thats has no effect on desktops (Windows 10/11)

Oh Yehsam is referring to the new changes, not the ones I initially suggested.  So far the new suggested change to `Renderer::TriangleCommandBufferManager::createBuffer()` has been working in my main project on Windows 10, but I'll go through cpp-tests as well to check for any issues.

In the meantime, @Yehsam23 would you please create the PR for the `Renderer::TriangleCommandBufferManager::createBuffer()` change?

**Comment by aismann** [comment]
Great work. Thanks!
