### ISSUE TITLE
New build crash at Splashscreen on iOS

### ISSUE THREAD

**Issue by Josh1603** [axmolengine/axmol#1126]
- axmol version: 1.0.0b10
- device tested on: iPhone 8
- developing environments
   - M2 MacBook Air
   - XCode version: 14.0.1
   - CMake version: 3.24.2

Followed GitHub build instructions as follows:

1. axmol new -p org.axmol.hellocpp -l cpp --portrait HelloCpp
2. cd HelloCpp
3. sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
4. cmake -S . -B build -GXcode -DCMAKE_TOOLCHAIN_FILE=$AX_ROOT/cmake/ios.toolchain.cmake -DPLATFORM=OS64
5. Automatic code signing in Xcode specifying Team with org.axmol.hellocpp  as bundler identifier

Build successful though crashes at Splash screen with some sort of lock issue.

Debug navigator shows:

>Thread 1 Queue: com.apple.main-thread (serial) > 0 _armv8_sve_probe

->  0x103112828 <+0>: eor    z0.d, z0.d, z0.d <<**Thread 1: EXC_BAD_INSTRUCTION (code=1, subcode=0x4a03000)**

>14 start

0x1045c44ac <+408>: bl     0x1045c5220               ; dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)
->  0x1045c44b0 <+412>: mov    x20, x0  <<**Thread 1: EXC_BAD_INSTRUCTION (code=1, subcode=0x4a03000)**

Exception breakpoint shows:

objc_exception_throw ID 2.1 **libobjc.A.dylib**
__cxa_throw ID 2.2 **libc++abi.dylib**

**Comment by rh101** [comment]
Can confirm that this crash is occurring with the latest code (https://github.com/axmolengine/axmol/commit/aeaf78772222abfa8c290dfba61b9849b3140c4a)

**Comment by halx99** [comment]
may caused by openssl

**Comment by rh101** [comment]
> could you try this branch: https://github.com/axmol-bot/axmol/tree/buildware_dist_v48 ?

It's still crashing.  I tried it multiple times with a clean build using branch `buildware_dist_v48` from that repository.

**Comment by halx99** [comment]
Sorry the openssl rollbaking failed in buildware_dist_v48, can confirm this issue caused by update openssl from 3.0.8 to 3.1.0, let's wait robot build the actually openssl-3.0.8 and create pull-request for us.

**Comment by halx99** [comment]
The latest commit should fix this issue.
