### ISSUE TITLE
axmol.cpp:   Impriove AX_DLL const char* axmolVersion()  for better issue information

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#1139]
```
AX_DLL const char* axmolVersion()
{
    return "axmol-1.0.0"
}
```
@halx99 
please add a a "hardcoded" PR like this?
![image](https://user-images.githubusercontent.com/8652787/227910005-6307921b-74be-4e5c-8cbf-dfa5b3bae723.png)
```
AX_DLL const char* axmolVersion()
{
    return "axmol-1.0.0-<Commit date.time>"
}
```
example:

![image](https://user-images.githubusercontent.com/8652787/227910947-ddda2867-0a48-440c-9621-16c053e1bb11.png)
```
AX_DLL const char* axmolVersion()
{
    return "axmol-1.0.0-Mar 26, 2023"
}
```

**Comment by aismann** [comment]
@halx99 its your "cmake" turn?

**Comment by rh101** [comment]
@halx99 The changes in https://github.com/axmolengine/axmol/commit/ee2de093a71ead88c2de6f914b4ce517849eb7be are picking up the .git of the game project, and not the .git in the axmol folder.  The results in the version.h file contain the git build, branch and commit hashes of the game project.
