### ISSUE TITLE
CMake Warning (dev) at thirdparty/CMakeLists.txt:137 (message):

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#1147]
@halx99 
I call:
`cmake -S . -B build -G "Visual Studio 17 2022" -A x64`
and get this warning  (is this ok?):

CMake Warning (dev) at thirdparty/CMakeLists.txt:137 (message):

AX_ISA_SIMD=avx2,AX_HAVE_AVX2_INTRINSICS=1,AX_HAVE_SSE42_INTRINSICS=1,AX_HAVE_SSE41_INTRINSICS=1,AX_HAVE_SSE2_INTRINSICS=1,AX_HAVE_NEON_INTRINSICS=
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by aismann** [comment]
> The best thing to do would be to change line 137 of that `CMakeLists.txt` to remove the `AUTHOR_WARNING`, assuming its only purpose is to show the results of the SIMD intrinsics detection.

But I can leave it as it is too?

**Comment by rh101** [comment]
> But I can leave it as it is too?

Yes, it's fine to be left as-is.

**Comment by aismann** [comment]
closet it
