### ISSUE TITLE
Compilation error:   NEON intrinsics not available with the soft-float ABI

### ISSUE THREAD

**Issue by asnagni** [axmolengine/axmol#1158]
- axmol version:NA
- devices test on: Mac Pro
- developing environments
   - NDK version: N/A
   - Xcode version: N/A
   - Visual Studio: 
      - VS version: N/A
      - MSVC version: N/A
      - Windows SDK version: N/A
   - cmake version: 3.26.2
Steps to Reproduce:

1. Download files from repository
2. Follow installation
3. Create project for ios arm64
4. Build
5. Then I will get the error message: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include/arm_neon.h:28:2 "NEON intrinsics not available with the soft-float ABI. Please use -mfloat-abi=softfp or -mfloat-abi=hard"

Would you know how to fix this issue?
I added the '-mfloat-abi=hard' flag in Compiler flags fo: C Flags & C++ Flags
I also tried the '-mfloat-abi=softfp '

Thank you!

**Comment by halx99** [comment]
The axmol cmake build system haven't add soft-float flag for arm64, for arm64 neon, you don't needs specific any flags.

**Comment by asnagni** [comment]
Hi,
	Yes you are correct. I needed to set manually in Xcode the the architecture to “Standard Architecture “arm64”” 

Thank you,
Stay safe

**Comment by asnagni** [comment]
It's working. Thank you
