### ISSUE TITLE
Lua script  targetPlatform definition miss matched

### ISSUE THREAD

**Issue by yangc999** [axmolengine/axmol#1176]
- axmol version:dev
- devices test on:
- developing environments
   - NDK version: r19c
   - Xcode version: 12.4
   - Visual Studio: 
      - VS version: 2019 (16.11), 2022 (17.4)
      - MSVC version: 1929, 1934
      - Windows SDK version: 10.0.22621.0
   - cmake version: 
Steps to Reproduce:

1. 
2.

**Comment by halx99** [comment]
please provide more detail information

**Comment by yangc999** [comment]
in lua "Constants.lua" definition like this: 
cc.PLATFORM_WINDOWS   = 0
cc.PLATFORM_LINUX     = 1
cc.PLATFORM_MACOS     = 2
cc.PLATFORM_ANDROID   = 3
cc.PLATFORM_IOS       = 4
but in cpp Enum like this:
    enum class Platform
    {
        Windows, /**< Windows */
        UWP,
        UWP_Phone,
        Linux,   /**< Linux */
        macOS,     /**< macOS */
        Android, /**< Android */
        iOS,      /**< Apple iOS */
    };

**Comment by yangc999** [comment]
it cause lua project can not run in mac platform

**Comment by rh101** [comment]
So the only thing missing is the new UWP entries in LUA, which is causing the value of the constants to be incorrect when compared to the C++ enum.

**Comment by rh101** [comment]
> not exactly.I found lua project can not run in mac platform due to initialize error in device.lua miss matched the platform definition.It may remains others.

Have you tried correcting those constants to see if it works?

**Comment by yangc999** [comment]
> Have you tried correcting those constants to see if it works?
I can only confirm mac platform which runs fine after correcting.
