### ISSUE TITLE
RenderTexture memory leak problem

### ISSUE THREAD

**Issue by DelinWorks** [axmolengine/axmol#1190]
- axmol version: v1.0.0
- devices test on: Windows 10
- developing environments
   - Visual Studio: 
      - VS version: 2022 (17.4)
      - MSVC version: 1929, 1934
      - Windows SDK version: 10.0.22621.0
Steps to Reproduce:

RenderTexture Memory leak when created and then released.

1. Create a new helloworld scene
2. put this code in the update function so that it creates a new **autoreleased** ax::RenderTexture every frame and monitor application memory usage.

![image](https://user-images.githubusercontent.com/45469625/234997328-9d182af2-f13f-4091-abe7-fa9c481292e4.png)

the memory leak happens when calling `initWithWidthAndHeight` but not when calling create only, I'm aware that create calls `initWithWidthAndHeight` internally but shouldn't calling `initWithWidthAndHeight` again release everything and  re`initWithWidthAndHeight` the render texture or do I just need to recreate a whole new rendertexture?

one solution would be to make a generic create function that doesnt call `initWithWidthAndHeight` but that doesn't solve the problem of changing the RenderTexture size dynamically.

**Comment by rh101** [comment]
You're right, there is an issue with memory usage increasing, one being because of a memory leak, since `_depthStencilTexture` is not being released, and the other being that the internal sprite isn't removed from the `RenderTexture`, since `initWithWidthAndHeight` always creates a new sprite.  That way you end up with more and more child sprite objects being part of that RenderTexture.

**Comment by rh101** [comment]
Before the PR #1191 (7.2GB in 13 seconds...):
![image](https://user-images.githubusercontent.com/8603230/235045103-a9bb6d4b-5481-4e47-87a3-9e32bb5da369.png)

After the changes, the usage is now steady:
![image](https://user-images.githubusercontent.com/8603230/235044990-73094946-a602-4fea-a609-336b33b5cac5.png)

**Comment by DelinWorks** [comment]
Good job! Thanks for the quick reply.
