### ISSUE TITLE
Add BrashMonkey's "Spriter Pro" (2D game animation tool) to axmol 

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#1193]
See also Discussion #945

## BrashMonkey's Spriter
- Upstream: https://github.com/aismann/Spriter4axmol
- Version: work in progress at the moment (Windows first version) 
- License: zlib license
- License: GreyGuy stuff => "Copyright_Information_Please_Read.txt" (GreGuy folder)

Spriter Pro will be added as an extension 

Some screenshots:
![image](https://user-images.githubusercontent.com/8652787/235306272-4a10e548-c252-4a4c-8289-3b1be5721d6c.png)

First cpp-test for Spriter Pro
![image](https://user-images.githubusercontent.com/8652787/235306314-7eb83186-608d-4ff5-afee-eedd513f3c47.png)

**Comment by aismann** [comment]
@halx99 
Is it ok to add BrashMonkey's "Spriter Pro" (2D game animation tool) to axmol?

Support on my repository:
https://github.com/aismann/Spriter4axmol

**Comment by aismann** [comment]
I will support it on my own site.

**Comment by halx99** [comment]
nice, I also add to https://github.com/axmolengine/axmol/discussions/694
