### ISSUE TITLE
Support for modules

### ISSUE THREAD

**Issue by asnagni** [axmolengine/axmol#1194]
Hi guys,
    I would like to now if you have any idea when the **cxx modules** will be supported? We can pay someone on your team to implement the support as part of our support/contribution to the community.
    
    
Thank you,
Stay safe

**Comment by rh101** [comment]
C++ Modules require C++20, and given that there is functionality in the engine that is limited to C++17 (UWP in particular), supporting modules may not be possible at this point in time.  If anything, you may need to create a separate fork of the engine and have it implemented in there, but merging it back into the engine may not be possible, at least not until everything is compatible with C++20.

Also, it's best if queries like this are put in the _Discussions_ section, and not in the issue tracker.

**Comment by asnagni** [comment]
Hi,
   Thank you for the answer, I do appreciate.

Stay safe

**Comment by aismann** [comment]
@asnagni 
Can it closed?

**Comment by asnagni** [comment]
Yes, thank you
