### ISSUE TITLE
LabelBMFont not rendering on Android device.

### ISSUE THREAD

**Issue by harontoo** [axmolengine/axmol#1256]
- axmol version:1.0.0-41137c6
- devices test on:Windows 11 PC, pixel 6 pro API UpsideDownCake(android emulator) and Tecno K17 android 13(physical device)
- developing environments
   - NDK version: 25.2.9519653
   - Xcode version: N/A
   - Visual Studio: 
      - VS version: 2022 (17.6.4)
      - MSVC version: v142
      - Windows SDK version: 10.0.22621.0
   - cmake version: 3.22.1
   
**Screen Shots**
![Screenshot (19)](https://github.com/axmolengine/axmol/assets/96364614/32459595-5077-4072-bd7d-01c30873fb3f)
![Screenshot (17)](https://github.com/axmolengine/axmol/assets/96364614/427ca214-c04e-4753-8a58-df7f9b76af10)

**Steps to Reproduce:**

1. Create a new Scene
2. Add labelbmtfont(Label::createWithBMFont) as a child and position it somewhere visible on the scene, for example at center.
3. Run the Scene on Android and Windows and see the rendering issue on android device.

**Comment by DelinWorks** [comment]
I can see that only the red one is not showing, could you show the full source or atleast check if the red labelbmfont has a proper font file being loaded? also it would be helpful to share the entire project you got since it seems to be a test project, it would help alot since it has the fonts you used which could potentially be the issue.

**Comment by harontoo** [comment]
> I can see that only the red one is not showing, could you show the full source or atleast check if the red labelbmfont has a proper font file being loaded? also it would be helpful to share the entire project you got since it seems to be a test project, it would help alot since it has the fonts you used which could potentially be the issue.

Hi thanks for the reply, the attached screenshots show the Content folder of my project which contains non-code resources such as fonts and artwork,inside the "uicomponentsresources" folder i have both "bitmapred.fnt" and "bitmapred.png" which complement each other,from the cocos2d-x docs i have read that i need to load only bitmapred.fnt as so   

auto labelbmfont = Label::createWithBMFont("uicomponentsresources/bitmapred.fnt", "LabelBMFont");

Windows works as expected but android does not, can't speak of macOS or iOS as I don't own any apple device so far.

**Screen Shots**
![Screenshot (22)](https://github.com/axmolengine/axmol/assets/96364614/134dc24b-916b-409b-9d86-a77a24dc8eb1)
![Screenshot (23)](https://github.com/axmolengine/axmol/assets/96364614/002054f9-10d5-428a-8c3a-34b5cc60206b)

**Comment by rh101** [comment]
@harontoo At the very least, you need to post the contents of the `bitmapred.fnt` file and the associated image file (or an equivalent that works with the same `bitmapred.fnt`).

**Comment by harontoo** [comment]
@rh101 Hi, after further investigation here is the warning I got on Android Studio,note that this warning doesn't appear on Visual Studio when debugging a win32 project.
![Screenshot (25)](https://github.com/axmolengine/axmol/assets/96364614/6a18b0f2-e1a2-423e-9ef3-3110bead8514)

So renamed "bitmapred.png" to "bitmapRed.png" then rebuilt the project and it finally worked as expected.
![Screenshot (26)](https://github.com/axmolengine/axmol/assets/96364614/b047199a-2364-4810-aa6c-4834a6f96229)

I don't know if this can still be regarded as an issue but I'm curious on why Android projects prefer camel cased names.

here are the files you requested "bitmapred.fnt" and "bitmapred.png"
[bitmapred.zip](https://github.com/axmolengine/axmol/files/11990880/bitmapred.zip)

**Comment by rh101** [comment]
> I don't know if this can still be regarded as an issue but I'm curious on why Android projects prefers camel cased names.

It is the reason I asked to see the files, because I suspected it would be the file name case.  he issue you ran into has nothing to do with the Android project preference or Axmol.   Android OS filesystem is case-sensitive, while Windows OS is not.  Just be careful when naming things, and stick to a specific naming convention for your files so you can spot issues like this easily.  

I for one have run into this problem multiple times, as I'm sure others have too.  Best thing to do is always step into the code that loads the resource with a debugger, and you'll quickly find out why it's not loading.

**Comment by harontoo** [comment]
> > I don't know if this can still be regarded as an issue but I'm curious on why Android projects prefers camel cased names.
> 
> It is the reason I asked to see the files, because I suspected it would be the file name case. The issue you ran into has nothing to do with the Android project preference or Axmol. Android OS filesystem is case-sensitive, while Windows OS is not. Just be careful when naming things, and stick to a specific naming convention for your files so you can spot issues like this easily.
> 
> I for one have run into this problem multiple times, as I'm sure others have too. Best thing to do is always step into the code that loads the resource with a debugger, and you'll quickly find out why it's not loading.

Agreed.
I also looked into bitmapred.fnt and found this information (in the attached screenshot), I hadn't bothered to check since i downloaded the files elsewhere.
Turns out "bitmapred.fnt" expects to find "bitmapRed.png" which I had renamed to "bitmapred.png"😅😅
![Screenshot (27)](https://github.com/axmolengine/axmol/assets/96364614/8291daad-e5c7-4de6-bae4-71ac1ec29294)
