### ISSUE TITLE
Runtime error in archlinux

### ISSUE THREAD

**Issue by Joilnen** [axmolengine/axmol#1273]
- axmol version: 412e398651144fd16ad998f1df9365300f7861f9
- devices test on: laptop
- developing environments
- linux x86_64
   - cmake version: 3.26.4
Steps to Reproduce:

1. axmol run -j 4 -p linux

I got a blackscreen and this error message
[GL:3.3 (Compatibility Profile) Mesa 23.0.3] Ready for GLSL
cocos2d: ERROR: Failed to compile shader, detail: 0:1(1): error: syntax error, unexpected end of file

**Comment by halx99** [comment]
which branch do you use

**Comment by halx99** [comment]
please switch to stable main branch

**Comment by Joilnen** [comment]
I was testing dev, trying main so

**Comment by Joilnen** [comment]
Ok it is working in arch linux after to install powershell
