### ISSUE TITLE
Android compile without Android Studio error

### ISSUE THREAD

**Issue by Joilnen** [axmolengine/axmol#1276]
- axmol version: 1daf87c7684ed62318b2751e0cabc91ad029f964 main branch
- developing environments
   - NDK version: 25.1.8937393

Steps to Reproduce:

1. axmol compile  -j 4 -p android
1.1.0-unknown
Building mode: b'debug'
Using b'Android Studio' project : b'/home/joilnen/Ina/proj.android'
Unknown engine version!

**Comment by halx99** [comment]
Please use powershell build script `$AX_ROOT/build.ps1`, in the future, axmol compile will be redirect to it.

**Comment by Joilnen** [comment]
could you to leave someway to compile without powershell, for small systems that use only linux ? powershell seems to depends from .NET is is huge package that I would like to avoid.

**Comment by halx99** [comment]
Actually, axmol only test and official support ubuntu 22.04+. but microsoft also provide:
[PowerShell archlinux Instructions](https://docs.microsoft.com/powershell/scripting/install/installing-powershell-core-on-linux#arch-linux)

**Comment by JoilnenLeite** [comment]
Installed the powershell it seems works ok but I got this binary doing this command 
pwsh ./build.ps1 -j2 -p android -a armv7
[joilnen@archblackstar Ina]$ file build_armv7/bin/Ina/Ina 
build_armv7/bin/Ina/Ina: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=efd9298a02cc06a0f558f92113502703a53d0466, for GNU/Linux 4.4.0, not stripped

and no apk, where I can get the apk file ?

**Comment by halx99** [comment]
> Installed the powershell it seems works ok but I got this binary doing this command pwsh ./build.ps1 -j2 -p android -a armv7 [joilnen@archblackstar Ina]$ file build_armv7/bin/Ina/Ina build_armv7/bin/Ina/Ina: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=efd9298a02cc06a0f558f92113502703a53d0466, for GNU/Linux 4.4.0, not stripped
> 
> and no apk, where I can get the apk file ?

The apk is in: `<ProjectDir>/proj.android/app/build/outputs/apk/debug`

**Comment by halx99** [comment]
axmol latest can simply execute https://github.com/axmolengine/axmol/blob/dev/install-pwsh.sh to install powershell on macOS, Ubuntu, ArchLinux
