### ISSUE TITLE
Missing files in glslcc repo

### ISSUE THREAD

**Issue by jacereda** [axmolengine/axmol#1280]
```
[ 52%] Built target spirv-remap
make[2]: *** No rule to make target '../3rdparty/glslang/gen_extension_headers.py', needed by 'include/glslang/glsl_intrinsic_header.h'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:531: 3rdparty/glslang/StandAlone/CMakeFiles/glslangValidator.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

**Comment by halx99** [comment]
I guess, you build glslcc by yourself?

**Comment by halx99** [comment]
I'm not sure why you encouter the issue, but the github ci checks success https://github.com/axmolengine/glslcc/actions/runs/5565882431 , and you can download binaries (build by github bot) directly: https://github.com/axmolengine/glslcc/releases

**Comment by jacereda** [comment]
OK, I noticed the build script is doing a partial build (make glslcc), I was just building the whole thing.

Sorry for the noise.
