### ISSUE TITLE
Initial settings different in FastTMXLayer::setupTileSprite()

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#1283]
- axmol version:
Orginal axmol (latest) :
![image](https://github.com/axmolengine/axmol/assets/8652787/f4b45654-5d28-44c2-9d2a-3944a87d3730)

Fixed `FastTMXLayer::setupTileSprite()` (changed  `sprite->setAnchorPoint(Vec2::ZERO);` to  `sprite->setAnchorPoint(Vec2(0.5f, 0.5f));`
![image](https://github.com/axmolengine/axmol/assets/8652787/bbadd7fb-3feb-45ce-a94b-760cd9751f5f)
@halx99 
Can I add this small PR?
The problem is:
You can see on the screenshot the position is now different.
So its also a API change. 

Here is a code snippet which work WHITHOUT changing the API:
`
void FastTMXLayer::setupTileSprite(Sprite* sprite, const Vec2& pos, uint32_t gid)
{
   // sprite->setPosition(getPositionAt(pos));
    sprite->setPositionZ((float)getVertexZForPos(pos));
//    sprite->setAnchorPoint(Vec2::ZERO);
    sprite->setOpacity(this->getOpacity());

    // put the anchor in the middle for ease of rotation.
    sprite->setAnchorPoint(Vec2(0.5f, 0.5f));
    sprite->setPosition(getPositionAt(pos).x + std::roundf(sprite->getContentSize().height / 2),
        getPositionAt(pos).y + std::roundf(sprite->getContentSize().width / 2));

`
![image](https://github.com/axmolengine/axmol/assets/8652787/ce585a04-6cc5-4b82-9508-14ec6a7227d3)

**Comment by halx99** [comment]
Yes, you can

**Comment by rh101** [comment]
@aismann Just one question. Is this actually a bug in the current implementation? Or is it just a preferred initial setting for the anchor point?

**Comment by aismann** [comment]
> @aismann Is this actually a bug in the current implementation? Or is it just a preferred initial setting for the anchor point?

Its look as a bug for me.
Compare the screenshots.
Andf if you look into `FastTMXLayer::setupTileSprite` itself you can see with rotation the anchor point is changing too.
So this fix set the anchor point for all sprites to the same value.

**Comment by rh101** [comment]
> Its look as a bug for me.
> Compare the screenshots.

I don't use tiled functionality, so I don't have an opinion on whether this is classed as a bug or not.  My only concern is that a change like this impacts any existing projects using the tiled functionality, and yet no-one has ever logged this issue as a bug, whether for Cocos2d-x or Axmol.  That is why I'm questioning the reason for the change.

**Comment by aismann** [comment]
> > Its look as a bug for me.
> > Compare the screenshots.
> 
> I don't use tiled functionality, so I don't have an opinion on whether this is classed as a bug or not. My only concern is that a change like this impacts any existing projects using the tiled functionality, and yet no-one has ever logged this issue as a bug, whether for Cocos2d-x or Axmol. That is why I'm questioning the reason for the change.
> 
> Any developers who actually use the tiled functionality should consider giving their opinion on the change before it is merged in.

It woks as before: on the second screenshot I have forgott to adapt the sprite position.
