### ISSUE TITLE
Using HttpClient when there is no internet connection.

### ISSUE THREAD

**Issue by Yehsam23** [axmolengine/axmol#1289]
- axmol version: 1.0 main newest
- devices test on:
- developing environments
   - NDK version: r23
   - Xcode version: 14.3
Steps to Reproduce:

1. After turning off the internet, open cpp-test -> Network Test -> HttpClientTest -> "Test Get."
2. After turning on the internet, if you press "Test Get" again, you will notice that all subsequent connections will still fail.

When there is no internet connection, the first attempt to use HttpClient is as follows:
HttpClient::getInstance()->send(request);
This attempt will fail.

Later, when the internet connection is restored, using the same method to operate HttpClient will result in a perpetual inability to connect.

**Comment by Yehsam23** [comment]
@halx99 
I get the same result on both an Android physical device and an iOS simulator. The video is as follows.

https://github.com/axmolengine/axmol/assets/1954445/fc629efa-8996-4f59-a0a8-f5c82042f13a

**Comment by halx99** [comment]
This issue should be fixed by https://github.com/axmolengine/axmol/commit/1b27df66d61893ea785380f3920ddf6ed2d22443
