### ISSUE TITLE
2d light system to make game have day and night effect

### ISSUE THREAD

**Issue by jcy1001** [axmolengine/axmol#1296]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rh101** [comment]
Isn't this a feature that is game/project specific? It really isn't something that belongs in the game engine.  If you need suggestions or help on how to implement such a thing, then there are more appropriate places to be asking such questions, such as the [Discussions ](https://github.com/axmolengine/axmol/discussions) section.

**Comment by halx99** [comment]
I guess you need: https://www.codeandweb.com/spriteilluminator/tutorials/how-to-use-light-effects-with-axmol-game-engine
