### ISSUE TITLE
i use FastTMXTiledMap to load 300*300 tile ,but it cannt display all

### ISSUE THREAD

**Issue by jcy1001** [axmolengine/axmol#1300]
- axmol version:
windows
![image](https://github.com/axmolengine/axmol/assets/24226340/f3857d53-070f-47b8-a61e-b50a4fb03fef)it can only dispaly part of map

![image](https://github.com/axmolengine/axmol/assets/24226340/a8f835e4-d88d-4a7b-b288-e5db76068151)

**Comment by aismann** [comment]
Any example source plz?

**Comment by jcy1001** [comment]
FastTMXTiledMap* pTiledmap=FastTMXTiledMap::create("TileMap/BattleMap/BattleMap2.tmx");
Layer *layer = Layer::create();
	layer->setPosition(_tileMap->getPosition());
	layer->addChild(_tileMap, 0);

	Size winSize = Director::getInstance()->getWinSize();  
	m_pScrollView = axis::extension::ScrollView::create(winSize,NULL);
	m_pScrollView->setMinScale(MIN_SCALE);
	m_pScrollView->setMaxScale(MAX_SCALE);
	this->addChild(m_pScrollView,0); 
just like this and 


i found 
void FastTMXLayer::updateIndexBuffer()
{
#ifdef AX_FAST_TILEMAP_32_BIT_INDICES
    unsigned int indexBufferSize = (unsigned int)(sizeof(unsigned int) * _indices.size());
#else
    unsigned int indexBufferSize = (unsigned int)(sizeof(unsigned short) * _indices.size());
#endif
    if (!_indexBuffer)
    {
        auto device  = backend::Device::getInstance();
        _indexBuffer = device->newBuffer(indexBufferSize, backend::BufferType::INDEX, backend::BufferUsage::DYNAMIC);
    }
    _indexBuffer->updateData(&_indices[0], indexBufferSize);
}

indexBufferSize is    unsigned int ,may it cause this problem??

**Comment by aismann** [comment]
@jcy1001 
without any source example (300*300 tiles) neverone can give an answer.

**Comment by rh101** [comment]
This is the same issue as #1306 

300 x 300 tiles = 90,000 tiles, which is above the 16384 (128x128) tile limit in the TMX implementation.
