### ISSUE TITLE
Xcode General tab is missing

### ISSUE THREAD

**Issue by asnagni** [axmolengine/axmol#1311]
- axmol version:
- devices test on:
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2
   - Visual Studio: 
      - VS version: 2019 (16.11), 2022 (17.6+)
      - MSVC version: 1929, 1934, 19.35, 19.36, 19.37
      - Windows SDK version: 10.0.22621.0
   - cmake version: 
Steps to Reproduce:

Hi guys,
First of all, I would to say congrats for the first official release 👍. We are trying to migrate from Cocos2d-x to Axmol. Unfortunately, after creating an Axmol project (for Xcode simulator) by following the steps provided on the website (https://github.com/axmolengine/axmol/blob/dev/docs/DevSetup.md), we noticed that from Xcode when you select your target, the General tab is missing. Not having the General Tab in the project makes it challenging. These are few challenges that we have:

1) Select the orientation for iPhone independently
2) Select a different orientation for iPad independently
3) Integrating third party framework like “Firebase” or “onesignal” since they reference the General tab.
4) Configuring the Frameworks, Libraries, and Embedded Content
5) etc...

Please let me know if we missed something in your tutorial/guide for creating an Axmol project.
If that was not the case, we would like to know if there is any plan to fix this issue in the near term?

As a side note this is working for Cocos2d-x regardless if the project targets Simulator or Device.

Thank you,
Stay safe

**Comment by halx99** [comment]
duplicated?

**Comment by asnagni** [comment]
Yes, you can close this one. Thank you very much.
