### ISSUE TITLE
TableViewCell, TableView & TableViewDataSource compilation error

### ISSUE THREAD

**Issue by asnagni** [axmolengine/axmol#1314]
- axmol version: 1.0
- devices test on: iOS 
- developing environments
   - NDK version: n/a
   - Xcode version: 14.3
   - Visual Studio: n/a
      - VS version: n/a
      - MSVC version: n/a
      - Windows SDK version: n/a
   - cmake version: 
Steps to Reproduce:

We are migrating from Cocos2d-x to Axmol and we are having issues  with the classes "TableViewDataSource", "TableView", and "TableViewCell". Our assumption is that these classes are in the namespace 'ax::extension'. But when we build our code that we are trying to migrate to Axmol we will have some compilation errors:

1. error: no type named 'TableView' in namespace 'ax::extension'
2. error: no type named 'TableViewCell' in namespace 'ax::extension'

My questions would be: 
1) The TableView classes, are they in the namespace 'ax::extension'?
2) If the answer to the first question is no, did you move them in a different name space. If yes, what would be that namespace 
3) Perhaps these classes were replaced by new ones. If that is case, what would they be?

Thank you for you help.
Stay safe

**Comment by rh101** [comment]
This kind of question is a little strange, given that any modern IDE or text editor has text search functionality.

The classes are in fact there, in the `ax::extension` namespace, and the files are in the `extensions/GUI` directory: 
![image](https://github.com/axmolengine/axmol/assets/8603230/6bf5badf-aeea-4593-92d3-37c1549fbc5d)

You can also look at the `cpp-tests` to verify that it exists, and how it works in the tests.

So, once you have verified that the code exists within the project (via the aforementioned text search functionality), you then need to look at your own code, and at a guess, it would be either an issue with the `include` statements, or something incorrect in the `CMakeLists.txt` of your project.

The extensions are build by ensuring `AX_ENABLE_EXT_GUI` is set correctly, and it defaults to true in `core/CMakeLists.txt`:
`option(AX_ENABLE_EXT_GUI "Build extension GUI" ON)`

Check if you have set `AX_ENABLE_EXT_GUI` to `OFF` or `false` for some reason.

**Comment by asnagni** [comment]
Hi RH,
	I hope you are doing great. 
	There is no strange questions 😊😊😊😊😊😊. Better ask than pretend to know 😂. We tried lot of things but since we couldn’t solved our issue that is why we asked. We will check to make sure that the option “AX_ENABLE_EXT_GUI” is set to ON.
	We also saw the example that you are referring. It’s the same like cocos2d-x but it was moved (the folder structure is different).  

	I’m sure we missed something that will look obvious to us when we will resume the work tomorrow. Thank you very much for your help, I do appreciate. We will look into it tomorrow. 

Thank you,
Stay safe.

**Comment by asnagni** [comment]
“AX_ENABLE_EXT_GUI” was set to OFF. We set it up to ON and everything was fine.

Thank you

**Comment by asnagni** [comment]
Issue was fixed
