### ISSUE TITLE
NUGET.EXE not being downloaded by setup.ps1 script

### ISSUE THREAD

**Issue by rh101** [axmolengine/axmol#1317]
- axmol version: latest from branches 1.0 and 1.x
- devices test on: PC
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2
   - Visual Studio: 
      - VS version: 2022 (17.6+)
      - MSVC version: 1929, 1934, 19.35, 19.36, 19.37
      - Windows SDK version: 10.0.22621.0
   - cmake version: 3.26.4
Steps to Reproduce:

1. Generate new project with `axmol new -p org.axmol.hellocpp -d . -l cpp --portrait HelloCpp`
2. Run cmake to generate build files inside the `HelloCpp` project directory: `cmake -S . -B build -G "Visual Studio 17 2022" -A x64`

This error pops up:

```
...
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- Including Win32 support
-- AX_USE_ALSOFT=ON
CMake axmol target_precompile_headers
NUGET.EXE not found.
CMake Error at G:/axmol/core/CMakeLists.txt:250 (message):
  Please run setup.ps1 again to download NUGET.EXE, and run CMake again.


-- Configuring incomplete, errors occurred!
```

`setup.ps1` has been run multiple times, and it never downloads NUGET:

```
PS G:\axmol> .\setup.ps1
build1k: PowerShell 5.1.19041.3031
build1k: proj_dir=G:\axmol, prefix=G:\axmol\tools\external
build1k: Using cmake: C:\Program Files\CMake\bin\cmake.exe, version: 3.26.4
build1k: setup successfully, please restart the terminal to make added system variables take effect
PS G:\axmol>
```

This was previously working with the Python `setup.py`.

I can't work on any project at the moment because of this unless I roll back to the version of Axmol with the Python scripts.

**Comment by halx99** [comment]
do you check branch dev?: 
![image](https://github.com/axmolengine/axmol/assets/6977319/fac4534e-8f78-4f91-8c9b-d1aa5b1209ae)

**Comment by rh101** [comment]
> do you check branch dev?:

Just tested dev branch now, and it works, so the problem is only with branches 1.0 and 1.x.

```
PS G:\axmol> git checkout dev
Updating files: 100% (1097/1097), done.
Switched to branch 'dev'
Your branch is up to date with 'origin/dev'.
PS G:\axmol> .\setup.ps1
build1k: PowerShell 5.1.19041.3031
build1k: proj_dir=G:\, prefix=G:\axmol\tools\external
build1k: Downloading https://github.com/axmolengine/glslcc/releases/download/v1.9.3/glslcc-1.9.3-win64.zip to G:\axmol\tools\external/glslcc-win64.zip ...
build1k: Using glslcc: G:\\tools\external\glslcc\glslcc.exe, version: 1.9.3
build1k: Using cmake: C:\Program Files\CMake\bin\cmake.exe, version: 3.26.4
build1k: Downloading https://dist.nuget.org/win-x86-commandline/latest/nuget.exe to G:\axmol\tools\external\nuget\nuget.exe ...
build1k: Using nuget: G:\axmol\tools\external\nuget\nuget.exe, version: latest
build1k: setup successfully, please restart the terminal to make added system variables take effect
PS G:\axmol>
```

**Comment by halx99** [comment]
Fixed

**Comment by rh101** [comment]
All good, working now. Thank you!
