### ISSUE TITLE
[1.x] Cmake error when creating x64 VS project

### ISSUE THREAD

**Issue by rh101** [axmolengine/axmol#1321]
- axmol version: current 1.x branch
- devices test on: Windows 10
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2
   - Visual Studio: 
      - VS version: 2022 (17.6+)
      - MSVC version: 1929, 1934, 19.35, 19.36, 19.37
      - Windows SDK version: 10.0.22621.0
   - cmake version: 3.26.4
Steps to Reproduce:

1. Run `axmol new -p org.axmol.hellocpp -d . -l cpp --portrait HelloCpp`
2. Go into the created HelloCpp folder
3. Run `cmake -S . -B build -G "Visual Studio 17 2022" -A x64`

The following errors appear:

```
...
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error: File G:/HelloCpp/run.bat.in does not exist.
CMake Error at CMakeLists.txt:40 (configure_file):
  configure_file Problem configuring file
...
-- Enabled axmol extensions:cocostudio;ImGui;fairygui;DragonBones;spine;physics-nodes;particle3d;assets-manager;GUI;
-- Configuring incomplete, errors occurred!
```

**Comment by halx99** [comment]
I update the v1.0.1 release tag to `v1.0.1p1`, now should work, Note: 1.x will be deprecated (it only contains webgl1 build support compare with 1.0)

**Comment by rh101** [comment]
Thank you!

> I update the v1.0.1 release tag to `v1.0.1p1`, now should work, Note: 1.x will be deprecated (it only contains webgl1 build support compare with 1.0)

Oh I'm not too concerned about webgl at the moment, but should we be using branch 1.0 instead of 1.x for projects that can't be moved to v2 just yet?

**Comment by halx99** [comment]
Yes, current 1.0 would be lts branch for 1.0.x

**Comment by rh101** [comment]
All good, thank you for clarifying.
