### ISSUE TITLE
can't create new project

### ISSUE THREAD

**Issue by 10100010010001001010** [axmolengine/axmol#1323]
![image](https://github.com/axmolengine/axmol/assets/120378517/3a9cd88c-f955-4dce-9428-4a3fade5c1e2)
and some more errors below. This started after reinstalling Windows and Axmol. Before this, I had to give permission to the installation script, because powershell wrote that script not have a digital signature.

**Comment by rh101** [comment]
@10100010010001001010 Things would be easier if you followed the bug report template.

What command did you use to try to create a new project?

Also, you can temporarily allow the Powershell scripts for the current session with:
`Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass`

**Comment by 10100010010001001010** [comment]
@rh101, i use this command too (Set-ExecutionPolicy). For creating a project i always use "axmol new -p name -l cpp "

**Comment by halx99** [comment]
`axmol new -p name -l cpp -d PROJECT DIR ProjectName`, the v1.0.1 / 1.x broken due to template config file not update, dev/v2.0.0 should works

**Comment by 10100010010001001010** [comment]
I'm getting the same errors on version 2.0.0

**Comment by halx99** [comment]
the incoming v2.0.1 improve axmol console, can you try latest dev branch?

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 10100010010001001010** [comment]
@halx99, could you please provide a link, I’m not very familiar with Github and only see Axmol 2.0.0

**Comment by halx99** [comment]
> @halx99, could you please provide a link, I’m not very familiar with Github and only see Axmol 2.0.0

https://github.com/axmolengine/axmol/archive/refs/heads/dev.zip

**Comment by 10100010010001001010** [comment]
![image](https://github.com/axmolengine/axmol/assets/120378517/ad0dd0d8-c1c4-411a-8045-7fc4d06ee388)
@halx99, and this is what i get) 

my os - win10. Maybe this is due to the mentioned above system security problems? Although i set CurrentUser and Scope values to bypass by default, when i write axmol without PowerShell, i get an error what the file is not digitally signed

**Comment by rh101** [comment]
@10100010010001001010 As the error message shows you, the project name can't be empty.

The command template is this: `axmol new -p YOUR.UNIQUE.ID -d PROJECT_PATH -l [cpp|lua] [--portrait] PROJECT_NAME`

So, for your case, it would be something like:

`axmol new -p UKTS -l cpp UKTS`

**Comment by 10100010010001001010** [comment]
@rh101, It turned out really stupid) I used to create a project this way and didn’t think that the console command had changed) thanks
