### ISSUE TITLE
Incorrect paths used in project creation with Axmol 1.0

### ISSUE THREAD

**Issue by rh101** [axmolengine/axmol#1335]
- axmol version: 1.0
- devices test on:
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2
   - Visual Studio: 
      - VS version: 2022 (17.6+)
      - MSVC version: 1929, 1934, 19.35, 19.36, 19.37
      - Windows SDK version: 10.0.22621.0
   - cmake version: 3.27.5
Steps to Reproduce:

Run this command:
`axmol new -p org.axmol.test -d . -l cpp axmol_test`

It results in these errors (note the "C:\WINDOWS\system32\" prefix on the paths):

![image](https://github.com/axmolengine/axmol/assets/8603230/03be7369-14ae-4b1e-9bab-6b9fd67512f9)

**Comment by halx99** [comment]
Fixed

**Comment by rh101** [comment]
All working, thank you!
