### ISSUE TITLE
[Done, wait for the FairyGUI page update]  Please add Axmol to the runtime list of FairyGUI

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#1345]
@halx99 
Please try to add Axmol to the runtime list of FairyGUI:
![image](https://github.com/axmolengine/axmol/assets/8652787/0dd78630-d570-48b3-b751-ecda6c6d413b)
![image](https://github.com/axmolengine/axmol/assets/8652787/ecf74d49-1f9d-4a9a-9c7d-d7934ad84928)

**Comment by halx99** [comment]
you need contact the author of fairygui

**Comment by aismann** [comment]
I have written an email.
I will closed it if it is done on FairyGUI page
https://fairygui.com/download#download-sdk
