### ISSUE TITLE
label_outline.frag does not draw properly on macOS Metal

### ISSUE THREAD

**Issue by cigumo** [axmolengine/axmol#1349]
I'm not sure why the .y component instead of the .w is being used in this case for Metal.
https://github.com/axmolengine/axmol/blob/bd65e25d1e1c936c256d7070a6389fec2741814b/core/renderer/shaders/label_outline.frag#L25

```
#ifndef GLES2
    float fontAlpha = texColor.y;
#else
    float fontAlpha = texColor.w;
#endif
```

This breaks the outline drawing, leaving only the outline and the font with the same color. 
Changing the .y back to .w fixes the issue. 
Maybe the ifdef should consider metal and other backends?

**Comment by halx99** [comment]
fixed in latest dev: https://github.com/axmolengine/axmol/commit/dcf2101b4c3538ad9997279db03a5a17a1c8e525

**Comment by cigumo** [comment]
Thanks!
