### ISSUE TITLE
EventListenerTouchAllAtOnce incorrect

### ISSUE THREAD

**Issue by NgVThangBz** [axmolengine/axmol#1358]
- axmol version: axmol-2.1.0-3db8a73
- devices test on: ipad 7th, iphone 13 promax
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2
Steps to Reproduce:
![Screenshot 2023-09-27 at 08 07 51](https://github.com/axmolengine/axmol/assets/125545428/c545e60f-e0c1-4942-8c02-9f35566b5fbe)
1. use sample project
2. use multi touch, touchs size `always` = 1;
3. i debug in  EAGLView-ios.mm in onTouch ( image bellow) `touches size` is 1, but `(UIEvent*)event.allTouches` have size 2
![image](https://github.com/axmolengine/axmol/assets/125545428/3adbbb22-3d86-48e0-8701-dc3793926927)
please check it

**Comment by rh101** [comment]
Would you care to state how you resolved this issue?  Was it an issue in your own code, or a bug in Axmol?

**Comment by NgVThangBz** [comment]
you can see it here: https://github.com/axmolengine/axmol/discussions/1356#discussioncomment-7118266
just need : [[__glView setMultipleTouchEnabled:YES];](https://stackoverflow.com/questions/21576101/how-to-enable-multitouch-in-cocos2d-x-ios-game-using-c)
you can enable it default

**Comment by rh101** [comment]
> you can enable it default

It's actually already in the code, and enabled by default in the view creation, but I just found out that it's being explicitly disabled in the project code:

You can see here that it is enabled:
```
bool GLViewImpl::initWithRect(std::string_view viewName, const Rect& rect, float frameZoomFactor)
{
    CGRect r = CGRectMake(rect.origin.x, rect.origin.y, rect.size.width, rect.size.height);
    convertAttrs();
    CCEAGLView* eaglView = [CCEAGLView viewWithFrame:r
                                         pixelFormat:(NSString*)_pixelFormat
                                         depthFormat:_depthFormat
                                  preserveBackbuffer:NO
                                          sharegroup:nil
                                       multiSampling:NO
                                     numberOfSamples:0];

    // Not available on tvOS
#if !defined(AX_TARGET_OS_TVOS)
    [eaglView setMultipleTouchEnabled:YES];
#endif

    _screenSize.width = _designResolutionSize.width = [eaglView getWidth];
    _screenSize.height = _designResolutionSize.height = [eaglView getHeight];
    //    _scaleX = _scaleY = [eaglView contentScaleFactor];

    _eaglView = eaglView;

    return true;
}
```

But then it is disabled in several places:
![image](https://github.com/axmolengine/axmol/assets/8603230/eb32456c-6dd4-4e0c-980c-d44368bb92b1)

Such as the RootViewController.mm of the cpp and lua project templates:
```
// Implement loadView to create a view hierarchy programmatically, without using a nib.
- (void)loadView
{
    // Initialize the CCEAGLView
    CCEAGLView* eaglView = [CCEAGLView viewWithFrame:[UIScreen mainScreen].bounds
                                         pixelFormat:(__bridge NSString*)ax::GLViewImpl::_pixelFormat
                                         depthFormat:ax::GLViewImpl::_depthFormat
                                  preserveBackbuffer:NO
                                          sharegroup:nil
                                       multiSampling:ax::GLViewImpl::_multisamplingCount > 0 ? YES : NO
                                     numberOfSamples:ax::GLViewImpl::_multisamplingCount];

    // Enable or disable multiple touches
#if !defined(AX_TARGET_OS_TVOS)
    [eaglView setMultipleTouchEnabled:NO];
#endif

    // Set EAGLView as view of RootViewController
    self.view = eaglView;
}
```

That's been the case since Cocos2d-x, and I'm not sure why it was set to NO by default in the template code.

**Comment by NgVThangBz** [comment]
I'm not sure about this, but if possible you should fix it a bit

**Comment by rh101** [comment]
@halx99 Should the iOS project template code be change to enable multi-touch by default?

**Comment by halx99** [comment]
> @halx99 Should the iOS project template code be change to enable multi-touch by default?

shoud be, do it

**Comment by halx99** [comment]
done by https://github.com/axmolengine/axmol/commit/b07cbc5255ae8bb08e6289e87397cc4985eb2569
