### ISSUE TITLE
Data::fastSet function logic changed

### ISSUE THREAD

**Issue by solan-solan** [axmolengine/axmol#1369]
- axmol version:
- devices test on:
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2
   - Visual Studio: 
      - VS version: 2019 (16.11), 2022 (17.6+)
      - MSVC version: 1929, 1934, 19.35, 19.36, 19.37
      - Windows SDK version: 10.0.22621.0
   - cmake version: 
Steps to Reproduce:

I used the function such a way:

![image](https://github.com/axmolengine/axmol/assets/73186496/15649729-868a-4fca-aa0d-07fe9ddf5296)

Now, Data::_impl.attach_abi(...) will free memory inside _Tidy() through the _Alloc::reallocate, and returned pointer is invalidated. It does not look like expected behavior

![image](https://github.com/axmolengine/axmol/assets/73186496/a9a8025c-ecef-4900-a73e-55ecd74877de)

(updated axmol up to 798689a6102e61e5da72821cda1cff69ba162a1b [798689a])

**Comment by halx99** [comment]
use takeBuffer is better in your use case

**Comment by solan-solan** [comment]
yes, it will fit, thanks
