### ISSUE TITLE
TMX sprites issue

### ISSUE THREAD

**Issue by Joilnen** [axmolengine/axmol#1382]
after this changes 48629f9cb13ebe47d90cfda8be2f1fdefc3fbf38
in codes like 

auto spirte = map->getTileAt(Vec(1, 1));
sprite->setAnchorPoint(Vec2(0, 0));

is changing the sprite position when should change only anchor point position for sprite got from tmx map

**Comment by halx99** [comment]
@aismann could you take a look?

**Comment by aismann** [comment]
> auto spirte = map->getTileAt(Vec(1, 1));
> sprite->setAnchorPoint(Vec2(0, 0));

@Joilnen 
Sorry This code makes no sense.
Why you change the AnchorPoint?

**Comment by Joilnen** [comment]
just try this with axmol pre commit, and check if it gives the same result in master, to me seems changing the position of sprite, but setAnchorPoint should to change only position of anchor point

**Comment by aismann** [comment]
> just try this with axmol pre commit, and check if it gives the same result in master, to me seems changing the position of sprite, but setAnchorPoint should to change only position of anchor point

Thats not correct:
If you change the anchorPoint you change also the position: look:
![image](https://github.com/axmolengine/axmol/assets/8652787/f4badf9e-71b3-4953-bd1d-1816ef2fcf1a)
```
 // add "HelloWorld" splash screen"
 auto sprite = Sprite::create("HelloWorld.png"sv);
 auto sprite1 = Sprite::create("HelloWorld.png"sv);
 if (sprite == nullptr)
 {
     problemLoading("'HelloWorld.png'");
 }
 else
 {
     // position the sprite on the center of the screen
     sprite->setPosition(Vec2(visibleSize.width / 2 + origin.x, visibleSize.height / 2 + origin.y));
     sprite->setAnchorPoint(Vec2(1, 1));
     this->addChild(sprite, 0);

     sprite1->setPosition(Vec2(visibleSize.width / 2 + origin.x, visibleSize.height / 2 + origin.y));
 //    sprite1->setAnchorPoint(Vec2(1, 1));
     this->addChild(sprite1, 0);

     auto drawNode = DrawNode::create();
     drawNode->setPosition(Vec2(0, 0));
     addChild(drawNode);

     drawNode->drawRect(safeArea.origin + Vec2(1, 1), safeArea.origin + safeArea.size, Color4F::BLUE);
 }

```

Changing the AnchorPoint makes only/often sense if you want change the rotating behavior (but you have to control the postion too).

@Joilnen 
I think you can close this issue?

**Comment by Joilnen** [comment]
Yes nothing with anchor point maybe but for some reason master is behaving different from old version, I am gonna to try to send you a code and data leave it open until that

**Comment by rh101** [comment]
> Yes nothing with anchor point maybe but for some reason master is behaving different from old version, I am gonna to try to send you a code and data leave it open until that

The changes made in PR #1285 definitely do change the behavior, which was the intention of that PR, and not a side-effect.

PR #1285 and the related issue #1283 were open since late July, and the issue closed and PR merged only in the last week.  It was hoped that developers using the tile map code would give their input regarding those changes prior to this occurring, but unfortunately no-one did so.

Now, regardless of that, knowing that the behavior has changed, what we need to know is:

1 - Can you adjust your game code to cater for the updated behavior?
2 - If there is no trivial way to adjust your game code to cater for this new behavior, and you consider this to be a bug, then please explain your reasoning, and show examples of your usage if possible, so we can better understand the issue.

**Comment by aismann** [comment]
@Joilnen 
Last but not least: You can use the Axmol 1.x path for your project
(Axmol 2.x has some more API changes which be different to 1.x)

**Comment by aismann** [comment]
@Joilnen
I think you can close this issue or have you one more question?

**Comment by Joilnen** [comment]
Ok What I could figure out of this was I had made some corrections, because this showed me slightly out of the position in old code, so when I update the axmol my scene showed me this out position again, I guess your commit fixed that, I am closing this one time it seems working better, I don't need to make those correction in code anymore, thanks

**Comment by aismann** [comment]
> Ok What I could figure out of this was I had made some corrections, because this showed me slightly out of the position in old code, so when I update the axmol my scene showed me this out position again, I guess your commit fixed that, I am closing this one time it seems working better, I don't need to make those correction in code anymore, thanks

Thats was the reason for this PR. Thanks for feedback.
