### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by rh101** [axmolengine/axmol#1389]
- axmol version: https://github.com/axmolengine/axmol/commit/ed867743a2e142c30d492b2391340e691247625a
- devices test on:
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2
   - Visual Studio: 
      - VS version: 2019 (16.11), 2022 (17.6+)
      - MSVC version: 1929, 1934, 19.35, 19.36, 19.37
      - Windows SDK version: 10.0.22621.0
   - cmake version: 
Steps to Reproduce:

Something is causing a crash in the scheduler due to the latest changes introduced in PR [1379](https://github.com/axmolengine/axmol/pull/1379). 

Create a new project, and add this line to `HelloWorldScene::init()`: 

`ax::network::HttpClient::getInstance();`

For example:

```
bool HelloWorld::init()
{
...
...
    scheduleUpdate();

    ax::network::HttpClient::getInstance();

    return true;
}
```

Compile and run the application, then close the window/exit the app.  It will crash:

![image](https://github.com/axmolengine/axmol/assets/8603230/bf7fd9e4-a7c5-4ab8-969c-cd298f4f0a11)

Also reproducible in the cpp_tests project. Navigate to "18:Network Test"->"1:HttpClientTest"->"Test Get", then close the application, and it will crash.

**Comment by rh101** [comment]
Once `unscheduleAllForTarget(target);` is called, that entry is removed from `_timersMap` inside `unscheduleAllForTarget`, and when it returns, `_timersMap.size()=0`, but for some reason it retrieves invalid values and enters that code block, calling `unscheduleAllForTarget` with an invalid value of `target`.  

I assumed it had something to do with an invalid iterator due to the call to `_timersMap.erase`, so changing the code to the following fixed it for me (although I'm not sure if this is the most optimal way to fix it):

```
std::vector<void*> targetsToUnschedule;
targetsToUnschedule.reserve(_timersMap.size());

// Custom Selectors
for (auto& [target, timerHandle] : _timersMap)
{
    targetsToUnschedule.emplace_back(target);
}

for (auto&& target : targetsToUnschedule)
{
    unscheduleAllForTarget(target);
}

targetsToUnschedule.clear();
```

**Comment by solan-solan** [comment]
I just wanted to clarify one thing. There appeared an error for me which caused to updated sheduler, which I have not seen before.

It happend in the code like this

```
Object1::update()
{
    Object2::unsheduleUpdate();
    Object3::sheduleUpdate();
}
```

After that, the error can happen here from time to time (not always):
![image](https://github.com/axmolengine/axmol/assets/73186496/bf838b03-2e66-40cf-ae81-05d340f2635b)

Now I am not completely sure that it is not my issue in some other place, by the way - 
Could you please confirm that this operation is safe, since _updates0List was list entry before, and now it is sequence vector?
Could be memory relocation in this vector while this operation:
![image](https://github.com/axmolengine/axmol/assets/73186496/0e6ad770-ef35-4a7c-84c9-f1c8695070ca)

**Comment by halx99** [comment]
shoud guard by _indexMapLocked:
```cpp
        auto& sched = updateIt->second;
        if (!_indexMapLocked) {
            axstd::erase(sched->owner, sched);
            delete sched;
        }
        else
        {
            sched->markedForDeletion = true;
            _updateDeleteVector.emplace_back(sched);
        }
```

And: 
```cpp
    // delete all updates that are removed in update
    for (auto&& sched : _updateDeleteVector) {
        axstd::erase(sched->owner, sched);
        delete sched;
    }
```

**Comment by rh101** [comment]
@halx99 I've noticed that the size of `_updates0List` changes (increases) while it's performing the loop, and in my case, there are no made to `unschedule*****` within that loop, so it may not be related to the unscheduling code. For example:

```
    auto size = _updates0List.size(); // Example size = 21 here
    // updates with priority == 0
    for (auto&& entry : _updates0List)
    {
        if ((!entry->paused) && (!entry->markedForDeletion)) // crashes here, but _updates0List.size() = 29 
        {
            entry->callback(dt);
        }
    }
```

So, assuming the callbacks are adding more schedule entries, would the act of adding items to the `_updates0List` affect the iterator of that loop? Are the entries in `_updates0List` sorted at all (which I assume would impact the iterator)?

Also, I've discovered that the entry in the previous loop, before it crashes, is actually still valid and in the `_updates0List`, so it's 100% not unscheduling anything.  It seems to be the iterator that becomes invalid for some reason.

**Comment by solan-solan** [comment]
@halx99 I agree that it is and if shed was marked for erasing its update should not be called, otherwise it breaks game logic

As @rh101 mentioned, adding of elements should also be taken into account?

**Comment by rh101** [comment]
@halx99 Could this be happening:

From [here](https://en.cppreference.com/w/cpp/container/vector/emplace_back):

"If after the operation the new [size()](https://en.cppreference.com/w/cpp/container/vector/size) is greater than old [capacity()](https://en.cppreference.com/w/cpp/container/vector/capacity) a reallocation takes place, in which case all iterators (including the [end()](https://en.cppreference.com/w/cpp/container/vector/end) iterator) and all references to the elements are invalidated. Otherwise only the [end()](https://en.cppreference.com/w/cpp/container/vector/end) iterator is invalidated."

because of this:
```
void Scheduler::appendIn(axstd::pod_vector<SchedHandle*>& list,
                         const ccSchedulerFunc& callback,
                         void* target,
                         bool paused)
{
    auto sched = new SchedHandle(list, callback, target, 0, paused);
    list.emplace_back(sched);
    _schedIndexMap.emplace(target, sched);
}
```
