### ISSUE TITLE
Live2D Android build issue

### ISSUE THREAD

**Issue by rh101** [axmolengine/axmol#1406]
- axmol version: https://github.com/axmolengine/axmol/commit/05e3ddd1a1cec564d65cda826d1ff150f23fdbc3
- devices test on:
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2
   - Visual Studio: 
      - VS version: 2019 (16.11), 2022 (17.6+)
      - MSVC version: 1929, 1934, 19.35, 19.36, 19.37
      - Windows SDK version: 10.0.22621.0
   - cmake version: 
Steps to Reproduce:

Live2d has the following in `Live2D/CMakeLists.txt`:
```
if (ANDROID)
    target_link_libraries(${LIB_NAME} INTERFACE Live2DCubismCore)
else()
    target_link_libraries(${LIB_NAME} Live2DCubismCore)
endif()
```

Then when it calls `setup_ax_extension_config(${LIB_NAME})`, it links with Axmol:
```
function(setup_ax_extension_config target_name)
  set(options DNTLINK opt_DNTLINK)
  cmake_parse_arguments(opt "" "${options}" ""
                          "" ${ARGN} )

  target_link_libraries(${target_name} ${_AX_CORE_LIB})
...
```

It results in the following error when running cmake for the Android build:
```
CMake Error at G:/game_engines/axmol/extensions/CMakeLists.txt:14 (target_link_libraries):
The keyword signature for target_link_libraries has already been used with
the target "Live2D".  All uses of target_link_libraries with a target must
be either all-keyword or all-plain.
```

Is the "INTERFACE" scope required for Android in this line?
`target_link_libraries(${LIB_NAME} INTERFACE Live2DCubismCore)`

If it is required, then a suggested fix:

Adjust `setup_ax_extension_config` to allow for optional link scope argument, for example: 

```
function(setup_ax_extension_config target_name)
  set(options DNTLINK opt_DNTLINK)
  set(options LINK_SCOPE opt_LINK_SCOPE)
  cmake_parse_arguments(opt "" "${options}" ""
                          "" ${ARGN} )

  target_link_libraries(${target_name} ${opt_LINK_SCOPE} ${_AX_CORE_LIB})
```

Which would be called like this:
`setup_ax_extension_config(${LIB_NAME} LINK_SCOPE PRIVATE)`

The above modification to `setup_ax_extension_config` has been tested, and it works, without affecting any other extensions.

**Comment by halx99** [comment]
lgtm, I think you can post a PR to fix it?

**Comment by rh101** [comment]
> lgtm, I think you can post a PR to fix it?

Sure, I'll post a PR up soon.
