### ISSUE TITLE
Command line build issue when folder name differs from project name

### ISSUE THREAD

**Issue by rh101** [axmolengine/axmol#1408]
- axmol version: https://github.com/axmolengine/axmol/commit/b56a60ad838def6e69206f19ca4701f42ca52c79
- devices test on:
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2
   - Visual Studio: 
      - VS version: 2019 (16.11), 2022 (17.6+)
      - MSVC version: 1929, 1934, 19.35, 19.36, 19.37
      - Windows SDK version: 10.0.22621.0
   - cmake version: 
Steps to Reproduce:

Run this command: `axmol new -p org.axmol.hellocpp -d C:\dev\ -l cpp --portrait HelloCpp`

A project is created in a directory named "HelloCpp".

Now rename the "HelloCpp" directory to "HelloCppTemp"

Attempting to use `axmol build -p win32 -a x64` results in an error, because it cannot find a project named "HelloCppTemp".  It seems to be using the project path to resolve the project name.  If the directory is renamed back to "HelloCpp", then it works. It should not work this way, since the folder name can be anything, and is unrelated to the project name set in `CMakeLists.txt`.

Example error:
```
build1k: BUILD_ALL_OPTIONS=--target HelloCppTemp --config Debug --parallel, Count=5
MSBuild version 17.7.2+d6990bcfa for .NET Framework
MSBUILD : error MSB1009: Project file does not exist.
Switch: HelloCppTemp.vcxproj
build1k: Build done
```

This has been tested on both Windows and MacOS; the same issue occurs on both.

@halx99 Is there any way we can pass the correct project name to the `axmol build` command? For example: `axmol build -p win32 -a x64 -t HelloCpp`, where `-t` is the target project name?  Or, if the axmol build script can somehow automatically detect the relevant project name from the generated build folder?

**Comment by halx99** [comment]
-xb "--target,HelloCpp"

**Comment by rh101** [comment]
> -xb "--target,HelloCpp"

That works fine, thank you!

Perhaps this can be added to the documentation too so that other developers are aware of it.

**Comment by halx99** [comment]
yes, and -xc for cmake config options
