### ISSUE TITLE
DrawNode: setLineWitdh() is no longer working

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#1411]
Steps to Reproduce:
cpp-tests->31:Node:Draw>GitHub Issue #11942 (axmol #137)"

Wrong:  Latest build:
![image](https://github.com/axmolengine/axmol/assets/8652787/a94dce8e-f398-4de5-87dd-7fc300897ff1)

Works: Thats a older version
![image](https://github.com/axmolengine/axmol/assets/8652787/8bef719b-26fe-4689-bc8e-480c182256c2)

**Comment by halx99** [comment]
Not recommand use setLineWith because the render backend opengl & metal have diferrent behavior:

- GLES2: support glLineWidth
- GLES3: only support glLineWidth (0~1)
- Metal: not support lineWidth

**Comment by joprice** [comment]
I hit this as well and found a workaround by taking the `drawSolidCircle` code and calling `drawPolygon` instead of`drawSolidPoly` and passing thickness along:

```c++
 static void drawCircle(DrawNode &node, const Vec2 &center, float radius, float angle, int segments,
                         float scaleX, float scaleY, const Color4F &color, float thickness) {
    const float coef = 2.0f * (float)M_PI / static_cast<float>(segments);

    Vec2 *vertices = new (std::nothrow) Vec2[segments];
    if (vertices == nullptr)
      return;

    for (unsigned int i = 0; i < segments; i++) {
      float rads = static_cast<float>(i) * coef;
      float j = radius * cosf(rads + angle) * scaleX + center.x;
      float k = radius * sinf(rads + angle) * scaleY + center.y;

      vertices[i].x = j;
      vertices[i].y = k;
    }
    node.drawPolygon(vertices, segments, Color4F(), thickness, color);

    CC_SAFE_DELETE_ARRAY(vertices);
  }
```

Might be of help to someone, or could perhaps become a new helper if it seems useful enough.
