### ISSUE TITLE
[UWP] Build errors

### ISSUE THREAD

**Issue by rh101** [axmolengine/axmol#1420]
- axmol version: 2.0, dev branch, https://github.com/axmolengine/axmol/tree/1948c4c06603973c4d952b01bf2ebb75111a8a9c
- devices test on:
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2
   - Visual Studio: 
      - VS version: 2022 (17.6+)
      - MSVC version: 1929, 1934, 19.35, 19.36, 19.37
      - Windows SDK version: 10.0.22621.0
   - cmake version: 
Steps to Reproduce:

1. Generate a new project, such as `axmol new -p org.axmol.hellocpp -d . -l cpp HelloCpp`
2. Run: `axmol build -p winuwp`
3. Project builds partially, and no executable is generated
4. Open the `HelloCpp.sln` file. Attempt to build. Many errors are generated:
![image](https://github.com/axmolengine/axmol/assets/8603230/5b918e17-793f-4f62-a9cc-08d969f8b084)

I can see that the file `module.g.cpp` does actually exist:
![image](https://github.com/axmolengine/axmol/assets/8603230/f4314e22-36f5-43e4-8f2e-f174aa82cbfb)

Is there something else that needs to be done in order to get a successful build?

**Comment by halx99** [comment]
Do you install visual studio C++ UWP workflow?

**Comment by rh101** [comment]
> Do you install visual studio C++ UWP workflow?

I've got all of these already installed:
![image](https://github.com/axmolengine/axmol/assets/8603230/520ac21d-2d3c-4ef7-ac76-eef7f95af820)

Is that what you are referring to?

**Comment by halx99** [comment]
> > Do you install visual studio C++ UWP workflow?
> 
> I've got all of these already installed: ![image](https://user-images.githubusercontent.com/8603230/280593061-520ac21d-2d3c-4ef7-ac76-eef7f95af820.png)
> 
> Is that what you are referring to?

yes, i have tests, can build in engine root directory, can't build in unique project, I have no idea yet

**Comment by rh101** [comment]
This section of `AXBuildHelpers.cmake`:

```
macro (ax_setup_app_props app_name)
    if(WINRT)
        get_target_property(app_vcxproj_dir ${APP_NAME} BINARY_DIR)
        configure_file(
            "${_AX_ROOT}/cmake/Directory.Build.targets.in"
            "${app_vcxproj_dir}/Directory.Build.targets"
            COPYONLY
        )
```

The `Directory.Build.targets.in` contains this:
```
<Project>
  <ItemGroup>
    <ClCompile Include="$(GeneratedFilesDir)module.g.cpp" />
  </ItemGroup>
  <ItemDefinitionGroup>
    <Midl><OutputDirectory /></Midl>
  </ItemDefinitionGroup>
</Project>
```

The issue may possibly be that `$(GenerateFilesDir)` macro is mapped to this:
![image](https://github.com/axmolengine/axmol/assets/8603230/698b4864-5159-49e8-b620-0851592c6b96)

If we instead use this in `Directory.Build.targets.in`:
`    <ClCompile Include="$(SolutionDir)$(GeneratedFilesDir)module.g.cpp" />`

Then that error goes away, as it results in the full path. For example:
`C:\dev\HelloCpp\build_winuwp_x64\Generated Files\module.g.cpp`


Once I got past the above error, I get new errors now:

![image](https://github.com/axmolengine/axmol/assets/8603230/a52f8e97-bacb-45ca-909f-1cc94def4a97)

I see this for the `unzip` project:
![image](https://github.com/axmolengine/axmol/assets/8603230/3ff3b9bd-5333-4b84-a630-8454f6fce58f)

A number of extensions all have the default C++14 set, so I changed them manually to C++20, and they all compiled.

The next issue is the include directories.  The "Generated Files" is not correctly included:
![image](https://github.com/axmolengine/axmol/assets/8603230/f69b9f5a-3d98-433d-bc9b-fabfe10247fa)


It maps to an invalid path, being "Generated Files/".  I manually added `$(SolutionDir)$(GeneratedFilesDir)` to the list, and now it correctly compiles.  This led to another issue, which is this:

```
Error	LNK2019	unresolved external symbol "void * __cdecl winrt_make_AxmolAppWinRT_XamlMetaDataProvider(void)" (?winrt_make_AxmolAppWinRT_XamlMetaDataProvider@@YAPEAXXZ) referenced in function "void * __cdecl winrt_get_activation_factory(class std::basic_string_view<wchar_t,struct std::char_traits<wchar_t> > const &)" (?winrt_get_activation_factory@@YAPEAXAEBV?$basic_string_view@_WU?$char_traits@_W@std@@@std@@@Z)	OpenAL	C:\dev\HelloCpp\build_winuwp_x64\engine\thirdparty\openal\module.g.obj	1	
Error	LNK2019	unresolved external symbol "void * __cdecl winrt_make_AxmolAppWinRT_OpenGLESPage(void)" (?winrt_make_AxmolAppWinRT_OpenGLESPage@@YAPEAXXZ) referenced in function "void * __cdecl winrt_get_activation_factory(class std::basic_string_view<wchar_t,struct std::char_traits<wchar_t> > const &)" (?winrt_get_activation_factory@@YAPEAXAEBV?$basic_string_view@_WU?$char_traits@_W@std@@@std@@@Z)	OpenAL	C:\dev\HelloCpp\build_winuwp_x64\engine\thirdparty\openal\module.g.obj	1	
```

In the `Generated Files`, there are a lot more files than just `module.g.cpp`, but they aren't referenced anywhere to be compiled. For example:
![image](https://github.com/axmolengine/axmol/assets/8603230/741a8e6d-427c-4632-81d3-325b366d86ae)

Do all of them have to be added to `Directory.Build.targets.in`?

**Comment by halx99** [comment]
No, only module.g.cpp required
