### ISSUE TITLE
Vertical center alignment within each line of RichText

### ISSUE THREAD

**Issue by rh101** [axmolengine/axmol#1463]
**Is your feature request related to a problem? Please describe.**

The current implementation of RichText forces all elements to be drawn from the anchor point (0,0) on each line, and this is not adjustable, so for example, this is the result when images are on a line:

![image](https://github.com/axmolengine/axmol/assets/8603230/e4dc3885-e97c-4630-89cc-ed85846d063e)
![image](https://github.com/axmolengine/axmol/assets/8603230/66656159-258e-4b58-b3e9-602ed72db026)
![image](https://github.com/axmolengine/axmol/assets/8603230/f5b8f0b7-26cc-4eb9-8b92-b7ece8151e93)

**Describe the solution you'd like**

The preference is that text and images are center-aligned vertically on a line, so the output would be as follows:
![image](https://github.com/axmolengine/axmol/assets/8603230/44e03d7a-bd5c-4084-a00e-7bddc3e39ef9)
![image](https://github.com/axmolengine/axmol/assets/8603230/7bff8588-259d-45c0-96b2-3555d8de76ab)
![image](https://github.com/axmolengine/axmol/assets/8603230/67be1aec-2478-40d8-bc77-72c1ee0349cd)

A few solutions I can think of at the moment:

1 - The easiest solution is to force the center vertical alignment, rather than bottom vertical alignment, but developers may prefer to keep it as it is at the moment.
2 - Add a new method to RichText that allows the developer to set vertical alignment that applies to all lines.
3 - Add support to configure the alignment per RichText element, so each line in the RichText can have a different vertical alignment setting.

Which would be preferred (or any other suggestions)?

**Comment by rh101** [comment]
Unless anyone objects, I'll create PR for option 2, which is to create a new setting that applies to all elements in the RichText, with TOP, CENTER and BOTTOM vertical alignment.  It will default to BOTTOM to keep the functionality the same as the current implementation.

**Comment by halx99** [comment]
I prefer option 2
