### ISSUE TITLE
Compiling cpp-tests causes VS to crash on occasion due to #1434

### ISSUE THREAD

**Issue by rh101** [axmolengine/axmol#1464]
- axmol version:
- devices test on:
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2
   - Visual Studio: 
      - VS version: 2019 (16.11), 2022 (17.6+)
      - MSVC version: 1929, 1934, 19.35, 19.36, 19.37
      - Windows SDK version: 10.0.22621.0
   - cmake version: 
Steps to Reproduce:

Over 10000 warnings pop up due to the changes made in #1434, which causes Visual Studio to randomly lock up and crash during compilation.

For example:
![image](https://github.com/axmolengine/axmol/assets/8603230/bbe9c8a1-13b1-4ef8-a010-8e34176d7eb3)

The values in the arrays should be floats, but they are missing the `f` suffix, so are being treated as type `double`.  Due to the large amount of data embedded in the source, it also slows down compilation, so it may be better to have these values in an external data file that is processed when that specific test is initiated.

**Comment by aismann** [comment]
Is this fixed if the value(s) be float?

**Comment by rh101** [comment]
> Is this fixed if the value(s) be float?

Yes, adding the "f" suffix should stop the large number of warnings, which is probably what is causing the VS IDE to lock up.

**Comment by aismann** [comment]
Can you make a PR?
I can do it later also.

**Comment by rh101** [comment]
> Can you make a PR? I can do it later also.

Sure, I'll sort it out in a few minutes.
