### ISSUE TITLE
Change audio from OpenAL to AVAudioEngine for Apple

### ISSUE THREAD

**Issue by paulocoutinhox** [axmolengine/axmol#1491]
**Is your feature request related to a problem? Please describe.**

Hi,

Xcode is warning about OpenAL deprecation (macOS, iOS and tvOS).

Example:

```
/Users/paulo/Developer/workspaces/cpp/axmol/core/audio/AudioPlayer.cpp:78:9: warning: 'alDeleteBuffers' is deprecated: first deprecated in macOS 10.15 - OpenAL is deprecated in favor of AVAudioEngine [-Wdeprecated-declarations]
        alDeleteBuffers(QUEUEBUFFER_NUM, _bufferIds);
```

<img width="691" alt="image" src="https://github.com/axmolengine/axmol/assets/395096/6ed87f40-7c3c-4cad-9666-be53116ba965">

**Describe the solution you'd like**

OpenAL was deprecated. Make axmol compatible with AVAudioEngine.

https://developer.apple.com/documentation/ios-ipados-release-notes/ios-13-release-notes#Deprecations

Thanks.

**Comment by halx99** [comment]
can switch to `AX_USE_ALSOFT=ON`

**Comment by paulocoutinhox** [comment]
I can use this inside my `CMakeLists.txt` using `set(AX_USE_ALSOFT ON)`? Or have another way to do this?

**Comment by rh101** [comment]
`set(AX_USE_ALSOFT ON CACHE BOOL "Use ALSOFT on apple" FORCE)` should work. Just remember to clear the `[build_folder]/CMakeCache.txt` and re-run the cmake command after you do this (via `axmol build ...` etc.).

**Comment by halx99** [comment]
see also readme
