### ISSUE TITLE
[UWP] uwp platform ttf font rendering problem

### ISSUE THREAD

**Issue by zhengy** [axmolengine/axmol#1497]
On uwp platform, ttf font looks thicker. When the font color is modified, the edges of the font will appear obviously jagged. What causes this? Is there any solution?
![0E5DF956-0F2D-40dc-883F-88E2346076E4](https://github.com/axmolengine/axmol/assets/3364091/8f085985-4c8b-49f4-b7ac-d3f6545a849d)

**Comment by halx99** [comment]
Please provide more detail information, sample reproducable project

**Comment by zhengy** [comment]
> Please provide more detail information, sample reproducable project

I apologize for any confusion. I created a new C++ project (Hello World project) and simply replaced the TTF font as well as modified the font color. When compiling and running the project separately for UWP and Win32, differences can be observed.

If I don't replace the default "Marker Felt.ttf" font and only modify the TTF font color, the result is as follows:

![13A7FA78-9717-4996-8262-89EFC7B3E74A](https://github.com/axmolengine/axmol/assets/3364091/eb609122-8ff3-47eb-94a1-3d2360fd7fad)

The only modification is add the code:
`label->setColor(Color3B(121, 89, 231));`

**Comment by halx99** [comment]
![image](https://github.com/axmolengine/axmol/assets/6977319/44ddcd28-ed73-4555-b215-060fda429dc0)

**Comment by rh101** [comment]
@zhengy Which version of Windows (and build number) are you running it on, and what monitor resolution?

**Comment by halx99** [comment]
> ![image](https://private-user-images.githubusercontent.com/6977319/289851668-44ddcd28-ed73-4555-b215-060fda429dc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzODI3OTQsIm5iZiI6MTcwMjM4MjQ5NCwicGF0aCI6Ii82OTc3MzE5LzI4OTg1MTY2OC00NGRkY2QyOC1lZDczLTQ1NTUtYjIxNS0wNjBmZGE0MjlkYzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTJUMTIwMTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQ0N2Y2ZmFlYmYwMWM2MjkzYzNiMTNkNTRkYjcyM2NkYTllODNkYzE4ZmI2MzQzZTAxY2ZlMDJjYjdlYjYxYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.V01HgY6GQA0Kj9tq6OL__YwT0s10BHrAgopMyhbJAiM)

The only reason cause uwp looks blur is:
 - win32 framesize controlled by GLView::createWithRect
 - winuwp framesize controlled by system, in my test, framesize is 1217x721 cause contentScaleFactor not 1.0

**Comment by zhengy** [comment]
> @zhengy Which version of Windows (and build number) are you running it on, and what monitor resolution?

Sorry for the late reply.  My Windows os system version is Windows 10 22H2 (Build 19045.3693), and the monitor resolution is 2560 * 1440 . 
Your test results appear to be normal. Did you make some modifications?
In my test environment, the issue occurs with any framesize and contentScaleFactor (1 or not).

**Comment by rh101** [comment]
> Sorry for the late reply. My Windows os system version is Windows 10 22H2 (Build 19045.3693), and the monitor resolution is 2560 * 1440 .

The reason I asked is because it seems that there are a lot of reports online related to bad UWP font rendering using certain resolution, which also seems to be impacted by the version of Windows used (not specific to Axmol).

**Comment by halx99** [comment]
> > @zhengy Which version of Windows (and build number) are you running it on, and what monitor resolution?
> 
> Sorry for the late reply. My Windows os system version is Windows 10 22H2 (Build 19045.3693), and the monitor resolution is 2560 * 1440 . Your test results appear to be normal. Did you make some modifications? In my test environment, the issue occurs with any framesize and contentScaleFactor (1 or not).

```cpp
ApplicationView::PreferredLaunchViewSize(winrt::Windows::Foundation::Size{1280, 720});
ApplicationView::PreferredLaunchWindowingMode(ApplicationViewWindowingMode::PreferredLaunchViewSize);
```

**Comment by zhengy** [comment]
> > Sorry for the late reply. My Windows os system version is Windows 10 22H2 (Build 19045.3693), and the monitor resolution is 2560 * 1440 .
> 
> The reason I asked is because it seems that there are a lot of reports online related to bad UWP font rendering using certain resolution, which also seems to be impacted by the version of Windows used (not specific to Axmol).

Yes, I tested both cocos2dx 3.17 and cocos2dx 4.0, and they have the same issue. May I ask what is your Windows version and screen resolution? I see your test results are normal.

**Comment by rh101** [comment]
> Yes, I tested both cocos2dx 3.17 and cocos2dx 4.0, and they have the same issue. May I ask what is your Windows version and screen resolution? I see your test results are normal.

I'm assuming you meant that question for @halx99

**Comment by halx99** [comment]
> > Yes, I tested both cocos2dx 3.17 and cocos2dx 4.0, and they have the same issue. May I ask what is your Windows version and screen resolution? I see your test results are normal.
> 
> I'm assuming you meant that question for @halx99

yes

**Comment by zhengy** [comment]
@halx99 @rh101   I'm very sorry I confused you .   
Is the issue related to the underlying rendering? In UWP, the underlying rendering uses DirectX, while in Win32, OpenGL is used. However, the antialiasing effect of FreeType on DirectX may be suboptimal.

**Comment by halx99** [comment]
> @halx99 @rh101 I'm very sorry I confused you . Is the issue related to the underlying rendering? In UWP, the underlying rendering uses DirectX, while in Win32, OpenGL is used. However, the antialiasing effect of FreeType on DirectX may be suboptimal.

Latest axmol both win32 & UWP use directx via google ANGLE render backend

**Comment by zhengy** [comment]
> > @halx99 @rh101 I'm very sorry I confused you . Is the issue related to the underlying rendering? In UWP, the underlying rendering uses DirectX, while in Win32, OpenGL is used. However, the antialiasing effect of FreeType on DirectX may be suboptimal.
> 
> Latest axmol both win32 & UWP use directx via google ANGLE render backend

Thank you for informing me of this news. So, this issue seems unrelated to whether DirectX or OpenGL is used.

@halx99  Why are your test results normal? Is it due to the system and resolution? Can you tell me your system version and screen resolution? I'd like to reproduce it.

I have added these two lines of code to set the resolution at startup, but the issue still persists.
`ApplicationView::PreferredLaunchViewSize(winrt::Windows::Foundation::Size{1280, 720});
ApplicationView::PreferredLaunchWindowingMode(ApplicationViewWindowingMode::PreferredLaunchViewSize);`

**Comment by halx99** [comment]
> > > @halx99 @rh101 I'm very sorry I confused you . Is the issue related to the underlying rendering? In UWP, the underlying rendering uses DirectX, while in Win32, OpenGL is used. However, the antialiasing effect of FreeType on DirectX may be suboptimal.
> > 
> > 
> > Latest axmol both win32 & UWP use directx via google ANGLE render backend
> 
> Thank you for informing me of this news. So, this issue seems unrelated to whether DirectX or OpenGL is used.
> 
> @halx99 Why are your test results normal? Is it due to the system and resolution? Can you tell me your system version and screen resolution? I'd like to reproduce it.
> 
> I have added these two lines of code to set the resolution at startup, but the issue still persists. `ApplicationView::PreferredLaunchViewSize(winrt::Windows::Foundation::Size{1280, 720}); ApplicationView::PreferredLaunchWindowingMode(ApplicationViewWindowingMode::PreferredLaunchViewSize);`

win1022h2 4k(3840x2560)

**Comment by zhengy** [comment]
@halx99  I am using another computer with the same system version and screen resolution as yours, but the issue still persists.

**Comment by halx99** [comment]
Try enable ttf SDF rendering: https://axmolengine.github.io/manual/latest/d3/d0e/classax_1_1_font_free_type.html#a5d00aecd9e3d6d3e1ed6408eb840648a

**Comment by zhengy** [comment]
Yes, I have tried it. When the ttf font is larger, enable sdf font will become more clearer, but when the font is smaller, the jagged feeling will still be obvious.
enable sdf has an effect, but the effect of ttf rendering is still different from that of the win32 platform (the font is thicker and has a sense of outline)

**Comment by zhengy** [comment]
> > @halx99 @rh101 I'm very sorry I confused you . Is the issue related to the underlying rendering? In UWP, the underlying rendering uses DirectX, while in Win32, OpenGL is used. However, the antialiasing effect of FreeType on DirectX may be suboptimal.
> 
> Latest axmol both win32 & UWP use directx via google ANGLE render backend

@halx99  Hello, I created a new HelloWorld project and noticed that the Win32 project doesn't use Google ANGLE. Does the Win32 project actually use DirectX?

**Comment by halx99** [comment]
The latest axmol change default gl bakcend to ANGLE(GLES), please update and recreate new helloworld to check
