### ISSUE TITLE
build cannot correct  handle '-' on the project name like:  axmol new -p org.axmol.hellocpp -d D:\dev\projects\ -l cpp --portrait My-Game

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#1498]
My-Game will be changed to: My_Game 
and error is raising:
MSBUILD : error MSB1009: Project file does not exist.

Same with "My-Game"
`axmol new -p org.axmol.hellocpp -d D:\dev\projects\ -l cpp --portrait "My-Game"`

Build output:

-- Enabled axmol extensions:JSONDefault;cocostudio;SDFGen;Inspector;ImGui;fairygui;DragonBones;spine;physics-nodes;particle3d;assets-manager;GUI;
-- No shader found in D:/dev/projects/My-Game/Source/shaders
-- Configuring done (30.1s)
-- Generating done (2.2s)
-- Build files have been written to: D:/dev/projects/My-Game/build_x64
build1k: BUILD_ALL_OPTIONS=--target My_Game --config Release --parallel, Count=5
MSBuild version 17.8.3+195e7f5a3 for .NET Framework
`MSBUILD : error MSB1009: Project file does not exist.`
Switch: My_Game.vcxproj
build1k: Build done

**Comment by aismann** [comment]
@halx99 
can you have a closer look agaain plz:

D:\__GIT\axmol>axmol new -p org.axmol.test -d D:\dev\projects\ -l cpp --portrait test-t
```
InvalidOperation: D:\__GIT\axmol\tools\console\axmol_new.ps1:31
Line |
  31 |  if ($pname.IndexOf('-') -ne -1) {
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
```
Creating project test-t, is_portrait=True ...
Create project test-t done.

**Comment by halx99** [comment]
fixed, and rebased
