### ISSUE TITLE
[iOS] terminating due to uncaught exception of type std::out_of_range: ibstream_view::consume out of range!

### ISSUE THREAD

**Issue by stephenhurry** [axmolengine/axmol#1506]
- axmol version: axmol-2.1.0-62e6542
- devices test on: iPhone 14 Pro (iOS 17.1.2)
- developing environments
   - Xcode version: 15.0.1
   - cmake version: 3.27.3
Steps to Reproduce:

1.  Build the iOS project through XCode and run it on my device, an error is caught: `libc++abi: terminating due to uncaught exception of type std::out_of_range: ibstream_view::consume out of range!`
2. Dropping a C++ exception breakpoint to trace the error:
![Screenshot 2023-12-12 at 15 29 04](https://github.com/axmolengine/axmol/assets/5404951/af954c71-f224-40a1-8971-de4959c54e68)
![Screenshot 2023-12-12 at 15 29 12](https://github.com/axmolengine/axmol/assets/5404951/4ea4dba3-d65e-499c-9c9e-04a0532bb26a)
![Screenshot 2023-12-12 at 15 29 27](https://github.com/axmolengine/axmol/assets/5404951/697d015e-83fe-48d1-a07d-d1e8b961c73d)
![Screenshot 2023-12-12 at 15 29 40](https://github.com/axmolengine/axmol/assets/5404951/5e79715b-5442-4ef6-8595-5a4da563c45a)
![Screenshot 2023-12-12 at 15 29 47](https://github.com/axmolengine/axmol/assets/5404951/66e8535c-dc96-4361-8502-08cd7fedc2d1)

**Comment by rh101** [comment]
Refer to #1482 

You need cmake 3.28 installed for MacOS and iOS builds.  The dev setup page needs to be updated to reflect this.

**Comment by halx99** [comment]
NOTE: If you follow latest `DevSetup.md` use command `axmol build -p ios -c` to generate xcode project, the command will auto setup required `cmake-3.28.0` in `$AX_ROOT/tools/external/cmake` and use it, shouldn't encounter this issue.
