### ISSUE TITLE
DrawNode 2.0: Add individual thickness for drawing primitives

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#1517]
Working on: `DrawNode 2.0`
- Add individual thickness for drawing primitives 

Add new Color4* type:
```
Color4F::INVISIBLE
Color4B::INVISIBLE
```
[DelinWorks](https://github.com/DelinWorks) commented [last week]
> maybe the name "TRANSPARENT" instead of "INVISIBLE" is clearer?

Sure but
![image](https://github.com/axmolengine/axmol/assets/8652787/bdbdea19-3b7c-4c33-9920-4796198be5af)
TRANSPARENT is used on wingdi.h:
```
wingdi.h -- GDI procedure declarations, constant definitions and macros

/* Background Modes */
#define TRANSPARENT         1
#define OPAQUE              2
#define BKMODE_LAST         2
```

**Comment by aismann** [comment]
Add new Color4* type:
```
Color4F::INVISIBLE
Color4B::INVISIBLE
```

**Comment by DelinWorks** [comment]
maybe the name "TRANSPARENT" instead of "INVISIBLE" is clearer?

**Comment by aismann** [comment]
> maybe the name "TRANSPARENT" instead of "INVISIBLE" is clearer?

TRANSPARENT is in used.
```
/* Background Modes */
#define TRANSPARENT         1
#define OPAQUE              2
#define BKMODE_LAST         2
```

**Comment by aismann** [comment]
some of drawPie also added 
![image](https://github.com/axmolengine/axmol/assets/8652787/45dcdd9c-6332-4640-9b77-89570a08c3cf)

**Comment by aismann** [comment]
Add line
![image](https://github.com/axmolengine/axmol/assets/8652787/59706675-18df-4b6b-8d83-d0b1bf9092bf)

Add fillcolor and bordercolor to Pie
![image](https://github.com/axmolengine/axmol/assets/8652787/d10c434b-c589-426e-8794-32a1e453cb2e)

**Comment by aismann** [comment]
Must stuff is done

![image](https://github.com/axmolengine/axmol/assets/8652787/069c4e58-9050-444e-b06a-20fb9220a19f)
![image](https://github.com/axmolengine/axmol/assets/8652787/5bc9efb0-a4e7-44f2-beef-f6d78d476ad6)

**Comment by aismann** [comment]
@halx99 
Please wait before you release the 2.1.0 => I want add this DrawNode 2.0: Thickness feature is some days.

**Comment by aismann** [comment]
![image](https://github.com/axmolengine/axmol/assets/8652787/47298dc8-ab42-46f0-926d-c5902f3c941a)

**Comment by aismann** [comment]
@halx99 
maybe 2.1.0 is to early
![image](https://github.com/axmolengine/axmol/assets/8652787/43a344c2-b5e7-46c7-aa49-75429fa70ba2)

**Comment by aismann** [comment]
Rewrite the DrawNode tests:
![image](https://github.com/axmolengine/axmol/assets/8652787/c3dd5395-c681-4dff-b17e-af2e1e18b308)

**Comment by aismann** [comment]
drawLine is working now:
![image](https://github.com/axmolengine/axmol/assets/8652787/cdbcb1ce-e8db-410b-8a38-fe2b99edb794)
![image](https://github.com/axmolengine/axmol/assets/8652787/2d80386f-97af-4653-ad0a-33e7f40ad31b)

**Comment by aismann** [comment]
PR is near ;)
Add some more (stress) tests before I submit this big PR

**Comment by aismann** [comment]
A movie shows more as a lot of pictures (deleted all entries which not really important or add it on the first entry)

https://github.com/axmolengine/axmol/assets/8652787/001a8e08-64c8-4c5a-ba2d-7723f43544e6

**Comment by aismann** [comment]
all in one now
