### ISSUE TITLE
support HarmonyOS System ?

### ISSUE THREAD

**Issue by 929496959** [axmolengine/axmol#1525]
support HarmonyOS System

**Comment by halx99** [comment]
I have no knowledge about it, and no resources, no plan to develop it. but
- Does it support GLES
- If some one interesting to implement HarmonyOS support, PRs are highly appreciated

**Comment by paulocoutinhox** [comment]
There is a PR for this here:
https://github.com/cocos2d/cocos2d-x/pull/20793
