### ISSUE TITLE
Add always to all "changed" source files "Copyright (c) 2019-present Axmol Engine contributors (see AUTHORS.md)." ...

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#1528]
... like on DrawNode.cpp:
Maybe '2019' is not always correct.
![image](https://github.com/axmolengine/axmol/assets/8652787/e1ef4499-0f58-4789-a263-fe0d77a51896)

**Comment by halx99** [comment]
the year is project launch time, not single file edit date

**Comment by aismann** [comment]
I think it can be closed, MIT license shows all too:
![image](https://github.com/axmolengine/axmol/assets/8652787/b4f00639-8640-4711-83ba-b69f45f925a7)
