### ISSUE TITLE
Is there any way for me to get the offline release package?

### ISSUE THREAD

**Issue by ChineseHotPot** [axmolengine/axmol#1529]
**Is your feature request related to a problem? Please describe.**
Is there any way for me to get the offline release package? It seems to me that I have a lot of difficulty getting dependencies through the build script, and it fails almost every time. 

**Describe the solution you'd like**
Maybe a distribution package like cocos2dx can help me.

**Comment by halx99** [comment]
You can just run `git clean -d -fx` in axmol root to cleanup cache stubs, rerun cmake generate will resolve your issue

**Comment by halx99** [comment]
A preview offline package available: [axmol-2.1.0-rc7.zip](https://github.com/axmolengine/axmol/releases/download/v2.1.0-rc7/axmol-2.1.0-rc7.zip)
