### ISSUE TITLE
Can not run tests

### ISSUE THREAD

**Issue by Roker2** [axmolengine/axmol#1553]
- axmol version: 2.1.0-rc7
- devices test on: Win10
- developing environments
   - Visual Studio: 
      - VS version: 2019 (16.11), 2022 (17.6+)
      - MSVC version: 1929, 1934, 19.35, 19.36, 19.37
      - Windows SDK version: 10.0.22621.0
Steps to Reproduce:
1. Open cpp-tests folder
2. Run `pwsh ../../build.ps1  -p win32`

It can not create `configs/config-example.plist`

**Comment by aismann** [comment]
@Roker2 
It builds using vs2022 ui?

**Comment by rh101** [comment]
> 1. Open cpp-tests folder
> 
>     2. Run `pwsh ../../build.ps1  -p win32`
> 
> 
> It can not create `configs/config-example.plist`

A lot of information missing from your post.  For example, which version of Visual Studio? What is the output of the console? Did you run setup? 

A few assumptions:

1 - You've already set up as per these instructions: https://github.com/axmolengine/axmol/blob/dev/docs/DevSetup.md#prerequisites
2 - You closed the terminal and opened up a new terminal after the setup is completed

In the cpp-tests folder, run this to build:
`axmol build -p win32`

Or, if you want to create the solution/project and build it within VS, then run this:
`axmol build -p win32 -c`
