### ISSUE TITLE
Missing extension options in CMakeOptions.md

### ISSUE THREAD

**Issue by iAndyHD3** [axmolengine/axmol#1556]
The following extension options are missing in [CMakeOptions.md](https://github.com/axmolengine/axmol/blob/dev/CMakeOptions.md)

- `AX_ENABLE_EXT_SDFGEN`
- `AX_ENABLE_EXT_JSONDEFAULT`
- `AX_ENABLE_EXT_LUA`

Unrelated discussion: I think that all extesnsions should be turned **off by default**, besides
- Imgui
- Inspector
- GUI

At the moment almost all extensions are turned **on** by default, which is bad, it forces everyone that doesn't need them to turn all of them off manually which is annoying. It is preferable that a user turns extensions on when they need them. Feedback?

**Comment by aismann** [comment]
Maybe differnt buikd flags be better?
- Default (use what is defined)
- All
- None
