### ISSUE TITLE
Disabling extensions causes linker errors using prebuilt

### ISSUE THREAD

**Issue by iAndyHD3** [axmolengine/axmol#1558]
- axmol version: dev branch latest commit
- devices test on: Windows 11 x64
- developing environments
   - Visual Studio: 
      - VS version: 2022 | 17.8
      - MSVC version: 19.38.33133.0
      - Windows SDK version: IDK
   - cmake version: 3.28.0
Steps to Reproduce:

1. Configure engine without tests and disabling extensions
```
cmake -B build_x64 -A x64 -DAX_BUILD_TESTS=OFF -DAX_ENABLE_EXT_ASSETMANAGER=OFF -DAX_ENABLE_EXT_PARTICLE3D=OFF -DAX_ENABLE_EXT_PHYSICS_NODE=OFF -DAX_ENABLE_EXT_SPINE=OFF -DAX_ENABLE_EXT_DRAGONBONES=OFF -DAX_ENABLE_EXT_COCOSTUDIO=OFF -DAX_ENABLE_EXT_FAIRYGUI=OFF -DAX_ENABLE_EXT_JSONDEFAULT=OFF -DAX_ENABLE_EXT_SDFGEN=OFF -DAX_ENABLE_EXT_LUA=OFF
```
2. Build engine
`cmake --build build_x64 --config RelWithDebInfo`
2. Create test project
`axmol new test new -p org.axmol.hellocpp -l cpp --portrait HelloCpp`
3. Configure project without extensions
```
cmake -B build_x64 -A x64 -DAX_PREBUILT_DIR=build_x64 -DAX_ENABLE_EXT_ASSETMANAGER=OFF -DAX_ENABLE_EXT_PARTICLE3D=OFF -DAX_ENABLE_EXT_PHYSICS_NODE=OFF -DAX_ENABLE_EXT_SPINE=OFF -DAX_ENABLE_EXT_DRAGONBONES=OFF -DAX_ENABLE_EXT_COCOSTUDIO=OFF -DAX_ENABLE_EXT_FAIRYGUI=OFF -DAX_ENABLE_EXT_JSONDEFAULT=OFF -DAX_ENABLE_EXT_SDFGEN=OFF -DAX_ENABLE_EXT_LUA=OFF
```
4. Build test project
`cmake --build build_x64 --config RelWithDebInfo`

I am getting the following: `LINK : fatal error LNK1104: cannot open file 'spine.lib'`. It seems like extensions are not being disabled correctly, after building spine extension in engine i get `LINK : fatal error LNK1104: cannot open file 'particle3d.lib'`

Can anyone reproduce?

**Comment by rh101** [comment]
Can reproduce this issue, but only when using the `AX_PREBUILT_DIR` option.
