### ISSUE TITLE
UI nodes documentation is missing

### ISSUE THREAD

**Issue by Nordsoft91** [axmolengine/axmol#1562]
On documentation page Modules -> UI Nodes is empty.
https://axmolengine.github.io/manual/latest/

<img width="250" alt="Снимок экрана 2023-12-31 в 18 05 34" src="https://github.com/axmolengine/axmol/assets/9308612/e911a913-ea13-4ecf-b92e-9889009ee5d5">

Documentation for ui nodes exists only in "classes" section

**Comment by aismann** [comment]
@halx99 
Can it be part (added) of the release of 2.1.0?

**Comment by halx99** [comment]
I have no idea yet

**Comment by aismann** [comment]
@halx99 
please add 'help wanted'
