### ISSUE TITLE
Extension DrawNodeEx ‐ a new kind of sprite class (*experimental phase*)

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#1567]
FIRST:
Because of possible side effects with `class DrawNode` the extension `DrawNodeEx` aka `DrawNode v2` is still in the experimental phase and may encounter bugs or stability or compatibility issues when used.

DrawNodeEx is not only a class for drawing primitives, it's more: 
- It's `DrawNode v2`
- It's a kind of sprite created from drawing primitives!

Features:
- `Individual line width`
```
    setDNLineWidth();
    getDNLineWidth();

    Default value: `1.0f`
```

- `Scale/Rotation/Position`
```
Scale:
    setDNScale()
    setDNScaleX()
    setDNScaleY()
Rotation:
    setDNRotation()
    getDNRotation()
    setDNCenter()
    getDNCenter()
Position:
    setDNPosition()
    getDNPosition()
```
- `general`
```
ensureDNValues()
restoreDNValues()
resetDNValues()
```
- Planed APIs:
```
enableDNTransform()
getDNSprite()
explodeDNSprite()
transformDNSprite()
morphDNSprite()
createAnimDNSprite()
```

- [x] Add initial `DrawNode v2` as extension `DrawNodeEx` to axmol as experimental 
- [x] `DrawNode` API compatible
- [x] Add individual line width for drawing primitives 
- [x] Scale drawing primitives without changing the individual line width.
- [x] Rotate drawing primitives around a customized center 
- Useful tests
     - [ ] funktional
     - [ ] performance/robustness
     - [ ] compare `DrawNode` vs `DrawNode v2`
- [ ] Code Cleanup
     - [ ] Remove/Add some comments
     - [ ] Reduce compiler warnings
- [ ] Documentation, Wiki
     - [ ] Info about AX_TRANSPARENT

New drawMethods:
- drawStar()
- drawSolidStar()

![image](https://github.com/axmolengine/axmol/assets/8652787/97e18c82-d1bd-4759-8a9f-9b75a867dcc0)

**Comment by halx99** [comment]
- suggestion: `DrawNodeExt` ==> `DrawNodeEx`
- question: move it to `extensions/DrawNodeEx` folder?

**Comment by aismann** [comment]
> * suggestion: `DrawNodeExt` ==> `DrawNodeEx`
> * question: move it to `extensions/DrawNodeEx` folder?

No problem. I will move and rename it
