### ISSUE TITLE
compiling error in linux

### ISSUE THREAD

**Issue by Joilnen** [axmolengine/axmol#1593]
- axmol version: 32b0b7a48b06a4c32638aa36f131994abc5b6224
- devices test on: x86
- developing environments
- cmake version: clang version 16.0.6
linux 
error output in attachment, am I missing something ?
[t.txt](https://github.com/axmolengine/axmol/files/13875143/t.txt)

**Comment by halx99** [comment]
32bit? 32bit linux not supported

**Comment by Joilnen** [comment]
sorry it is x86_64, error is next lasts commits

**Comment by Joilnen** [comment]
it is working fine with commit 36018ecca3564ceafa8c7d230084d57073bd1ed4

**Comment by halx99** [comment]
seems there is no significant changes between https://github.com/axmolengine/axmol/commit/36018ecca3564ceafa8c7d230084d57073bd1ed4 and https://github.com/axmolengine/axmol/commit/32b0b7a48b06a4c32638aa36f131994abc5b6224

**Comment by halx99** [comment]
Your error caused by deps package download fail, just try again: `axmol build -p linux -f`

**Comment by Joilnen** [comment]
ok that works, but there is a way this work with local packages too like before ?

**Comment by halx99** [comment]
https://github.com/axmolengine/axmol/releases/download/v2.1.0-6f8601b/axmol-2.1.0-6f8601b.zip offline package

**Comment by Joilnen** [comment]
I mean by last commit before this last one I could to compile with my operating system it could be like this too, and we have this option and we don't need to download everything we just have in SO

**Comment by halx99** [comment]
i can't reproduce on my local wsl machine

**Comment by Joilnen** [comment]
ok, so it changed this feature, do you know if there is some option to me generate apk with debug sign yet ?

**Comment by halx99** [comment]
pass options like this: https://github.com/axmolengine/axmol/blob/dev/build.ps1#L178

**Comment by Joilnen** [comment]
yes but it can't generate a debug default one, like before, I can't see that option ?

**Comment by halx99** [comment]
you are right, debug sign not supported yet.

refer: https://github.com/axmolengine/axmol/blob/dev/templates/cpp-template-default/proj.android/app/build.gradle#L54

**Comment by Joilnen** [comment]
thank you
