### ISSUE TITLE
I miss the "Content' Folder at least on cpp-test repository. Right?

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#1606]
- axmol version: latest

**Comment by halx99** [comment]
it will generate in cmake config step.

**Comment by aismann** [comment]
How can i add new images e.g. for cpp-tests?

**Comment by rh101** [comment]
> How can i add new images e.g. for cpp-tests?

Aren't they located in this repo: https://github.com/axmolengine/axmol-sample-assets

**Comment by halx99** [comment]
> > How can i add new images e.g. for cpp-tests?
> 
> Aren't they located in this repo: https://github.com/axmolengine/axmol-sample-assets

Yes, @aismann you need add to that repo

**Comment by aismann** [comment]
close it here
