### ISSUE TITLE
A 'transparent' Amol logo is missed (Anybody have time to add it?)

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#1625]
![image](https://github.com/axmolengine/axmol/assets/8652787/8ade6fab-12f2-474f-a90b-81fdd06143c8)

The old 'AXIS" logo:
![image](https://github.com/axmolengine/axmol/assets/8652787/3892bae6-713f-441a-8fbf-95b7a9835b31)

**Comment by rh101** [comment]
Where is it missing from? I don't recognize that background.

**Comment by halx99** [comment]
here is: https://github.com/axmolengine/axmol/blob/dev/docs/logo.png

**Comment by aismann** [comment]
> Where is it missing from? I don't recognize that background.

The (cpp) template has the 'HelloWorld.png' (axmol) logo , its not transparent.

**Comment by aismann** [comment]
Thanks. Closed
![image](https://github.com/axmolengine/axmol/assets/8652787/d2e9701d-0a97-473e-9505-fe7d7db21d9f)
