### ISSUE TITLE
Scissor state is not applied for `Renderer::clear()` command

### ISSUE THREAD

**Issue by smilediver** [axmolengine/axmol#1627]
Scissor state is not applied for the clear command generated by `Renderer::clear()`, so the command ends up using an old state.

Since the only place where scissor state is applied is `Renderer::beginRenderPass()` it means that the scissor state is applied only when something is being drawn on the screen. So if the last command disables scissor state (after it was enabled earlier in the frame), the disabled scissor state is not applied in the next frame when `Renderer::clear()` happens and the screen is not cleared. The state is applied only after something is drawn and it triggers `Renderer::beginRenderPass()` call.

To setup a repro scene run the following code in an empty scene. Also make sure that nothing else is rendering like ImGui, fps, etc.

```cpp
auto scene = ax::Director::getInstance()->getRunningScene();

// This should draw an almost invisible fullscreen red quad.
// But since background is not cleared, it's max red.
auto dn = ax::DrawNode::create();
dn->drawSolidRect({ 0, 0 }, { 2000, 2000 }, { 255, 0, 0, 40 });
scene->addChild(dn);

auto dn2 = ax::DrawNode::create();
dn2->drawSolidRect({ 0, 0 }, { 100, 100 }, { 0, 255, 0, 40 });
auto crn = ax::ClippingRectangleNode::create({ 0, 0, 50, 50 });
crn->addChild(dn2);
// Comment this out to see that the issue is gone if scissor state is not being manipulated
scene->addChild(crn);
```

- axmol version: latest dev branch
- devices test on: macOS+OpenGL

**Comment by rh101** [comment]
Would you be able to add screenshots of expected and actual output, just to better understand what the issue is?

**Comment by rh101** [comment]
Possible reason why from this [source](https://www.khronos.org/opengl/wiki/Scissor_Test_And_Framebuffer_Clearing):
"The OpenGL Specification states that glClear() only clears the scissor rectangle when the scissor test is enabled."

If I understand correctly, what you're trying to achieve would better be served by using stencil clipping.

For example:
```
auto scene = ax::Director::getInstance()->getRunningScene();

auto dn = ax::DrawNode::create();
dn->drawSolidRect({ 0, 0 }, { 2000, 2000 }, { 255, 0, 0, 40 });
scene->addChild(dn);

auto clipper = ax::ClippingNode::create();
clipper->setContentSize(ax::Size(50, 50));
clipper->setInverted(false);
scene->addChild(clipper);

auto stencil = DrawNode::create();
stencil->drawSolidRect(Vec2(0, 0), Vec2(50, 50), Color4F::MAGENTA);
clipper->setStencil(stencil);

auto dn2 = ax::DrawNode::create();
dn2->drawSolidRect({ 0, 0 }, { 100, 100 }, { 0, 255, 0, 40 });
clipper->addChild(dn2);
```

The output with stencil clipping:
![image](https://github.com/axmolengine/axmol/assets/8603230/d55e183f-3459-48cd-b873-b5a593d57507)

**Comment by smilediver** [comment]
> Would you be able to add screenshots of expected and actual output, just to better understand what the issue is?

Expected:

<img width="128" alt="Screenshot 2024-01-24 at 13 25 52" src="https://github.com/axmolengine/axmol/assets/1411067/4008fd69-ecb9-4435-8ade-ec62bc5c3e5d">

Actual:

<img width="128" alt="Screenshot 2024-01-24 at 13 24 57" src="https://github.com/axmolengine/axmol/assets/1411067/eba5a1e1-6930-4153-91e0-8d49dc0d254c">

> Possible reason why from this [source](https://www.khronos.org/opengl/wiki/Scissor_Test_And_Framebuffer_Clearing): "The OpenGL Specification states that glClear() only clears the scissor rectangle when the scissor test is enabled."

The actual issue is that `ClippingRectangleNode` enables and then disables scissor test, but the actual scissor test state is never disabled, because `glDisable(GL_SCISSOR_TEST);` is not being called when `Renderer::clear()` happens. The only place where `glDisable(GL_SCISSOR_TEST);` is called is in `Renderer::beginRenderPass()`, which is called only when something is rendered. Ie, add another `DrawNode` after the `ClippingRectangleNode` and the bug will disappear again.

Btw, I haven't tested Metal, but probably this bug manifests there too.

**Comment by rh101** [comment]
> The actual issue is that `ClippingRectangleNode` enables and then disables scissor test, but the actual scissor test state is never disabled, because `glDisable(GL_SCISSOR_TEST);` is not being called when `Renderer::clear()` happens. The only place where `glDisable(GL_SCISSOR_TEST);` is called is in `Renderer::beginRenderPass()`, which is called only when something is rendered. Ie, add another `DrawNode` after the `ClippingRectangleNode` and the bug will disappear again.

OK, I can see where the issue is now.

Given that we have a state cache, then it may be possible to add a single call to the `Renderer::clear()` method that should fix the issue, and won't needlessly call `glEnable/glDisable` for `GL_SCISSOR_TEST` if it's already in the correct state.  See the change below:

```
void Renderer::clear(ClearFlag flags, const Color4F& color, float depth, unsigned int stencil, float globalOrder)
{
    _clearFlag = flags;

    CallbackCommand* command = nextCallbackCommand();
    command->init(globalOrder);
    command->func = [this, flags, color, depth, stencil]() -> void {

        backend::RenderPassDescriptor descriptor;

        descriptor.flags.clear = flags;
        if (bitmask::any(flags, ClearFlag::COLOR))
        {
            _clearColor                = color;
            descriptor.clearColorValue = {color.r, color.g, color.b, color.a};
        }

        if (bitmask::any(flags, ClearFlag::DEPTH))
            descriptor.clearDepthValue = depth;

        if (bitmask::any(flags, ClearFlag::STENCIL))
            descriptor.clearStencilValue = stencil;

        _commandBuffer->setScissorRect(_scissorState.isEnabled, _scissorState.rect.x, _scissorState.rect.y,
                                   _scissorState.rect.width, _scissorState.rect.height);  // <<<=== add this line
        _commandBuffer->beginRenderPass(_currentRT, descriptor);
        _commandBuffer->endRenderPass();
    };
    addCommand(command);
}
```

@halx99 what is your opinion on this?

> Btw, I haven't tested Metal, but probably this bug manifests there too.

Best not to assume, so if you have the capability to test it, then please do so.

**Comment by halx99** [comment]
If the scissor state was changed, need invoke `_commandBuffer->setScissorRect`, right?

**Comment by rh101** [comment]
> If the scissor state was changed, need invoke `_commandBuffer->setScissorRect`, right?

The issue is this:
1. Program start
2. Clear screen with disabled scissor state (screen gets cleared correctly)
3. Draw a node with scissor state disabled.
4. Draw a node with scissor state enabled (eg. `ClippingRectangleNode`)
5. Finish render loop. 

Now repeat loop:
1. Clear screen with scissor state still enabled (due to step 4 above). Screen does not get cleared correctly.
2. Draw a node with scissor state disabled.
3. Draw a node with scissor state enabled (eg. `ClippingRectangleNode`)
4. Finish render loop, repeat etc. etc.

If nothing is rendered with a disabled scissor state prior to the `glClear`, then it will always use the enabled scissor state.

**Comment by rh101** [comment]
To avoid calling `glScissor` in certain situations where we just want to enable or disable the scissor state without also setting the scissor rectangle:

In `CommandBuffer`, we can add:
```
virtual void setScissorState(bool state) == 0;
```

In `CommandBufferGL` add the override:
```
void CommandBufferGL::setScissorState(bool state)
{
    if (state)
        __gl->enableScissor();
    else
        __gl->disableScissor();
}
```

In `OpenGLState` add:
```
void enableScissor()
{
    try_enable(GL_SCISSOR_TEST, _scissor);
}
```

Then in `void Renderer::clear(ClearFlag flags, const Color4F& color, float depth, unsigned int stencil, float globalOrder)` just call:

```
_commandBuffer->setScissorState(_scissorState.isEnabled);
_commandBuffer->beginRenderPass(_currentRT, descriptor);
_commandBuffer->endRenderPass();
```

**Comment by halx99** [comment]
> _commandBuffer->setScissorRect(_scissorState.isEnabled);
> _commandBuffer->beginRenderPass(_currentRT, descriptor);
> _commandBuffer->endRenderPass();

should be: `_commandBuffer->setScissorState(_scissorState.isEnabled)` ?

**Comment by halx99** [comment]
And @rh101 would like create a PR?

**Comment by rh101** [comment]
> > _commandBuffer->setScissorRect(_scissorState.isEnabled);
> > _commandBuffer->beginRenderPass(_currentRT, descriptor);
> > _commandBuffer->endRenderPass();
> 
> should be: `_commandBuffer->setScissorState(_scissorState.isEnabled)` ?

Sorry, yes. Typo.

**Comment by rh101** [comment]
> And @rh101 would like create a PR?

Sure, I'll create one now.  Are you happy with the suggested changes?

**Comment by smilediver** [comment]
I've tried `_commandBuffer->setScissorRect(_scissorState.isEnabled, _scissorState.rect.x, _scissorState.rect.y, _scissorState.rect.width, _scissorState.rect.height);` fix, and it does work, and looks like a reasonable fix. I'm not sure `_commandBuffer->setScissorState(_scissorState.isEnabled)` is enough, because maybe someone does want to enable scissors for the clear command, and in this case it would not update the rectangle.

But since I don't know the overall renderer's architecture, I can't say which fix is a correct one.

**Comment by halx99** [comment]
> > And @rh101 would like create a PR?
> 
> Sure, I'll create one now. Are you happy with the suggested changes?

Yeah, lgtm

**Comment by rh101** [comment]
> I've tried `_commandBuffer->setScissorRect(_scissorState.isEnabled, _scissorState.rect.x, _scissorState.rect.y, _scissorState.rect.width, _scissorState.rect.height);` fix, and it does work, and looks like a reasonable fix. I'm not sure `_commandBuffer->setScissorState(_scissorState.isEnabled)` is enough, because maybe someone does want to enable scissors for the clear command, and in this case it would not update the rectangle.

How would that work exactly? The issue with that is there is no history of the rectangle values. The `OpenGLState` doesn't cache the rectangle values, so there is no way to reset the rectangle to what it was prior to the first clear.

The only way this is possible is to add a new command that sets the scissor rectangle and sets scissor state to true, or use a `ClippingRectangleNode`, that occurs as the last command in the rendering loop just prior to the call to `Renderer::clear()`.

**Comment by rh101** [comment]
The metal renderer doesn't seem to have a state setting, and just sets the entire render target size as the scissor rectangle if the scissor state is `false`:

```
void CommandBufferMTL::setScissorRect(bool isEnabled, float x, float y, float width, float height)
{
    MTLScissorRect scissorRect;
    if (isEnabled)
    {
        y                  = _renderTargetHeight - height - y;
        int minX           = clamp((int)x, 0, (int)_renderTargetWidth);
        int minY           = clamp((int)y, 0, (int)_renderTargetHeight);
        int maxX           = clamp((int)(x + width), 0, (int)_renderTargetWidth);
        int maxY           = clamp((int)(y + height), 0, (int)_renderTargetHeight);
        scissorRect.x      = minX;
        scissorRect.y      = minY;
        scissorRect.width  = maxX - minX;
        scissorRect.height = maxY - minY;
        if (scissorRect.width == 0 || scissorRect.height == 0)
        {
            scissorRect.width  = 0;
            scissorRect.height = 0;
        }
    }
    else
    {
        scissorRect.x      = 0;
        scissorRect.y      = 0;
        scissorRect.width  = _renderTargetWidth;
        scissorRect.height = _renderTargetHeight;
    }
    [_mtlRenderEncoder setScissorRect:scissorRect];
}
```

So, we can't add a `setScissorState` for it, since it always needs the rectangle size to be passed in.

In this case, we should just fix this by adding this line to `Renderer::clear()`, and not bother with the other changes:

```
_commandBuffer->setScissorRect(_scissorState.isEnabled, _scissorState.rect.x, _scissorState.rect.y,
                                   _scissorState.rect.width, _scissorState.rect.height);
```

**Comment by smilediver** [comment]
> The only way this is possible is to add a new command that sets the scissor rectangle and sets scissor state to true

That's exactly what I had in mind. Maybe someone will want to add that command and clear just a part of the framebuffer on purpose for some reason. With `setScissorRect()` fix it would be possible to do that, with `setScissorState()` it would not. Since it seems that the `setScissorRect()` fix is the only one possible, then there's no issue here.
