### ISSUE TITLE
bindings-generator script run incorrectly

### ISSUE THREAD

**Issue by bintester** [axmolengine/axmol#1635]
It seems that bindings-Generator Script cannot correctly generate functions containing std:: int32_t parameters or return values.
It seems that the Node::getLocalZOrder and Node::setLocalZOrder not generated correctly.
when I change std::int32_t to int32_t, It can be exported.

- axmol version: 2.1
- devices test on: windows
- developing environments
   - NDK version: 23.2.8568313
   - Xcode version: 14.2
   - Visual Studio: 
      - VS version: 2022
   - cmake version: 3.28

**Comment by halx99** [comment]
would you like make a PR to fix this issue?
