### ISSUE TITLE
How to disable yasio ? I want to use other socket lib.

### ISSUE THREAD

**Issue by dotcomtnu** [axmolengine/axmol#1642]
Hi there,
I'm a indie dev, I love using C++ to dev game, thank you for bring Cocos2d-x back in a new generation.
I want to use other socket lib, but that lib conflict with some yasio pre defined macro, I can modify the source to temporary fix, but it is good to have option to switch off include yasio lib.
Please consider to add cmake option to disable yasio.
Thank you.

**Comment by halx99** [comment]
The axmol builtin `HttpClient` and `WebSocket` based on `yasio`, so not easy to disable it currently

**Comment by halx99** [comment]
BTW: which socket lib do you use?

**Comment by dotcomtnu** [comment]
> BTW: which socket lib do you use?

hi halx99
I'm using libhv for cross platform tcp/ip socket with ssl support and protobuf for data exchange between client/server.
Because I'm not using yasio so I will modify yasio pre defined macro to keep libhv as original,
Thank you.
