### ISSUE TITLE
Questions about branches and outdated links in README.md

### ISSUE THREAD

**Issue by grif-on** [axmolengine/axmol#1674]
1.
There are currently two branches : `2.1` and `dev` .
Why is `dev` not a default branch , and why is it behind `2.1` ? What is the point of `dev` at all ?

2.
What branch (or chechout ... or relative path) should be used for links in the documentation ?
Right now readme has all kinds of links :
- https://github.com/axmolengine/axmol/blob/dev/AUTHORS.md
Which are suffer from 1. problem .
- https://github.com/axmolengine/axmol/blob/d8d3137515a73e5c2395cae04d6b5ef6b1cc6777/CONTRIBUTING.md
Which points to specific version of the file (and thus needs to be updated every time the target file changes) .
- https://github.com/axmolengine/axmol/blob/master/LICENSE
Which points to a deleted branch (i.e. to page 404) , again 1. problem .
- extensions/README.md
Which seems the most universal , since it is guaranteed to point to a file on any current branch . But feels like a double-edged sword due to this branch polymorphism .

**Comment by halx99** [comment]
The 2.1 branch is for 2.1.x releases, but current no break changes 2.2.x features commits on dev branch, the dev & 2.1 should be identically

**Comment by danialias** [comment]
Sorry, my bad. I made a new PR correcting those links. I think this issue can be closed now.

**Comment by grif-on** [comment]
> The 2.1 branch is for 2.1.x releases, but current no break changes 2.2.x features commits on dev branch, the dev & 2.1 should be identically

Ok , get it .
Sorry , i was just been confused since `dev` has been behind for a long time .

**Comment by grif-on** [comment]
> Sorry, my bad. I made a new PR correcting those links. I think this issue can be closed now.

One more PR and yes , it should be closed .

**Comment by halx99** [comment]
Due to the dev & 2.1 is identically, I reset the default branch to `dev`
