### ISSUE TITLE
Can't start lua project on ios

### ISSUE THREAD

**Issue by halx99** [axmolengine/axmol#1712]
- axmol version:
- devices test on:
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2
   - Visual Studio: 
      - VS version: 2019 (16.11), 2022 (17.6+)
      - MSVC version: 1929, 1934, 19.35, 19.36, 19.37
      - Windows SDK version: 10.0.22621.0
   - cmake version: 
Steps to Reproduce:

1. axmol new HelloLua -l lua -d .
2. cd HelloLua
3. axmol build -p ios -a arm64 -c

**Comment by halx99** [comment]
@bintester sorry i do a mistake delete discuss about this issue

**Comment by rh101** [comment]
Deleting these lines from `lua-template-default\proj.ios_mac\ios\targets\ios\Info.plist` will fix the issue:

```
<key>NSMainNibFile</key>
<string>MainMenu</string>
<key>NSPrincipalClass</key>
<string>NSApplication</string>
```

They were introduced in this commit, I'm assuming by accident, because they shouldn't be there:
https://github.com/axmolengine/axmol/commit/7f309b75704cfbf1a047180b0bc732d0bcff836c

**Comment by halx99** [comment]
A better solution PR #1713 created
