### ISSUE TITLE
lua下DrawNode的drawPoly无法绘制多边形

### ISSUE THREAD

**Issue by qq461787436** [axmolengine/axmol#1714]
- axmol version:axmol-2.1.0
- devices test on:Mac OS M1
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2
   - Visual Studio: 
      - VS version: 2019 (16.11), 2022 (17.6+)
      - MSVC version: 1929, 1934, 19.35, 19.36, 19.37
      - Windows SDK version: 10.0.22621.0
   - cmake version: 
Steps to Reproduce:
无法绘制多边形，发现主要原因是drawPoly没有对应的Color4F接口，需要把luaval_to_color4f修改成luaval_to_color4b才能绘制
<img width="946" alt="image" src="https://github.com/axmolengine/axmol/assets/8909631/ecdefa81-c35a-475f-afaf-c9102cad46c1">

**Comment by halx99** [comment]
Fixed by https://github.com/axmolengine/axmol/commit/ce2c25c1e297e851652b20eede2dc80b2097e446
