### ISSUE TITLE
DebugDraw issue in 3D physics test

### ISSUE THREAD

**Issue by 10100010010001001010** [axmolengine/axmol#1726]
- axmol version: 2.1.1
- devices test on: PC, Windows 10
- Visual Studio 2022 (17.7+)
- cmake version: 3.27.4

![DebugDrawBug](https://github.com/axmolengine/axmol/assets/120378517/c1a4e72c-7327-4a0b-a5ce-603ea861c073)
![DebugDrawBug2](https://github.com/axmolengine/axmol/assets/120378517/a6d320e4-dd79-4605-a826-10f813381a49)
![DebugDrawBug3](https://github.com/axmolengine/axmol/assets/120378517/561fb487-0626-4244-b8c8-7971bc783a35)

**Comment by solan-solan** [comment]
Look's like `Physics3DDebugDrawer` should use V3F_C4F struct for `_buffer` vector instead of V3F_V4F since they have different sizes (28 vs 32), but PositionColor shader expect the first for _stride_, or may be some another way to resolve.
It is definitely alignment issue
