### ISSUE TITLE
[Windows] No log messages are being displayed in Visual Studio output window

### ISSUE THREAD

**Issue by rh101** [axmolengine/axmol#1737]
- axmol version: https://github.com/axmolengine/axmol/commit/2a40fcf50980727e1933a3f591738512c1570b8d
- devices test on: Windows 10
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2+
   - Visual Studio: 
      - VS version: 2022 (17.9+)
      - MSVC version: 19.39+
      - Windows SDK version: 10.0.22621.0+
   - cmake version: 
Steps to Reproduce:

1. Create a new project
2. Run project within Visual Studio

No log calls can be seen in the "Output" window

**Comment by rh101** [comment]
In commit https://github.com/axmolengine/axmol/commit/931ca91c71d506be436103f95c68e2cb1707a0ed, the call to `OutputDebugSstringW` was removed in the Win32 section of `Console.cpp`.

If it is to be re-added, it should be surrounded by pre-processor check for debug build only, since this should not be called in release builds:

```
#if defined(_WIN32) && (defined(_DEBUG) || !defined(_NDEBUG))
    // print to debugger output window
    std::wstring wbuf = ntcvt::from_chars(message);
    OutputDebugStringW(wbuf.c_str());
#endif
```

**Comment by halx99** [comment]
will re-add later, better is use winapi `IsDebuggerPresent` to check
