### ISSUE TITLE
One texture in two different slots

### ISSUE THREAD

**Issue by solan-solan** [axmolengine/axmol#1759]
- axmol version:
- devices test on:
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2+
   - Visual Studio: 
      - VS version: 2022 (17.9+)
      - MSVC version: 19.39+
      - Windows SDK version: 10.0.22621.0+
   - cmake version: 
Steps to Reproduce:

Direct me please if it is bad designe from my side. Really I can avoid this case (and will do), but it happend in my application.

One shader use's some texture with slot 7. The second shader use's the same texture with slot 8. The second shader is drawn right after the first according to the accident.
Then the texture will not be bind to the slot 8 for the second shader
![image](https://github.com/axmolengine/axmol/assets/73186496/004aa91c-f123-4762-aa51-37135e14985d)
![image](https://github.com/axmolengine/axmol/assets/73186496/de45538e-e69d-49ae-b198-17f244d453e3)

**Comment by DelinWorks** [comment]
go to the config and turn off gl state cache and see if that helps

**Comment by solan-solan** [comment]
With disabled _...GUARD..._ macros texture works as expected, since bind will pass, but this feature reduce gl calls

May be it's better to leave all as is to avoid overhead, since this case looks rare, and textures have locations in builting shaders

**Comment by halx99** [comment]
The cache should process active slot and texture binding, this should be the opengl state cache bug

**Comment by halx99** [comment]
@solan-solan please check latest commit: https://github.com/axmolengine/axmol/commit/2701bd10881df9ae7e8fb0b6d4417c39b93bd9ce

**Comment by solan-solan** [comment]
@halx99 I checked and it looks very good optimization, since there are no more extra texture bindings for objects which use multiple textures (ex. diffuse, then normal map) and drawn one by one. Thanks for this
