### ISSUE TITLE
axmol new -p org.axmol.hello-cpp -d <path>\ -l cpp hello-cpp changing packageName to: org.axmol.hello_cpp

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#1767]
org.axmol.hello-cpp will converted to 'org.axmol.hello_cpp' `<<<<<   is the '-' a problem anywhere?`

`axmol new -p org.axmol.hello-cpp -d path -l cpp hello-cpp`
Output:
axmol: **`Warning: package name was converted to 'org.axmol.hello_cpp'!`**
axmol: Creating project hello-cpp ...
axmol: ==> packageName: org.axmol.hello_cpp
axmol: ==> destinationPath: C:\Users\eismpesd\__eis\hello-cpp
axmol: ==> lang: cpp
axmol: ==> is_portrait: False
axmol: Create project hello-cpp done.

**Comment by halx99** [comment]
android package name require `_`, so converted. there is no problem, just a recommend don't use `-` for packageName
