### ISSUE TITLE
Compile error in 2.1.2

### ISSUE THREAD

**Issue by Diam2023** [axmolengine/axmol#1768]
- axmol version: axmol-2.1.2
- devices test on: windows11
- developing environments
   - Visual Studio: 
      - VS version: 2022 (17.9+)
      - MSVC version: 19.37.32825.0
      - Windows SDK version: 10.0.22621.0+
   - cmake version: 3.26.3
Steps to Reproduce:

1. cmake -S . -B build -G "Visual Studio 17 2022" -A win32
2. Open Visual Studio 
3. Start Local Windows Debugger

**Comment by Diam2023** [comment]
Error: axmol-2.1.2\thirdparty\astcenc\astcenc_vecmathlib_sse_4.h(1310,26): error C3861: '_mm_popcnt_u64': identifier not found

**Comment by aismann** [comment]
> Error: axmol-2.1.2\thirdparty\astcenc\astcenc_vecmathlib_sse_4.h(1310,26): error C3861: '_mm_popcnt_u64': identifier not found

can you try this one plz:
`cmake -S . -B build -G "Visual Studio 17 2022" -A x64`

**Comment by Diam2023** [comment]
Thank u :), It's worked for me.

**Comment by aismann** [comment]
> Thank u :), It's worked for me.

Small hint: 32 build will removed:
Mark as deprecated, and will be removed in next release axmol-2.2.0
32bit build

@halx99 
axmol version: axmol-2.1.2 has problem with 32 build:
cmake -S . -B build -G "Visual Studio 17 2022" -A win32

with:
Error: axmol-2.1.2\thirdparty\astcenc\astcenc_vecmathlib_sse_4.h(1310,26): error C3861: '_mm_popcnt_u64': identifier not **found**

**Comment by halx99** [comment]
but `axmol build -p win32 -a x86 -xb '--config,Debug'` workd

**Comment by halx99** [comment]
Maybe the typo mistake, you are use `win32` , but should be: `Win32`

**Comment by Diam2023** [comment]
> Maybe the typo mistake, you are use `win32` , but should be: `Win32`

You are right...
