### ISSUE TITLE
Xcode: Building for 'iOS-Simulator' but linking in object file built for iOS

### ISSUE THREAD

**Issue by dlheard17** [axmolengine/axmol#1770]
- axmol version: 2.1.3
- devices test on: Apple M1 Max
- developing environments
   - Xcode version: 15.2
   - cmake version: 3.29.0
Steps to Reproduce:
1.  Run axmol DevSetup steps
2.  Create new CPP project with `axmol new -p YOUR.UNIQUE.ID -d PROJECT_PATH -l cpp [--portrait] PROJECT_NAME`
3. Build for arm64 with: `axmol build -p ios -a arm64 -c`
4. Open the newly created Xcode project and attempt to build

This results in the error in the title. I have also tried an axmol build with x64 but that results in Xcode not showing any run destinations

**Comment by halx99** [comment]
you should select simulator destinations by yourself

**Comment by halx99** [comment]
The arm64 simulator not support yet.

**Comment by halx99** [comment]
Now latest commit support build arm64 simulator by `axmol build -p ios -a arm64 -sdk simulator`
