### ISSUE TITLE
Please update third-party library FlatBuffers

### ISSUE THREAD

**Issue by stephenhurry** [axmolengine/axmol#1774]
Dear maintainers,

I am an active user of the axmol project, and I’ve noticed that it currently relies on an outdated version of the FlatBuffers library (version 2.0.8). As a developer, I would like to take advantage of the new features introduced in newer version (latest  is v24.3.25), specifically the FlexBuffers feature.

Thank you for your attention to this matter. I appreciate your efforts in maintaining the project.

**Comment by halx99** [comment]
Complete by: https://github.com/axmolengine/axmol/commit/2ea963cb07739bebd9f94e916b4cc9ccc793ed63
