### ISSUE TITLE
Bluetooth audio device connected or disconnected on windows will crash.

### ISSUE THREAD

**Issue by Sevael** [axmolengine/axmol#1779]
- axmol version: 2.1.0
- devices test on: Windows 11/Windows 10
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2+
   - Visual Studio: 
      - VS version: 2022 (17.9+)
      - MSVC version: 19.39+
      - Windows SDK version: 10.0.22621.0+
   - cmake version: 3.22
Steps to Reproduce:

Whenever a Bluetooth audio device is connected or disconnected, the program will crash.
it crash on source file hrtf.cpp.
![Screenshot 2024-04-01 121828](https://github.com/axmolengine/axmol/assets/8056570/b7e8e0d6-b621-4491-bbd8-9110afb7674c)

Any idea ? Please help.

**Comment by halx99** [comment]
Maybe it's openal-soft issue?

**Comment by halx99** [comment]
I can't reproduce this issue

**Comment by Sevael** [comment]
i can reproduce the issue every time.
1. make sure the audioengine is using, like playing bgm or sound.
2. while playing sound, then connected or disconnect the bluetooth audio device.

**Comment by DelinWorks** [comment]
what device are you using?

**Comment by halx99** [comment]
> i can reproduce the issue every time.
> 
> 1. make sure the audioengine is using, like playing bgm or sound.
> 2. while playing sound, then connected or disconnect the bluetooth audio device.

I follow the steps, but still can't reproduce

**Comment by Sevael** [comment]
I will explain the steps in more detail. When the Bluetooth is disconnected or connected, it will not crash for a short period of time (but sometimes it will crash immediately), but after several operations in connected and disconnected, it will crash in different places. .
![Screenshot 2024-04-01 173108](https://github.com/axmolengine/axmol/assets/8056570/fe904bfb-d3c2-4f36-a092-e7f024e9cd76)


My device is an ordinary Bluetooth headset, and I originally thought it would only happen with Windows 11. Later, I tested it on Windows 10 and had the same problem.

It would be really weird if everyone couldn't reproduce it.

**Comment by halx99** [comment]
I test several  times, but chould'nt reproduce, my device is windows 11 23H2 , and Bluetooth device is `Xiaomi Buds 3Pro`

**Comment by Sevael** [comment]
I tried the latest version 2.1.2, and the crash problem was indeed fixed, so I replaced the OpenAL Library with the version I am currently using, and the problem was solved too.

Thanks for everyone's discussion, the Bluetooth problem has been solved.

**Comment by halx99** [comment]
strange, the v2.1.0, v2.1.2 using same openal version: 1.23.1-e714c8f (8659)
