### ISSUE TITLE
Android Studio: [CXX1300] CMake '3.29.0' was not found in SDK, PATH, or by cmake.dir property.

### ISSUE THREAD

**Issue by stephenhurry** [axmolengine/axmol#1783]
- axmol version: axmol-2.1.3-55275c0
- devices test on: Pixel 6a
- developing environments
   - NDK version: r23c
   - cmake version: 3.29.0
Steps to Reproduce:

1.  Build the project on Android Studio Iguana
2. Got the error message:
```
Execution failed for task ':project:configureCMakeDebug[arm64-v8a]'.
...
Caused by: com.android.builder.errors.EvalIssueException: [CXX1300] CMake '3.29.0' was not found in SDK, PATH, or by cmake.dir property.
```

**Comment by halx99** [comment]
Need more info

**Comment by halx99** [comment]
NOTE: You can't specify cmake version in your gradle other than `3.22.1` due the android sdk command line doesn't contains newer cmake version, instead you need install cmake by your self if you don't use `axmol build -p android`

**Comment by stephenhurry** [comment]
![Screenshot 2024-04-03 at 00 59 28](https://github.com/axmolengine/axmol/assets/5404951/ad2764f8-1867-48ac-b4cc-102bd0fbe4c9)

As shown in the logcat, Gradle is trying to build with cmake 3.29.0 (which is absent in the path)

P.S. I use `axmol build -p android -a arm64` to setup the android project

**Comment by halx99** [comment]
seems the path incorrect, my computer is: 

![image](https://github.com/axmolengine/axmol/assets/6977319/80741172-5ca4-4281-8c16-0ccb4f81b942)

**Comment by halx99** [comment]
The path xxx/sdk/cmake/3.28.1/bin/cmake actually 3.29.0, but folder is 3.28.1, i guess you copy 3.29.0 into it manually?
please check it by
```sh
cd xxx/sdk/cmake/3.28.1/bin
./cmake --version
```

**Comment by rh101** [comment]
Can confirm that it works as expected, as long as you have cmake 3.29 installed. Download that version, install it, and make sure it's in the environment path.  Then go into the `/Users/stephen/Library/Android/sdk/cmake` path and delete the `3.28.1` folder (which should be a symlink).

After that it will work fine, since Android Studio will detect cmake 3.29 from your environment path variable.

This is a screenshot from my app showing that it does work:
![image](https://github.com/axmolengine/axmol/assets/8603230/6d637dc6-9230-4087-9806-ca48bbe43861)

**Comment by stephenhurry** [comment]
> Can confirm that it works as expected, as long as you have cmake 3.29 installed. Download that version, install it, and and make sure it's in the environment path. Then go into the `/Users/stephen/Library/Android/sdk/cmake` path and delete the `3.28.1` folder (which should be a symlink).
> 
> After that it will work fine, since Android Studio will detect cmake 3.29 from your environment path variable.
> 
> This is a screenshot from my app showing that it does work: ![image](https://private-user-images.githubusercontent.com/8603230/318993058-6d637dc6-9230-4087-9806-ca48bbe43861.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMjE0MjIsIm5iZiI6MTcxMjEyMTEyMiwicGF0aCI6Ii84NjAzMjMwLzMxODk5MzA1OC02ZDYzN2RjNi05MjMwLTQwODctOTgwNi1jYTQ4YmJlNDM4NjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMDUxMjAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTVhODNlYzVkMWQ0NzEwNTI3NTM4ZmVjYzlhZmViZTY2NTc3OTVmNWRiZmRmMGIxMzEzMzBlZjQ1NTdlMTI4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FxCinvEema1nUvo74gHyoTr4uOXyfLidxy0ftHrb-Ro)

That works. Thanks a lot.
