### ISSUE TITLE
Add CMake option to remove Console from builds

### ISSUE THREAD

**Issue by smilediver** [axmolengine/axmol#1785]
Right now there's no way to remove `Console` class (remote command execution through TCP) from builds. Maybe a single option to remove all debug tools from the engine for final game releases would be sufficient.

**Comment by rh101** [comment]
> Maybe a single option to remove all debug tools from the engine for final game releases would be sufficient.

The console isn't solely a debugging tool, as release builds may still require output to console, but I understand your desire to have the ability to remove it.

Perhaps the best way is to just add the cmake option to disable the console, and have all the `AXLOG*` macros compile to nothing.

**Comment by smilediver** [comment]
Sorry for not being clear... I had in mind `Console` class, that opens a TCP port for remote commands, not the logging part.
