### ISSUE TITLE
Changing between Fullscreen and Windowed M1 Macbook, w/ Retina Display

### ISSUE THREAD

**Issue by TyelorD** [axmolengine/axmol#1787]
- axmol version: 2.1.2
- devices test on: MacBook Pro, 16in, 2021, M1 Mac
- developing environments
   - Xcode version: 15.2
   - cmake version: 3.29.0

Steps to Reproduce:
1. Create an empty Axmol project.
2. Add code that allows you to change the GLViewImpl from Fullscreen to Windowed and back (i.e. using the setWindowed and setFullscreen functions in the GLViewImpl class).
3. Add code that allows you to change the resolution between the different resolutions given to us by the GLViewImpl's Video Modes (i.e. using something like glfwGetVideoModes(_monitor, &count); to get all the supported resolutions for this monitor).
4. Default starting the game into fullscreen.
5. While running the game, change to Windowed Mode.
6. Change to the smallest allowed resolution (if not already on it).
7. Change back to Fullscreen Mode.
8. Observe the resolution of the game being far too large.

The game appears to be rendering at about twice as wide and twice as tall as it should be for the given resolution in fullscreen. I haven't tested with any other devices, but based on the symptoms and similar issues I've dealt with before using the old Cocos2d-x v3.17.2 I highly suspect that this issue has to do with Retina Displays with Macbooks.

Any help fixing this would be greatly appreciated, especially since this bug was a big reason why I convinced the boss to let me port our game to Axmol from Cocos2d-x v3.17.2 (which also had this bug, but only recently, since we fixed it once a year or two before the M1 macs were first released).

**Comment by halx99** [comment]
similar issue: https://github.com/axmolengine/axmol/issues/1691

**Comment by halx99** [comment]
could you provide reproduce demo?

**Comment by halx99** [comment]
Now should be fixed by latest commit
