### ISSUE TITLE
iOS-Xcode: the Info.plist, added capabilities and  scripts are deleted

### ISSUE THREAD

**Issue by asnagni** [axmolengine/axmol#1792]
We just migrated our 2  projects from Cocos2d-x 3.17.2 to Axmol and wanted to say that this team did a great job, thank you very much 👍.
After completing our migration, we noticed little issues that can become big issues if we don't address them quickly. We noticed that unlike with cocos2d-x, when we configure our info.plist, and add some capabilities to the apps (in the signing & capabilities tab), or add a script in the Build phases tab, they will disappear if for any reason you modify the CMAKe.list file.  

Would you know how to prevent that to happen either by putting  these values in the CMAKe.list file or prevent CMAKe to delete them. That will save us lot of time.

This issue will happen only if the CMAke file is modify or if you clear the build folder. This was not happening with cocos2d-x. 
Thank you in advance to anyone that could help on this issue.

Thank you,
Stay safe

- axmol version: 2..1.2
- devices test on: iPhone 11, 12, 13, 14
- developing environments
   - NDK version: r23c
   - Xcode version: 15.3
   - Visual Studio: N/A
      - VS version: N/A
      - MSVC version: 1N/A
      - Windows SDK version: N/A
   - cmake version:  3.29.0
Steps to Reproduce:

1. Add some info in your info.plist or capability in signing & capabilities tab
2. Modify your project CMAKe file and build or do a clear build folder an build
3. Check you info.plist file

**Comment by halx99** [comment]
you should add any props of info.plist by cmakelist via `set_xcode_property`

**Comment by asnagni** [comment]
Hi,
	Thank you for your reply, I do appreciate. We are not by any stretch CMAKE experts, would you have any example by any chance or do you have examples in any of the cpp Tests folder?

Thank you,
Stay safe

**Comment by halx99** [comment]
This maybe helpful: https://github.com/ChilliHugger/The-Lords-Of-Midnight/blob/AXMOL-port-3/main/midnight/CMakeLists.txt#L331C5-L331C23

**Comment by asnagni** [comment]
Thank you I do appreciate.

Stay safe
