### ISSUE TITLE
Build time too  long when we re-run the App

### ISSUE THREAD

**Issue by asnagni** [axmolengine/axmol#1794]
When we re-run our App without changing (no code change), everything will build again. That a long wasted. Maybe there is an option in Axmol to avoid this situation? No sure why this happening!

- axmol version: 2.1.2
- devices test on: iPhone 11, 12 , 13, 14
- developing environments
   - NDK version: N/A
   - Xcode version: N/A
   - Visual Studio: 
      - VS version: N/A
      - MSVC version: N/A
      - Windows SDK version: N/A
   - cmake version: 
Steps to Reproduce:

1. Create an Axmol project
2. Add your files
3. Build
4. Run your App.
5. Stop the App (via Xcode) 
6. Run the App from you device (Do not use Xcode)
7. Stop the App
8. Run your App again with Xcode
9. Everything will be rebuilt again

**Comment by asnagni** [comment]
Hi guys,
   I have a way to solve this issue. Now the build is  8x to 10x faster. Only what changed will be rebuild and no rebuild of the Axmol libraries. It is as fast as cocos2d-x and in some cases faster. 
    I do believe that this should should be included in the Axmol template build. That will help convert more people to the Axmol platform .
    
 How can I share the solution that I have?
 
 Thank you.

**Comment by asnagni** [comment]
Should I create one feature request?
Use this entry?

Feature request: Suggest an idea for this project

**Comment by danialias** [comment]
Have you tested this issue with other not-Axmol projects? It may be a Xcode problem.

I found a similar question in Reddit: https://www.reddit.com/r/iOSProgramming/s/63mUKEZ630

**Comment by asnagni** [comment]
This is the document that I have to significantly improve Axmol build time. That may help anyone that would like to improve their productivity.

[AxmolBuildTime.pdf](https://github.com/axmolengine/axmol/files/14939416/AxmolBuildTime.pdf)

**Comment by rh101** [comment]
I haven't managed to reproduce this specific issue at all, with either an existing project or a new project. The application is never rebuilt after step 8, it just simply runs on the device.

Using Xcode 15.0.1

**Comment by paulocoutinhox** [comment]
Hi,

I have the same problem on Xcode and not on Android.

I see this more when add cocoapods dependency that use ObjC bridge, like RevenueCat framework.
