### ISSUE TITLE
Cannot open source file "WebView.h": rebuild axmol with the latest version

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#1795]
- axmol version: latest 3a5498

get the error:
\axmol\core\ui\UIWebView\UIWebViewImpl-win32.cpp(51,14): error C1083: Cannot open include file: 'WebView.h': No such file or directory [\axmol\build_x64\engine\axmol\core\axmol.vcxproj]
  (compiling source file '../../../../core/ui/UIWebView/UIWebViewImpl-win32.cpp')

Cannot open include file: 'WebView.h': No such file or directory	axmol	\axmol\core\ui\UIWebView\UIWebViewImpl-win32.cpp	51

**Comment by halx99** [comment]
Can't reproduce

**Comment by aismann** [comment]
I use the latest again and its build now. sorry. Yesterday it didn't work
