### ISSUE TITLE
 Impossible to retrieve the text from  an UIEditbox

### ISSUE THREAD

**Issue by asnagni** [axmolengine/axmol#1796]
When you enter a text in an edibox or you try retrieve the text entered, and access error will generated. In case of trying to read/retrieve the Editbox text, it not be possible. We are running on iOS 17.4.1 and targeting a a minimum deployment iOS16

- axmol version: 2.1.2
- devices test on: iPhone 11, 12, 13, 14 (running on iOS 17.4.1)
- developing environments
   - NDK version: N/A
   - Xcode version: N/A
   - Visual Studio: 
      - VS version: N/A
      - MSVC version: N/A
      - Windows SDK version: N/A
   - cmake version: 
Steps to Reproduce:

1. Create a edit box
2. Try to enter a text
3. Try to read back the text you entered in the Editbox
4. You should see this error:  

-[RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:]  perform input operation requires a valid sessionID. inputModality = Keyboard, inputOperation = <null selector>, customInfoType = UIEmojiSearchOperations

**Comment by rh101** [comment]
Out of curiosity, is this happening on only on iOS 17? There seems to be many reports of this same issue in applications unrelated to Axmol, such as what you can see in the posts on the Apple forums [here](https://forums.developer.apple.com/forums/thread/731700).

**Comment by aismann** [comment]
@halx99 
Can you plz add a tag like IOS?
It seems to be an OS specific issue

**Comment by asnagni** [comment]
Probably but we need to investigate to make sure.

**Comment by asnagni** [comment]
Hi guys,
    My devices were automatically updated to iOS 17.4.1 and the issue disappeared . There the problem was on Apple end. This issue can be closed.
    
    Thank you

**Comment by asnagni** [comment]
The issue was on Apple end. Axmol code is fine 👍
