### ISSUE TITLE
MSAA support in metal (iOS/macOS)

### ISSUE THREAD

**Issue by Sevael** [axmolengine/axmol#1813]
Is there any plan to support MSAA in metal (iOS/macOS)?
MSAA support on Android/Windows is perfect but apple.

thank you.

**Comment by halx99** [comment]
This PR https://github.com/cocos2d/cocos2d-x/pull/20506 maybe helpful for you

**Comment by Sevael** [comment]
After research, it seems that it is difficult to transplant to AXMOL. Many structures are already different from AXMOL. Without understanding the metal, I had to give up.
😣

But I still hope that AXMOL can support MSAA in the future
