### ISSUE TITLE
PixelFormat::R8/A8 and GLES 2.0

### ISSUE THREAD

**Issue by smilediver** [axmolengine/axmol#1829]
GLES 2.0 for single channel textures used PixelFormat::A8, but in GLES 3.0 it was removed in favor of PixelFormat::R8. It seems like all other graphics APIs also use PixelFormat::R8. Our and Axmol code is full of hacks like these:

`auto pixelFormat = AX_GLES_PROFILE == 200 ? PixelFormat::A8 : PixelFormat::R8;`

Maybe it's worth to make `PixelFormat::A8 = PixelFormat::R8` and deal with the difference on the backend side when calling GLES api, so all code could use `PixelFormat::R8` everywhere? I'm not aware of unintended consequences, but at first sight it seems it would work. There could also be a macro to help on the shader code side, something like:

```
#ifdef GLES2
    #define R8_CHANNEL a
#else
    #define R8_CHANNEL r
#endif
```

What do you think?

**Comment by aismann** [comment]
@smilediver 
I found only 3 times like you means:

![image](https://github.com/axmolengine/axmol/assets/8652787/622c18a8-9a64-49c1-8760-0b0cea9223f2)

**Comment by aismann** [comment]
> Our ... code is full of hacks like these:
> 
> `auto pixelFormat = AX_GLES_PROFILE == 200 ? PixelFormat::A8 : PixelFormat::R8;`
> 

@smilediver 
May a "global pixelFormat" member is the solution on your code, defined only one times?
Can you close this issue?

**Comment by smilediver** [comment]
I would prefer for this to be handled on the engine side, since the engine's whole purpose is to abstract out such minor platform differences. But if people don't see this as something useful, then I'll close the issue.

**Comment by aismann** [comment]
@halx99 @rh101 
What are you meaning?

**Comment by halx99** [comment]
Can by done #1839 and GLES2 will emulate R8 RG8 via:

- R8: L8
- RG8: LA8
