### ISSUE TITLE
Broken RenderTexture

### ISSUE THREAD

**Issue by smilediver** [axmolengine/axmol#1838]
`RenderTexture` is broken on macOS Metal and GL. Haven't tested other platforms. Repro code:

```
    auto rt1 = RenderTexture::create(100, 100, PixelFormat::RGBA8);
    rt1->setAutoDraw(true);
    rt1->setClearColor(Color4F(1, 0, 0, 1));
    rt1->setClearFlags(ClearFlag::COLOR);
    rt1->setPosition(50, 50);

    auto rt2 = RenderTexture::create(100, 100, PixelFormat::RGBA8);
    rt2->setAutoDraw(true);
    rt2->setClearColor(Color4F(0, 1, 0, 1));
    rt2->setClearFlags(ClearFlag::COLOR);
    rt2->setPosition(150, 50);

    auto rt3 = RenderTexture::create(100, 100, PixelFormat::RGBA8);
    rt3->setAutoDraw(true);
    rt3->setClearColor(Color4F(0, 0, 1, 1));
    rt3->setClearFlags(ClearFlag::COLOR);
    rt3->setPosition(250, 50);

    scene->addChild(rt1);
    scene->addChild(rt2);
    scene->addChild(rt3);
```

Result:

<img width="330" alt="Screenshot 2024-04-19 at 20 06 42" src="https://github.com/axmolengine/axmol/assets/1411067/85b6add1-c7ee-4f7b-8369-80256e47763f">

There should be 3 quads: red, green and blue. It seems like only the 3rd RT is being drawn, but it's actually drawing a 2nd RT's texture.

Edit: the earliest Axmol version I could test was `2.1.0` and it was broken there too, so it's been broken for awhile.

**Comment by rh101** [comment]
`RenderTexture::create(int w, int h, backend::PixelFormat eFormat, PixelFormat uDepthStencilFormat, bool sharedRenderTarget)`

`sharedRenderTarget` defaults to true.

Please set it to false, and re-do your test, as that should resolve the issue you are seeing.

A quick test:
![image](https://github.com/axmolengine/axmol/assets/8603230/fbbb62e4-9881-407f-89da-63cf27734d83)

**Comment by smilediver** [comment]
It does work with shared render target off.

What is the purpose of the shared render target? How it's supposed to work?

**Comment by smilediver** [comment]
I've tested this on the Cocos version we're using (it's based on some older v3) and this code does work. Linking relevant issues and PR that probably broke this: #676 and #677.

I don't know how this shared render target is supposed to work, but maybe there's something missing in its code path. It's weird that each `RenderTexture` set their own textures on `_renderTarget` when it's created, but never when they render. Maybe that's the problem? The only place setting is here:
https://github.com/axmolengine/axmol/blob/f159250c4e5b3e7c79d1e3f8de48d6dfdb74ba8a/core/2d/RenderTexture.cpp#L222-L226
So maybe this needs to be done for each render?

**Comment by rh101** [comment]
> I've tested this on the Cocos version we're using (it's based on some older v3) and this code does work. Linking relevant issues and PR that probably broke this: #676 and #677.

#676 describes the same issue as what you posted, and #677 was the fix for the issue, which is to give us a way to not use the shared render target.

As for the shared render target, perhaps @halx99 can help in explaining its purpose.

**Comment by smilediver** [comment]
I was able to "fix" it by adding this in `void RenderTexture::onBegin()`:
```diff
     _oldRenderTarget = renderer->getRenderTarget();
+    if (isSharedRenderTarget())
+    {
+        _renderTarget->setColorAttachment(_texture2D ? _texture2D->getBackendTexture() : nullptr);
+        auto depthStencilTexture = _depthStencilTexture ? _depthStencilTexture->getBackendTexture() : nullptr;
+        _renderTarget->setDepthAttachment(depthStencilTexture);
+        _renderTarget->setStencilAttachment(depthStencilTexture);
+    }
     renderer->setRenderTarget(_renderTarget);
```
but this is probably not a right fix as I think `RenderTexture` inside another `RenderTexture` would not work again, or screw with other users of offscreen render target. Right now this shared render target feature would work only for the last `RenderTexture` created.

**Comment by rh101** [comment]
> but this is probably not a right fix as I think `RenderTexture` inside another `RenderTexture` would not work again, or screw with other users of offscreen render target. Right now this shared render target feature would work only for the last `RenderTexture` created.

Sorry, I'm not quite following. Are you referring to the code modification you posted?

Now. regardless of that, is there a specific issue you're having with the implementation in Axmol?  Does setting `sharedRenderTarget` when creating the `RenderTexture` not work for you? If it does not work, then please show an example of expected and actual renderer output, including code to replicate the issue.

**Comment by smilediver** [comment]
> Sorry, I'm not quite following. Are you referring to the code modification you posted?

Yes, I was referring to my diff "fix", that sets up shared render target just before rendering. It seems to fix my issue, but I'm not sure about this fix correctness.

> Now. regardless of that, is there a specific issue you're having with the implementation in Axmol? Does setting `sharedRenderTarget` when creating the `RenderTexture` not work for you? If it does not work, then please show an example of expected and actual renderer output, including code to replicate the issue.

The specific issue is that now render textures are broken by default, and the reason it's broken is shared render target. So in my mind there are two possibilities:
* Shared render target works ok - then I believe defaults are bad and `sharedRenderTarget` should default to false.
* Shared render target has a bug - then it needs to be fixed.

The main problem for shared render target is that it works only if you ever have a single `RenderTexture` at any given point. If you create another render texture, then it breaks the previous one, and so on. This is why I believe that probably shared render target feature is broken and should be fixed. But I would like someone more knowledgeable about this feature to chime in and comment if I'm right or wrong.

**Comment by halx99** [comment]
set useSharedRenderTarget to false may better
