### ISSUE TITLE
Cannot printLog on MacOS

### ISSUE THREAD

**Issue by jie-meng** [axmolengine/axmol#1866]
axmol version: latest verison of 'dev' branch
devices test on: MacBookPro M3 Max
developing environments
Xcode version: 15.3
cmake version: 3.29.2
Steps to Reproduce:

I tried this:
```lua
local TestScene = class("TestScene", cc.load("mvc").ViewBase)

function TestScene:onCreate()
    -- add background image
    display.newSprite("HelloWorld.png")
        :move(display.center)
        :addTo(self)

    -- add HelloWorld label
    cc.Label:createWithSystemFont("Test", "Arial", 40)
        :move(display.cx, display.cy + 200)
        :addTo(self)

    printLog("TestScene", "TestLog")
end

return TestScene
```

The "printLog" in functions.lua uses standard lua function "print", I don't know if it has bridged to MacOS app standard terminal output or not.

Nothing printed.

**Comment by jie-meng** [comment]
I tried to check the source code of axmol and found in LuaStack.h/LuaStack.cpp
```
#if defined(_AX_DEBUG) && _AX_DEBUG == 1
static LogLevel s_logLevel = LogLevel::Debug;
#else
static LogLevel s_logLevel = LogLevel::Info;
#endif

// ...

template <typename _FmtType, typename... _Types>
inline void printLogT(_FmtType&& fmt, LogItem& item, _Types&&... args)
{
    if (item.level() >= getLogLevel())
        outputLog(LogItem::vformat(std::forward<_FmtType>(fmt), item, std::forward<_Types>(args)...), "axmol");
}

#define AXLOG_WITH_LEVEL(level, fmtOrMsg, ...) \
    ax::printLogT(FMT_COMPILE("{}" fmtOrMsg "\n"), ax::preprocessLog(ax::LogItem{level}), ##__VA_ARGS__)

#define AXLOGT(fmtOrMsg, ...) AXLOG_WITH_LEVEL(ax::LogLevel::Trace, fmtOrMsg, ##__VA_ARGS__)
#define AXLOGD(fmtOrMsg, ...) AXLOG_WITH_LEVEL(ax::LogLevel::Debug, fmtOrMsg, ##__VA_ARGS__)
#define AXLOGI(fmtOrMsg, ...) AXLOG_WITH_LEVEL(ax::LogLevel::Info, fmtOrMsg, ##__VA_ARGS__)
#define AXLOGW(fmtOrMsg, ...) AXLOG_WITH_LEVEL(ax::LogLevel::Warn, fmtOrMsg, ##__VA_ARGS__)
#define AXLOGE(fmtOrMsg, ...) AXLOG_WITH_LEVEL(ax::LogLevel::Error, fmtOrMsg, ##__VA_ARGS__)
```
```
int lua_print(lua_State* L)
{
    std::string t;
    get_string_for_print(L, &t);
    AXLOGD("[LUA-print] {}", t);

    return 0;
}
```

It seems because of the default s_logLevel = LogLevel::Debug.
I don't know where to set the default log level, so I have to change the lua_print function implementation, make AXLOGD to AXLOGI would be OK. lua print can show in the console.

So what I still want to ask is what is the correct way to show lua log? Or is this a bug?

**Comment by halx99** [comment]
there is an api: release_print in lua, maybe in the future, export AXLOGD, AXLOGI, and other stubs to lua is better

**Comment by halx99** [comment]
> there is an api: release_print in lua, maybe in the future, export AXLOGD, AXLOGI, and other stubs to lua is better

done by: https://github.com/axmolengine/axmol/commit/1d8233d3ade9f821e6c6e2bf9bbe88cdbbc53c98
