### ISSUE TITLE
Content not found if app is launched from other dir than exe

### ISSUE THREAD

**Issue by smilediver** [axmolengine/axmol#1872]
I think current logic that initializes `_defaultResRootPath` for Windows and Linux is wrong. The problem is that if app is launched from other directory than where executable is, then it ignores game's content directory.

I think it should never search for data in the working directory. People or tools can launch the game from any location. I think `_defaultResRootPath` should be set to `<exe dir>/<AX_CONTENT_DIR>` if it exists, and otherwise it should be set to `<exe dir>`.

Current code for reference:

https://github.com/axmolengine/axmol/blob/d69fdfd0386248f564eed83eff495db9c84f9be8/core/platform/win32/FileUtils-win32.cpp#L98-L121

**Comment by halx99** [comment]
The design purpose is make workingDirectory in searchpath priority like generic normal apps

**Comment by smilediver** [comment]
Right now this feature actively ignores app's resources if launched from non exe dir. `_defaultResRootPath` purpose is to point to those resources, but it doesn't, so the app can't even call `FileUtils::getDefaultResourceRootPath()` to know where its resources are to add them back to the search paths. So current design doesn't work well for games. Also there's a consistency problem that `FileUtils::getDefaultResourceRootPath()` works for all the platforms except Linux and Windows.

So I propose alternative design:
* Set `_defaultResRootPath` to `<exe dir>/<AX_CONTENT_DIR>` if it exists, and otherwise set to `<exe dir>`.
* Add only `_defaultResRootPath` to the search paths.
* Add a new `FileUtils::getWorkingDirectory()` method for apps that want to add working directory to the search paths.

But even if the old design is left, I think at least the `_defaultResRootPath` should point to the right directory, so users can call `FileUtils::getDefaultResourceRootPath()` to resetup the search paths, and to keep the consistency with other platforms.
