### ISSUE TITLE
FairyGUI problems with text update

### ISSUE THREAD

**Issue by paulocoutinhox** [axmolengine/axmol#1874]
- axmol version: d6781284a5b2d9b21d3f98334a93a37cb49f55e3
- devices test on: all
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2+
   - Visual Studio: 
      - VS version: 2022 (17.9+)
      - MSVC version: 19.39+
      - Windows SDK version: 10.0.22621.0+
   - cmake version: 3.28.1
Steps to Reproduce:

1. Create a FairGUI GTextField element with any custom font and a simple text, example "test"
2. Change the text of GTextField in runtime with characters that is not in original text, example "text"

BEFORE CHANGE TEXT

<img width="371" alt="image" src="https://github.com/axmolengine/axmol/assets/395096/ca5d1aea-bb2c-456a-9d3a-8f710e416c10">

AFTER CHANGE TEXT

<img width="367" alt="image" src="https://github.com/axmolengine/axmol/assets/395096/d00c9031-b1e3-471e-a86d-4d96561aa21f">

The letter "x" that is not in design mode don't appear when new text have it.

Code:

```cpp
auto lbMessage = dynamic_cast<fairygui::GTextField *>(getContentPane()->getChild("lbMessage"));
lbMessage->setText("text");
```

What is wrong?

**Comment by rh101** [comment]
> What is wrong?

Have you followed it with a debugger to narrow down where the issue is occurring?

**Comment by paulocoutinhox** [comment]
Sure. Im try debug but i don't understand why it is cutting the chars that is not in the original text. I read all the source code, step by step with debug, but don't make sense to me.

**Comment by paulocoutinhox** [comment]
The steps is:

```cpp
void GBasicTextField::setTextFieldText()
{
    if (_templateVars != nullptr)
        _label->setText(parseTemplate(_text.c_str()));
    else
        _label->setText(_text);
}
```

That call FUILabel.cpp setText:

```cpp
void FUILabel::setText(std::string_view value)
{
    if (_fontSize < 0)
        applyTextFormat();

    setString(value);
}
```

That call core/2d/Label.cpp method setString:

```cpp
void Label::setString(std::string_view text)
{
    if (text.compare(_utf8Text))
    {
        _utf8Text     = text;
        _contentDirty = true;

        std::u32string utf32String;
        if (StringUtils::UTF8ToUTF32(_utf8Text, utf32String))
        {
            _utf32Text = utf32String;
        }
    }
}
```

And when i changed the text, it set the new string, "text" in my sample, without problems:

<img width="1185" alt="image" src="https://github.com/axmolengine/axmol/assets/395096/fb46615c-0cbf-4ee6-a72d-11c0407b2150">

Don't appear be nothing specific with FairyGUI, since it use Axmol Label.

**Comment by paulocoutinhox** [comment]
And the TTFConfig of Axmol label is this:

<img width="675" alt="image" src="https://github.com/axmolengine/axmol/assets/395096/5a7f3b0f-1734-4d07-a3d8-fd805e87f907">

The font is ok, it generate the first text of label without problems.

The problems happen when i change the label string/text.

**Comment by rh101** [comment]
> Don't appear be nothing specific with FairyGUI, since it use Axmol Label.

Have you tested the same font with an `ax::Label` to see if it has the same issue?  If it does not have an issue, then you should compare the behaviour of a standard `ax::Label` with that of the one used by FairyGUI.  Follow it in the debugger to the construction of the texture from the text itself, and you should be able to spot the difference.

**Comment by paulocoutinhox** [comment]
Hi, sure. Is this I'm doing, but without success. I'm debugging but do not discover the problem.

**Comment by paulocoutinhox** [comment]
Hi,

I think that there is wrong in my current project, because i create another sample with FairyGUI and axmol Label, and both works fine :(

https://github.com/paulocoutinhox/fairygui-bug

<img src="https://github.com/paulocoutinhox/fairygui-bug/raw/main/Extras/screenshots/ss1.jpg" width="280" />

<img src="https://github.com/axmolengine/axmol/assets/395096/56e52d3b-0fef-46e4-8791-c93a2cbc028b" width="280" />

**Comment by paulocoutinhox** [comment]
In test project it works on both devices.

In my real project it have problems on Android only:

![Screenshot_20240503_021149](https://github.com/axmolengine/axmol/assets/395096/80004ca0-65dc-4bf7-ab0b-f822866f0c17)

**Comment by paulocoutinhox** [comment]
I solve the problems settings correct resolution in design resolution and the text problems is related to threads, because i call JNI somethings and it don't render when come from JNI call (i dont know why, but i call on callback the method runInAxmolThread). Thanks.
