### ISSUE TITLE
Android:  protected void onNewIntent(Intent intent) is never called

### ISSUE THREAD

**Issue by asnagni** [axmolengine/axmol#1881]
Hi guys,
  Normally, the **onNewIntent()** method is supposed to be called on AppActivity instance to handle a new intent. Unfortunately at I'm not seeing that happening .

- axmol version: 2.1.2
- devices test on: Alcatel, Redmi 8 & 9
- developing environments
   - NDK version: 23.2.8568313
   - Xcode version:  N/A
   - Visual Studio: N/A 
      - VS version: N/A
      - MSVC version: N/A
      - Windows SDK version: N/A
   - cmake version:  3.29.0
Steps to Reproduce:

1. create a simple Axmol android project
2. Override the **protected void onNewIntent(Intent intent)**
3. Run and create a new internet wherever you may like
4. Your method **onNewIntent(Intent intent)** will never be called.

**Comment by asnagni** [comment]
It's working properperly. This was a mistake in the Manifest file.

**Comment by rh101** [comment]
> Normally, the **onNewIntent()** method is supposed to be called on AppActivity instance to handle a new intent. Unfortunately at I'm not seeing that happening .

The Android OS is responsible for calling `onNewIntent()`, so it's not something controlled by Axmol.  Furthermore, the call to `onNewIntent()` is only made depending on the configuration of the activity.  More info [here](https://developer.android.com/reference/android/app/Activity#onNewIntent(android.content.Intent)).

> It's working properperly. This was a mistake in the Manifest file.

Please close this issue if this isn't something related to Axmol.

**Comment by asnagni** [comment]
Hi rh101,
   The issue was resolved and the issue was on our side. We just forgot to close this opened bug.
   
   Thank you for your assistance, I do appreciate.
   
   Stay safe

**Comment by asnagni** [comment]
Thank you
