### ISSUE TITLE
Support for fixed sprite content size regardless of new texture content

### ISSUE THREAD

**Issue by rh101** [axmolengine/axmol#1896]
- axmol version: https://github.com/axmolengine/axmol/tree/1baf5cde3b0ccadf63fef045521723497d6f346f

This isn't really a bug, since the current implementation is correct.  Sprite frames can have different sizes, and a sprite should change size depending on the texture size of the frame.

It would be nice to have the ability to lock the sprite size so that it ignores the new frame texture size.  This would typically be used with stretch mode enabled.

Use `grossini.plist` sprite sheet and texture from cpp-tests.
```
auto spriteCache = SpriteFrameCache::getInstance();
spriteCache->addSpriteFramesWithFile("grossini.plist");

ax::Vector<ax::SpriteFrame*> animFrames;
for (int i = 1; i < 15; i++)
{
    auto frameName = fmt::format("grossini_dance_{:02}.png", i);
    animFrames.pushBack(spriteCache->getSpriteFrameByName(frameName));
}

auto* animation = ax::Animation::createWithSpriteFrames(animFrames, 1 / 25.f, -1);
auto* animationAction = ax::Animate::create(animation);
auto animatingSprite  = ax::Sprite::createWithSpriteFrame(animFrames.front());
animatingSprite->setPosition(visibleSize / 2);
animatingSprite->setStretchEnabled(true);
animatingSprite->setContentSize(ax::Vec2(200, 200));
animatingSprite->runAction(animationAction);
this->addChild(animatingSprite);
```

Expected output when animating (size of `200, 200` due to stretch factor):
![image](https://github.com/axmolengine/axmol/assets/8603230/afc5e3ea-efc2-440d-a549-53919e332619)

Actual output while animating:
![image](https://github.com/axmolengine/axmol/assets/8603230/ba1dad5e-78d3-417e-a5e1-bb16f9bd21d6)

**Comment by rh101** [comment]
Not sure about the best way to add this feature.  

Can add a new `FixedSizeAnimate` action is added that always sets the same content size after each new frame on a sprite, but that means calculations inside the `Sprite` will be done twice, once in the chain called from `setSpriteFrame` -> `setTextyureRect` etc., and then another by the extra `setContentSize`.  They all end up calling `updateStretchFactor();` and `updatePoly();`, so they'll be called twice for every frame.

Another option would be to add something to `Sprite` to indicate that the content size is fixed, and should not change on new textures/frames (as long as it's not a content size of `0, 0`).

**Comment by rh101** [comment]
With PR #1897 a simple call to ~~`sprite->setContentSizeDynamic(false);`~~ `sprite->setAutoSize(false);` would enable the functionality described above.

**Comment by halx99** [comment]
API: change to setAutoSize?

**Comment by rh101** [comment]
> API: change to setAutoSize?

Yes! That makes way more sense. Will update the PR.
