### ISSUE TITLE
Network requests failure rate is higher in yasio compared to java.net we use in cocos2dx

### ISSUE THREAD

**Issue by battulasaivinesh** [axmolengine/axmol#1931]
- axmol version: axmol-2.1.2
- devices test on: Produciton (Accross a vast set of devices)
- developing environments
   - NDK version: r24c
   - Xcode version: 14.2+
   - cmake version:  3.28.1

After monitoring HTTP calls from our app, we observed that the failure rate of HTTP calls is double in axmol compared to cocos2dx 3.17. Here is the list of requests with different internal response codes - 

<img width="442" alt="Screenshot 2024-05-26 at 6 34 39 PM" src="https://github.com/axmolengine/axmol/assets/17727130/5e96c0b3-ad34-4faf-993c-888996c954f4">

##
Error rate added comes up to 6% of total requests, where as before in cocos 2dx 3.17 it used to be on 3% of total requests. The first one is considered as success.

Here is a sample code on how we are doing HTTP calls from our app - 

```
network::HttpRequest* request = new network::HttpRequest();
request->setUrl(url);
request->setRequestType(network::HttpRequest::Type::POST);
request->setResponseCallback(
    [](network::HttpClient* client, network::HttpResponse* response) { callback() });
std::string userGetStr = JsonController::getJsonStringFromValueMap(payload);
request->setRequestData(userGetStr.c_str(), userGetStr.length());
network::HttpClient::getInstance()->send(request);
CC_SAFE_RELEASE(request);
```

**Comment by smilediver** [comment]
Maybe this is related to #2067. We had an issue where Axmol would flood the server with requests and it would start refusing connections.
