### ISSUE TITLE
HSL Video - Assertion failed: (_videoRotation % 180 == 0 ? YASIO_SZ_ALIGN(videoDim.x, 32)

### ISSUE THREAD

**Issue by thienphuoc** [axmolengine/axmol#1984]
- axmol version:2.1.3
- devices test on:Apple M2/ IOS 17.4.1
- developing environments

   - Xcode version: 15.3
   - cmake version: 3.28.1
Steps to Reproduce:

S1. Play this video 
    auto videoPlayer = ax::ui::VideoPlayer::create();
    videoPlayer->setPosition(winSize / 2);
    videoPlayer->setAnchorPoint(Vec2::ANCHOR_MIDDLE);
    videoPlayer->setContentSize(0.25f*Size({1920,1080}));
    videoPlayer->setUserInputEnabled(true);
    videoPlayer->setKeepAspectRatioEnabled(true);
    videoPlayer->setURL("https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_adv_example_hevc/master.m3u8?58331");
    videoPlayer->play();
    this->addChild(videoPlayer);
    
S2.

https://github.com/axmolengine/axmol/assets/17909394/5067ca79-e72f-4c12-b193-677bd54ae699

Data : 

YWidth: 1920
YHeight: 1080
UVWidth: 960
UVHeight: 540
YPitch: 1920
UVPitch: 1920
YDataLen: 2073600
UVDataLen: 1036800
videoDim.x: 960
videoDim.y: 540
Expected Data Length (aligned): 777600
Assertion failed: YDataLen + UVDataLen does not match expected data length. Expected: 777600, Actual: 3110400

**Comment by halx99** [comment]
seems caused by the  video dim not match
