### ISSUE TITLE
Cannot Capture a ScrollView: Issue with RenderTexture?

### ISSUE THREAD

**Issue by asnagni** [axmolengine/axmol#2002]
Hi guys,
	I created a method/function to help capture a ScrollView But when I try to capture a a ScrollView using the method/function I get an empty png image. I’m not sure if there is an issue with the Axmol RenderTexture or if I’m doing something wrong. Some help will be appreciated.
	Perhaps there is already a method in Axmol to help do that? If yes please let me know so I don’t reinvent the wheel.
        

**This is the function I'm using to capture a a ScrollView** 

    void CModalLayerFeedbackRequestStats::CaptureScrollView(ui::ScrollView* scrollView, const std::string& filename)
    {
        // Get the size of the entire content of the ScrollView
        Size contentSize = scrollView->getInnerContainerSize();

        // Create a RenderTexture
        RenderTexture* renderTexture = RenderTexture::create(contentSize.width, contentSize.height);

        // Ensure the renderTexture is not released prematurely
        renderTexture->retain();

        // Save the current position and anchor point of the scroll view
        Vec2 originalPosition = scrollView->getInnerContainerPosition();
        Vec2 originalAnchor = scrollView->getAnchorPoint();

        // Position the ScrollView at the bottom left
        scrollView->setInnerContainerPosition(Vec2::ZERO);
        scrollView->setAnchorPoint(Vec2::ZERO);

        // Begin rendering to the RenderTexture
        renderTexture->begin();

        // Get the renderer
        Renderer* renderer = Director::getInstance()->getRenderer();

        // Use the correct visit signature to render the scroll view
        scrollView->visit(renderer, Mat4::IDENTITY, 0);

        // End rendering
        renderTexture->end();
        Director::getInstance()->getRenderer()->render();

        // Restore the original position and anchor point of the ScrollView
        scrollView->setInnerContainerPosition(originalPosition);
        scrollView->setAnchorPoint(originalAnchor);

        // Save the rendered texture to an image file
        renderTexture->saveToFile(filename, Image::Format::PNG, true, [renderTexture](RenderTexture* rt, std::string_view path) {
            // Release the renderTexture to balance the retain call
            renderTexture->release();
        });
    }

Thank you,
Stay safe

- axmol version: development branch
- devices test on: iOS X, 11, 14 & iPad 11' pro
- developing environments
   - NDK version: N/A
   - Xcode version: 15.4
   - Visual Studio: 
      - VS version: N/A
      - MSVC version: N/A
      - Windows SDK version: N/A
   - cmake version: 3.29.0
Steps to Reproduce:

1. Create a ScrollView and add few components in it (images, sprites, etc)
2. Call "CaptureScrollView" by passing the ScrollView and the name of png file (not the full path just the name of the image you would like to have)

**Comment by rh101** [comment]
I think that's a known issue, which is from Cocos2d-x.  You may be able to work around it if you do this:
```
scheduleOnce([](float)
{
// your render texture code
}, 0.f, "capture_sv");
```

or even:

```
scheduleOnce([this, scrollView, fileName](float) 
{ 
    CaptureScrollView(scrollView, fileName); 
}, 0.f, "capture_sv");
```

Is this a issue on all platforms, or just a specific platform (like iOS)?

Also, are you by any chance calling the `CaptureScrollView` from inside an event handler (like a touch/click handler etc.)?

**Comment by rh101** [comment]
This issue and #2001 are exactly the same.

**Comment by asnagni** [comment]
Hi rh101,
   Thank you for your reply, I do appreciate. 
 1) I will apply the adjustment that you are suggesting and let you know the outcome 👍. 
 2) I will let you know if this suggestion addresses issue #2001 also
 
 3) We do not develop on all platforms but I can tell you that the issue is on iOS & Android. Not sure about the other platforms.
 4) Yes the the call to "CaptureScrollView" is triggered by an event handler. In this case by a button click.
 
 
Thank you

**Comment by rh101** [comment]
> 4\. Yes the the call to "CaptureScrollView" is triggered by an event handler. In this case by a button click.

Then that may be the exact same issue that has always been in Cocos2d-x, which is when you attempt to draw to a `RenderTexture` within an event handler (button handler etc.).  Wrapping the code in a `scheduleOnce` is a work around to this strange issue (which is how I handle it in my projects too).

**Comment by asnagni** [comment]
Hey rh101,
   That was exactly the problem. Thank you for the pointer/suggestion. 
   
   It works perfectly by adding the scheduleOnce solution :
   
 scheduleOnce([](float)
{
// your render texture code
}, 0.f, "capture_sv");


   **This is the final code version. That could help anyone that may be facing the same problem:**
   
     void CaptureScrollView(ui::ScrollView* scrollView, const std::string& filename)
    {
        scheduleOnce([=](float)
        {
            // Get the size of the entire content of the ScrollView
            auto pInternalNode = scrollView->getInnerContainer();
            Size contentSize   = pInternalNode->getContentSize();

            // Create a RenderTexture with valid depth and stencil formats
            RenderTexture* renderTexture = RenderTexture::create(contentSize.width, contentSize.height, backend::PixelFormat::RGBA8, backend::PixelFormat::D24S8);

            // Ensure the renderTexture is not released prematurely
            renderTexture->retain();

            // Save the current position and anchor point of the scroll view
            Vec2 originalPosition = scrollView->getInnerContainerPosition();
            Vec2 originalAnchor = scrollView->getAnchorPoint();

            // Position the ScrollView at the bottom left
            scrollView->setInnerContainerPosition(Vec2::ZERO);
            scrollView->setAnchorPoint(Vec2::ZERO);

            // Begin rendering to the RenderTexture
            renderTexture->begin();

            // Get the renderer
            Renderer* renderer = Director::getInstance()->getRenderer();

            // Use the correct visit signature to render the scroll view
            ((Node*)pInternalNode)->visit();
            
            // End rendering
            renderTexture->end();
            Director::getInstance()->getRenderer()->render();

            // Restore the original position and anchor point of the ScrollView
            scrollView->setInnerContainerPosition(originalPosition);
            scrollView->setAnchorPoint(originalAnchor);

            // Save the rendered texture to an image file
            renderTexture->saveToFile(filename, Image::Format::PNG, true, [renderTexture](RenderTexture* rt, std::string_view path) {
                // Release the renderTexture to balance the retain call
                renderTexture->release();
            });
            
        }, 0.f, "capture_sv");
    }



Thank you

**Comment by asnagni** [comment]
Issue solved. Thank you rh101
