### ISSUE TITLE
Downloader fails if filename with tmp extension already exists

### ISSUE THREAD

**Issue by rh101** [axmolengine/axmol#2004]
- axmol version: axmol-2.1.4-d1ca753
- devices test on: Windows 10/Android/iOS devices
- developing environments
   - NDK version: r26
   - Xcode version: 14.2+
   - Visual Studio: 
      - VS version: 2022 (17.9+)
      - MSVC version: 19.39+
      - Windows SDK version: 10.0.22621.0+
   - cmake version: 
Steps to Reproduce:

There seems to be a scenario where a downloaded file exists along with the digest file, but also a tmp file exists.  If these files are all present, the downloader fails with this:

```
23:54:14:849	E/[2024-06-26 23:54:14.739][TID:9308]DownloadGame task failed : https://[address]/data.bin, identifier(BINFILE) error code(-3), internal error code(22) desc(HTTP response code said error)
```
For example, if these files all exist prior to starting a download, the error will occur:
![image](https://github.com/axmolengine/axmol/assets/8603230/bde5f127-e510-441e-adb7-0db889d91cdc)

This issue only started occurring after commit b6b6a15284111d75a0384c6a2295e05724785320, but I'm not entirely sure if it's just a coincidence.

If the `*.tmp` file is deleted, then the download works without issues.

**Comment by halx99** [comment]
I can't reproduce

**Comment by rh101** [comment]
Closing since this is a server-side issue.
