### ISSUE TITLE
Support removal of debug logging calls from builds

### ISSUE THREAD

**Issue by rh101** [axmolengine/axmol#2005]
At the moment there is no way to strip out all `AXLOGD` and `AXLOGV` calls from the builds, which is something that is supported by the `AXLOG` call (yet it doesn't use `fmt` for formatting).  These calls may contain output that should not be part of a release, whether it's sensitive information or things that would never make sense to have in release builds.

Would it make sense to support something such as the following?

```
#if AX_STRIP_DEBUG_LOGGING
#    define AXLOGV(...) \
        do              \
        {               \
        } while (0)
#    define AXLOGD(...) \
        do              \
        {               \
        } while (0)
#else
#    define AXLOGV(fmtOrMsg, ...) AXLOG_WITH_LEVEL(ax::LogLevel::Verbose, fmtOrMsg, ##__VA_ARGS__)
#    define AXLOGD(fmtOrMsg, ...) AXLOG_WITH_LEVEL(ax::LogLevel::Debug, fmtOrMsg, ##__VA_ARGS__)
#endif
```

By default, `AX_STRIP_DEBUG_LOGGING` would be false, so debug logging would be compiled in, but at least it would give the developer the option to completely strip out any code related to debug and verbose logging calls from a build.

**Comment by smilediver** [comment]
I think logging should be removed in release builds by default with an optional opt-in. One way would be to add `AX_USE_LOGGING` CMake option and something like:

```cpp
#if !defined(AX_USE_LOGGING)
    #if _AX_DEBUG > 0
        #define AX_USE_LOGGING 1
    #endif
#endif
```

Ignoring the default values I recommend using enabling logic like `AX_USE_LOGGING` instead of the disabling like `AX_STRIP_DEBUG_LOGGING` to avoid double negatives.

Btw, it's possible to workaround this by setting custom null logger using `setLogOutput()`

**Comment by rh101** [comment]
> Btw, it's possible to workaround this by setting custom null logger using `setLogOutput()`

That won't work in this case, since we still need output from `AXLOGI/AXOGW/AXLOGE` in release builds (depending on the output level set), and I don't want the debug logging calls to remain in the output executable.

I'll sort out a PR for this in the next few days.

**Comment by smilediver** [comment]
Ah, I missed that you're talking specifically about debug and verbose levels only...

Btw, just found that there are more of these:

```cpp
#    define AXLOG(format, ...) ax::print(format, ##__VA_ARGS__)
#    define AXLOGERROR(format, ...) ax::print(format, ##__VA_ARGS__)
#    define AXLOGINFO(format, ...) ax::print(format, ##__VA_ARGS__)
#    define AXLOGWARN(...) __AXLOGWITHFUNCTION(__VA_ARGS__)
```

Is there a reason why they don't use `AXLOG_WITH_LEVEL()`? And now they are inconsistent with `AXLOGX()` macros in respect of what gets enabled for debug/release builds.

**Comment by rh101** [comment]
> Is there a reason why they don't use `AXLOG_WITH_LEVEL()`? And now they are inconsistent with `AXLOGX()` macros in respect of what gets enabled for debug/release builds.

I don't know why they were left in there as they are, but perhaps @halx99 can provide an answer to that question.

**Comment by halx99** [comment]
> ```c++
> #    define AXLOG(format, ...) ax::print(format, ##__VA_ARGS__)
> #    define AXLOGERROR(format, ...) ax::print(format, ##__VA_ARGS__)
> #    define AXLOGINFO(format, ...) ax::print(format, ##__VA_ARGS__)
> #    define AXLOGWARN(...) __AXLOGWITHFUNCTION(__VA_ARGS__)
> ```

they are present only for compatibility purpose, and DEPRECATED.

**Comment by halx99** [comment]
> > ```c++
> > #    define AXLOG(format, ...) ax::print(format, ##__VA_ARGS__)
> > #    define AXLOGERROR(format, ...) ax::print(format, ##__VA_ARGS__)
> > #    define AXLOGINFO(format, ...) ax::print(format, ##__VA_ARGS__)
> > #    define AXLOGWARN(...) __AXLOGWITHFUNCTION(__VA_ARGS__)
> > ```
> 
> they are present only for compatibility purpose, and DEPRECATED.

relative PR: https://github.com/axmolengine/axmol/pull/2017
