### ISSUE TITLE
zlib download path.

### ISSUE THREAD

**Issue by xMonody** [axmolengine/axmol#2013]
- axmol version: 2.1.3
- devices test on:
   - Visual Studio: 
      - VS version: 2022 (17.9+)
      - MSVC version: 19.39+
      - Windows SDK version: 10.0.22621.0+
   - cmake version: 3.28.1

It looks like there's an extra semicolon in the zlib download path.
![image](https://github.com/axmolengine/axmol/assets/76483540/85f621db-2ff2-485f-9f43-eced37594168)

**Comment by halx99** [comment]
I can't reproduce:
![image](https://github.com/axmolengine/axmol/assets/6977319/472bf6f5-6418-4b8f-b6f6-07fe440ee154)

**Comment by xMonody** [comment]
Okay, thank you very much. I'll reinstall the operating system and see.
