### ISSUE TITLE
Android Webview loadData call error function

### ISSUE THREAD

**Issue by Sevael** [axmolengine/axmol#2014]
UIWebViewImpl-android.cpp:

void WebViewImpl::loadData(const Data& data,
                           std::string_view MIMEType,
                           std::string_view encoding,
                           std::string_view baseURL)
{
    std::string dataString(reinterpret_cast<char*>(data.getBytes()), static_cast<unsigned int>(data.getSize()));
    JniHelper::callStaticVoidMethod(className, "setJavascriptInterfaceScheme", _viewTag, dataString, MIMEType, encoding,
                                    baseURL);
}

"setJavascriptInterfaceScheme" should be "loadData"

**Comment by rh101** [comment]
Good catch, and I'm really surprised this wasn't spotted long ago, since it's been there for years (2015, Cocos2d-x v3, or even earlier): https://github.com/cocos2d/cocos2d-x/blob/cd7446f17956d73041f9b33b37b4c747c6bc1993/cocos/ui/UIWebViewImpl-android.cpp#L179

Are you able to submit a PR for this?

**Comment by Sevael** [comment]
😊No, i no able to submit this PR, please submit it instead of me.
Thank you a lot.
