### ISSUE TITLE
Rename all AXLOG to AXLOGD (there be 417 without .\core) 

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#2019]
![image](https://github.com/axmolengine/axmol/assets/8652787/b7304f3b-bc65-443d-ac28-3a6ae5b49b22)

See PR: (https://github.com/axmolengine/axmol/pull/2017)

@halx99 
Can I do it or any issues for waiting?

**Comment by halx99** [comment]
Yes, you can, thanks

**Comment by aismann** [comment]
@halx99 
Before I start: All extensions (I belive yes)?
![image](https://github.com/axmolengine/axmol/assets/8652787/aa4fa114-7151-42f1-a7f8-360e29c3549e)

**Comment by halx99** [comment]
Yes
