### ISSUE TITLE
Two rapidjson with different version cause unexpected crash problem on apple family platforms

### ISSUE THREAD

**Issue by rh101** [axmolengine/axmol#2048]
- axmol version:
- devices test on:
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2+
   - Visual Studio:
      - VS version: 2022 (17.9+)
      - MSVC version: 19.39+
      - Windows SDK version: 10.0.22621.0+
   - cmake version:
Steps to Reproduce:

Firstly, this is not an issue with Axmol, but rather with the rapidjson library.

An application I ported over from Cocos2d-x was previously using an older version of rapidjson included with it (which was also from cocos2d-x), so it was never using the radpijson in Axmol.  Deleting the local version of rapidjson so the app would use the version supplied with Axmol has resulted in reproducible crashes on iOS (arm64).  

The crashes only occur in the release builds (with optimizations on).  The crashes do not occur with ARM debug or x86/x86_64 (debug/release).

The links below describe the issue, which is still unresolved, but there are a few ways to work around it.

https://github.com/Tencent/rapidjson/issues/388
https://github.com/Tencent/rapidjson/issues/301#issuecomment-93767130
https://github.com/Tencent/rapidjson/issues/601
https://github.com/cocos2d/cocos2d-x/issues/16492

Checking the local version of rapidjson, I noticed this difference in `document-wrapper.h`:

Axmol version:
```
#pragma once

#include "rapidjson.h"
#include "document.h"
```

Cocos2d-x version:
```
// Wrapper file for document.h to fix the crash bug (https://github.com/cocos2d/cocos2d-x/issues/16492)

// Bug in gcc 4.9.0 on ARM with ARM instruction set, -O2 causes the bug
// This gcc version cannot use #pragma GCC push_options/pop_options as well. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59884

#include "json/rapidjson.h"

#if defined(__arm__) && defined(RAPIDJSON_GNUC) && RAPIDJSON_GNUC >= RAPIDJSON_VERSION_CODE(4,9,0) && RAPIDJSON_GNUC < RAPIDJSON_VERSION_CODE(5,0,0)
    #pragma GCC optimize ("O1")
#endif
#include "document.h"
#if defined(__arm__) && defined(RAPIDJSON_GNUC) && RAPIDJSON_GNUC >= RAPIDJSON_VERSION_CODE(4,9,0) && RAPIDJSON_GNUC < RAPIDJSON_VERSION_CODE(5,0,0)
    #pragma GCC reset_options
#endif
```

The above optimization fix as implemented does not work with the latest Xcode 15, since the compiler checks don't do anything, and would need to be updated to work with the compiler used in Xcode 15.

The alternative work-around, which can be done in our projects, is to use the `CrtAllocator` instead, and have custom `Document` and `Value` types. For example:

```
namespace jsonfix
{
using JDocument = rapidjson::GenericDocument<rapidjson::UTF8<>, rapidjson::CrtAllocator>;
using JValue = rapidjson::GenericValue<rapidjson::UTF8<>, rapidjson::CrtAllocator>;
}
```

...and then use `jsonfix::JDocument` and `jsonfix::JValue` instead of `rapidjson::Document` and `rapidjson::Value`.   This is the way I've implemented it in my own project.

**Comment by solan-solan** [comment]
Thanks, it is very useful info

**Comment by smilediver** [comment]
Is it unaligned memory access crash or something else?

**Comment by rh101** [comment]
> Is it unaligned memory access crash or something else?

NULL pointer dereference crash in the `Malloc` method, `allocator.h`.  

The `shared_` variable is null, when it shouldn't be.

```
    //! Allocates a memory block. (concept Allocator)
    void* Malloc(size_t size) {
        RAPIDJSON_NOEXCEPT_ASSERT(shared_->refcount > 0);
        if (!size)
            return NULL;

        size = RAPIDJSON_ALIGN(size);
        if (RAPIDJSON_UNLIKELY(shared_->chunkHead->size + size > shared_->chunkHead->capacity))  //<< crashes here
            if (!AddChunk(chunk_capacity_ > size ? chunk_capacity_ : size))
                return NULL;

        void *buffer = GetChunkBuffer(shared_) + shared_->chunkHead->size;
        shared_->chunkHead->size += size;
        return buffer;
    }
```

**Comment by rh101** [comment]
@halx99 This issue is just to inform others of the problem, so if you want to set the "Helpdesk" label on it, then that would be good.  Feel free to close the issue at any time, since there may not be anything we can do about it in the rapidjson source.

**Comment by halx99** [comment]
maybe align issue, any memory pool implemention shoud ensue allocated address base align `max_align_t`, @rh101 could you try redefine RAPIDJSON_ALIGN?

**Comment by halx99** [comment]
https://github.com/yasio/yasio/issues/283

**Comment by rh101** [comment]
> maybe align issue, any memory pool implemention shoud ensue allocated address base align `max_align_t`, @rh101 could you try redefine RAPIDJSON_ALIGN?

The existing definition is this:

`#define RAPIDJSON_ALIGN(x) (((x) + static_cast<size_t>(7u)) & ~static_cast<size_t>(7u))`

Changing it to the following shows it aligning correctly, but it did not fix the problem, and still crashes because `shared_` is `NULL`:

`#define RAPIDJSON_ALIGN(x) (((x) + static_cast<size_t>(alignof(max_align_t) - 1) & ~static_cast<size_t>(alignof(max_align_t) - 1))`

Crashes in here:
```
//! Allocates a memory block. (concept Allocator)
void* Malloc(size_t size) {
    RAPIDJSON_NOEXCEPT_ASSERT(shared_->refcount > 0);
    if (!size)
        return NULL;

    size = RAPIDJSON_ALIGN(size);
    if (RAPIDJSON_UNLIKELY(shared_->chunkHead->size + size > shared_->chunkHead->capacity))  //<< crashes here
        if (!AddChunk(chunk_capacity_ > size ? chunk_capacity_ : size))
            return NULL;

    void *buffer = GetChunkBuffer(shared_) + shared_->chunkHead->size;
    shared_->chunkHead->size += size;
    return buffer;
}
```

**Comment by halx99** [comment]
could you provide reproduce sample code and device info to test on?

**Comment by rh101** [comment]
> could provide reproduce sample code and device info to test on?

I did try to create a reproducible test case, but no matter what I've tried so far, I can't reproduce it.

Running as a release build on an iPhone 7 (arm64).

The project is here: https://github.com/rh101/issue2048

The `test.json` file it is parsing is similar to the one that it crashes on in the main application.  If I manage to find out what the difference is between this and the main app, or manage to reproduce it, then I'll post an update.

**Comment by rh101** [comment]
Just something to note.  If the `Undefined Behavior Sanitizer` option is enabled for the current scheme, then the crash does not occur.

![image](https://github.com/user-attachments/assets/1d35006e-68d6-4189-a911-12c4eeb60f7d)

**Comment by rh101** [comment]
A few screenshots from the crash (from project with the issue, not the sample project):
![image](https://github.com/user-attachments/assets/c88a9853-7473-4982-b0a4-99bc2942700c)
![image](https://github.com/user-attachments/assets/34d4cc14-1e73-4ee1-a95c-9b2172b3506b)

**Comment by halx99** [comment]
reproduced by your sample project?

**Comment by rh101** [comment]
> reproduced by your sample project?

Sorry no, those screenshots are from the main project that has the issue.  I'll update the post to mention that.

**Comment by halx99** [comment]
![image](https://github.com/user-attachments/assets/3a868d88-47c2-4307-b938-6ba0916e3e48)
initializer-list order issue? try trace the execution order? or move shared_ from initializer-list to constructor body?

**Comment by rh101** [comment]
OK, so @halx99 pointed something out to me, which is that if a library linked to the application happens to use a different versions of rapidjson, then strange things may happen on iOS.

While tracing this issue, 2 different versions of the rapidjson `allocators.h` loaded from different code paths, so it turned out there is a library in the app that did in fact include its own version of rapidjson.  The mismatch with the implementation of the `MemoryPoolAllocator` was the cause of all of these issues.  Deleting the rapidjson from that library and forcing it to reference the version supplied with Axmol fixed the problem.

The issue only ever showed itself in the iOS release build, never in debug, and no other platform was affected, which really confused things.  Hopefully this helps anyone that ever runs into this issue in the future.
