### ISSUE TITLE
FontFreeType performance issues on Android

### ISSUE THREAD

**Issue by smilediver** [axmolengine/axmol#2063]
We have big performance issues on Android when creating Labels. It looks like the issue is that FontFreeType is not loading whole font file into memory, but is reading it like a regular file from APK. Reading from APK seems to be super slow (maybe only random seeking?). Profiler shows that it takes 8ms for reading glyph data. I have suspicion that it might be decompressing whole font file each time it is accessed.

<img width="1146" alt="Screenshot 2024-07-31 at 17 39 46" src="https://github.com/user-attachments/assets/40e7d57a-c105-42c6-9155-1936e8ccaa7a">

**Comment by halx99** [comment]
Check your build.gradle does the noCompress contains ttf, ttc

https://github.com/axmolengine/axmol/blob/dev/templates/common/proj.android/app/build.gradle#L83

**Comment by smilediver** [comment]
That solved the issue. Thanks!
