### ISSUE TITLE
UITest.json source

### ISSUE THREAD

**Issue by stanmalachowski** [axmolengine/axmol#2066]
Hi,

I am trying to build some of the test suite - specifically the UILayoutTest example and it wants to load a file UITest.json, which does not seem to be anywhere in the distribution. Is there something I have missed?

Thanks,

Stan

**Comment by rh101** [comment]
> I am trying to build some of the test suite - specifically the UILayoutTest example and it wants to load a file UITest.json

What do you mean by that?  Are you attempting to build `cpp-tests` and it is failing to find that file, or did you copy the source code into a different project?

`UITest.json` does exist in the `Content` folder of the cpp-tests project, and in fact there are multiple versions of it.  The test project will pick a specific version depending on the size of the test window.

You can see one of the `UITest.json` files in this screenshot of the `cpp-tests` folder:

![image](https://github.com/user-attachments/assets/26298e7d-6dbf-40ae-9f58-93300353f5eb)

**Comment by rh101** [comment]
Note that if you don't have a `Content` folder, or link to that folder, within the `cpp-tests` project, then the problem may be that you never ran the `axmol build` command, or something went wrong when running that command.  That would the issue that needs to be addressed.

The test project resources exist in a separate repository, and will be downloaded when you run the `axmol build` command.

If for some reason you want to download the test resources yourself, then you can find them [here](https://github.com/axmolengine/axmol-sample-assets).

**Comment by stanmalachowski** [comment]
@rh101  Thanks. I had a problem with the build and ignored it. This is fixed, and so the files are visible now. I appreciate your help
