### ISSUE TITLE
checkReallySupportsASTC does not work on ios device

### ISSUE THREAD

**Issue by BIGCATDOG** [axmolengine/axmol#2078]
- axmol version: latest version
- devices test on:iPhone XR
- developing environments
   - NDK version: r23c
   - Xcode version: 15.1
   - Visual Studio: 
      - VS version: 2022 (17.9+)
      - MSVC version: 19.39+
      - Windows SDK version: 10.0.22621.0+
   - cmake version: 
Steps to Reproduce:

1. glReadPixels always get black pixel so that checkReallySupportsASTC return false.
2.

**Comment by halx99** [comment]
by default ios use metal render backend, not GLES, do you means GLES? if so that should really means ios GLES render not support ASTC

**Comment by BIGCATDOG** [comment]
yes, i use GLES render backend.

**Comment by BIGCATDOG** [comment]
And it works perfect on android device. It is strange.

**Comment by BIGCATDOG** [comment]
@halx99  If i just hard code to make check function return true. Everything works well. ASTC texture can be rendered on screen on ios device.

**Comment by halx99** [comment]
should fixed by commits in branch https://github.com/axmolengine/axmol/tree/release-2.1.5

**Comment by BIGCATDOG** [comment]
> should fixed by commits in branch https://github.com/axmolengine/axmol/tree/release-2.1.5
It is very appreciated. Thanks for your hard work.
