### ISSUE TITLE
执行csb文件，打开界面慢

### ISSUE THREAD

**Issue by qq461787436** [axmolengine/axmol#2092]
- axmol version:2.1.5
- devices test on:mac os 14.6.1
- developing environments
   - Xcode version: 14.2+
Steps to Reproduce:
加载csb文件时候，加载重复加载plist，导致打开界面缓慢
CSLoader中SpriteFrameCache::getInstance()->isSpriteFramesWithFileLoaded(plist) 加载了文件还是返回false
![QQ20240816-141648](https://github.com/user-attachments/assets/d33f745c-8483-4602-bb85-82d5610fb0a6)
哪位大神知道怎么回事的吗？
我在加载csb之前会调用addSpriteFramesWithFile提前把资源加载进来，跟这个有关系吗？

**Comment by qq461787436** [comment]
我在加载csb之前会调用addSpriteFramesWithFile提前把资源加载进来
测试了下，确实是提前addSpriteFramesWithFile加载后，打开csb文件会导致这个问题
SpriteFrameCache::getInstance()->addSpriteFramesWithFile(_FullPath, _Texture2D)
这样加载的

**Comment by qq461787436** [comment]
SpriteFrameCache::getInstance()->addSpriteFramesWithFile(_FullPath, _Texture2D)调用这个加载plist时候不能填写完整路径，只能填写文件名才能正确与加载和使用，否则会出现上面情况

**Comment by halx99** [comment]
确实应该统一用 fullPath

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by qq461787436** [comment]
调用的这个获取文件的完整路径ax::FileUtils::getInstance()->fullPathForFilename()

**Comment by qq461787436** [comment]
貌似addSpriteFramesWithFile传入完整路径，SpriteFrameCache的_spriteSheets的会把路径当key，当csb加载的时候是以文件名请求加载，_spriteSheets按这个文件名查找，结果没有找到对应的对象就重新加载了！

**Comment by halx99** [comment]
嗯，目前实现内部不会转换路径，也就是说外部需要保证加载某个 plist 路径形式一致性

**Comment by halx99** [comment]
看了下原 cocos2dx 也不会强制以 fullPath 作为 key

**Comment by qq461787436** [comment]
嗯，cocos那边我是主线程加载直接传文件名的，所以一直没发现还这个需要注意这个，现在升级成axmol引擎我改成了多线程资源加载，加载完成后用完整路径进行添加了，才导致这样的情况，现在直接改成文件名了，完美解决！
