### ISSUE TITLE
ZipUtils class - How to use it (need examples)

### ISSUE THREAD

**Issue by asnagni** [axmolengine/axmol#2139]
Hi,
   I'm trying to use the class ax::ZipUtils . The goal is to unzip a file that I dowloaded on the device (iOS & Android). Unfortunately there is no example or documentation on how to use this class. Do anyone have an idea on how to use this class? I do not want to install an extra library if Axmol has one that I can use.
  
Thank you,
Stay safe

- axmol version: 2.1.5
- devices test on: iOs, Android
- developing environments
   - NDK version: n/a
   - Xcode version:  n/a
   - Visual Studio:  n/a
      - VS version:  n/a
      - MSVC version:  n/a
      - Windows SDK version:  n/a
   - cmake version: 3.30.1
Steps to Reproduce:

1. download a Zip file on the device
2. Try to unzip it

**Comment by rh101** [comment]
You should use `ax::ZipFile`.  The methods in that class are pretty self-explanatory. 

Simple example:
```
const auto zipFile = std::unique_ptr<ax::ZipFile>(ax::ZipFile::createFromFile(zipFilePath));
if (zipFile && zipFile->fileExists("data.json"sv))
{
    std::string s;
    ax::ResizableBufferAdapter buf(&s);
    if (zipFile->getFileData("data.json"sv, &buf))
    {
        // do something with the data
    }
}
```

**Comment by asnagni** [comment]
Hi @rh101 ,
   Thank you for the info. 
   I was looking at the wrong class apparently. Thank you for the info and the example, I do appreciate.


Stay safe.

**Comment by rh101** [comment]
> Hi @rh101 , Thank you for the info. I was looking at the wrong class apparently. Thank you for the info and the example, I do appreciate.
> 
> Stay safe.

No problem.  Please do not forget to close this issue, and any others you have created that should be closed.
