### ISSUE TITLE
WASM: Element.setCapture() is deprecated. Use Element.setPointerCapture() instead. For more help https://developer.mozilla.org/docs/Web/API/Element/setPointerCapture

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#2212]
`Element.setCapture()` should be replace.
![image](https://github.com/user-attachments/assets/81482234-cc7d-41e2-82b4-26a603de7885)

**Comment by halx99** [comment]
There no any invoke on axmol engine, so we can't control it

**Comment by aismann** [comment]
I have replaced it on the "*.js" file of my project and its works.

**Comment by halx99** [comment]
which file?

**Comment by aismann** [comment]
> which file?

created < project >.js
e.g.: cpp-tests.js

**Comment by halx99** [comment]
while, the cpp-tests.js is build by emsdk, so we can't control that

**Comment by aismann** [comment]
> is build by emsdk

I know. But I can edit it after build.
Maybe thats an usefull help for somebody

**Comment by halx99** [comment]
should be an emsdk issue
