### ISSUE TITLE
feature-request: Android 15 for 16 KB page sizes support

### ISSUE THREAD

**Issue by bintester** [axmolengine/axmol#2219]
Android 15 has been released!
It may become the minimum adaptation requirement for listing on Google Play in the near future.
Notice that in the update information, there is a support requirement for [16 KB page sizes](https://developer.android.com/about/versions/15/behavior-changes-all#16-kb).
Will the engine be adapted in the future?
[Guides](https://developer.android.google.cn/guide/practices/page-sizes)

**Comment by halx99** [comment]
under axmol ndk-r23c, add additional link flags: `"-Wl,-z,max-page-size=16384"`

**Comment by halx99** [comment]
seems libc++_shared.so need from newer ndk or from ci.android.com

**Comment by halx99** [comment]
There two PR

- Add build 16KB page size support, but not enable by default: #2268 
- Enable 16KB page size for libc++_shared.so via set default ndk to r23d(install from Android CI: #2269
