### ISSUE TITLE
io_server异常崩溃

### ISSUE THREAD

**Issue by qq461787436** [axmolengine/axmol#2224]
- axmol version:2.2.1
- devices test on:win 10
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2+
   - Visual Studio: 
      - VS version: 2022 (17.9+)
      - MSVC version: 19.39+
      - Windows SDK version: 10.0.22621.0+
   - cmake version: 
Steps to Reproduce:
崩溃如图：
![IMG_1676_副本](https://github.com/user-attachments/assets/18daf25d-2397-41a8-9845-29f421091809)

**Comment by halx99** [comment]
如何重现？

**Comment by qq461787436** [comment]
每隔5秒钟http post请求服务器数据，在win10下挂了有三天机的时候出现的

**Comment by halx99** [comment]
这看上去有点难重现呀，出现后 vs 调试下，看了下逻辑，正常应该不会出现这种情况

**Comment by halx99** [comment]
另外，看看能否找到必现条件

**Comment by qq461787436** [comment]
嗯，好的

**Comment by qq461787436** [comment]
后面发现，这个主要是http请求的计时器漏掉释放导致异常了，修改了下再没出现了
