### ISSUE TITLE
How to Retrieve True Size of axmol::ui::RichText Using getContentSize()

### ISSUE THREAD

**Issue by asnagni** [axmolengine/axmol#2227]
Hello everyone,

I’m encountering an issue with the axmol::ui::RichText class and the getContentSize() method, and I’m hoping someone might have a solution.

**Problem**
I want to retrieve the true size of a RichText object based on the text it contains. However, I'm running into the following behavior:

If I don't set the content size, getContentSize() always returns (0, 0).
If I do set the content size beforehand, getContentSize() just returns the size that I manually set, regardless of the actual size of the text.

**Example:**
In the code example I’ve provided, I create two axmol::ui::RichText objects, display them, and try to retrieve their true size based on their content. I expected getContentSize() to return the actual dimensions of the text, but the behavior seems inconsistent with what I need.

[HelloCpp 2.zip](https://github.com/user-attachments/files/17569157/HelloCpp.2.zip)

I've included two images:

No annotations – to show the plain rendering of the text.
With annotations – to highlight what I believe the correct size should be for the RichText.

**Question:**
Does anyone know a reliable way to get the true size of an axmol::ui::RichText object? Any insights or workarounds would be greatly appreciated!

Thanks in advance for your help. Stay safe!

Best regards

- axmol version: 2.1.5
- devices test on: iPhone 11, iPhone 14, Alcatel 
- developing environments
   - NDK version: 23.2.8568313
   - Xcode version: 15.4
   - Visual Studio: 
      - VS version: n/a
      - MSVC version: n/a
      - Windows SDK version: n/a
   - cmake version: 3.30.1
Steps to Reproduce:

1.  create a axmol::ui::RichText
2. add some text 
3. display it
4. call getContentSize()

No annotations:
![Screenshot 2024-10-30 at 5 01 16 AM copy](https://github.com/user-attachments/assets/6223b306-4988-42e7-9e78-b41d37b8015a)

With annotations:
![Screenshot 2024-10-30 at 5 01 16 AM](https://github.com/user-attachments/assets/cf45e745-14ec-48ec-8d26-e7be0da30524)

**Comment by rh101** [comment]
When a `RichText` object is created, the actual creation of the contents based on the `RichText` elements isn't done until `Widget::visit()` is called, which means the content size has not yet been calculated. The content size would be valid after the frame is drawn, so on the next update loop.  

You can force the calculation by using `RichText::formatText(bool force)`, so something like the following:

```
auto richText = RichText::create();

// add the rich text elements

richText->formatText(true); // force the creation of the elements and the calculation of the content size

auto contentSize = richText->getContentSize(); // read the updated content size
```

**Comment by asnagni** [comment]
Hi @rh101,
   Thank you for this information. We just tested it and worked.
   
   I really do appreciate,
   Stay safe
