### ISSUE TITLE
BUG that Khmer language displays incorrectly using ttf text

### ISSUE THREAD

**Issue by cxcxiaochuan** [axmolengine/axmol#2249]
The framework displays Khmer TTF text content incorrectly. The text content pattern displayed is different from the original text content pattern that needs to be displayed, and the Khmer TTF text content is easily triggered

AXLOG("LabelTextFormatter error: can't find letter definition in font file for letter: 0x%x",character);

**Comment by rh101** [comment]
Can you please show screenshots of actual and expected output?

Also, are you able to provide the TTF font file that you use for the Khmer text?

**Comment by cxcxiaochuan** [comment]
> Can you please show screenshots of actual and expected output?
> 
> Also, are you able to provide the TTF font file that you use for the Khmer text?

OK, wait a minute.

**Comment by cxcxiaochuan** [comment]
The original text on the button below is as follows:ចាប់ផ្តើម

But the content displayed by the program becomes the following screenshot
![屏幕截图 2024-11-26 131948](https://github.com/user-attachments/assets/26c2a87f-14aa-44dd-b18b-92c41a1e0bf6)

**Comment by cxcxiaochuan** [comment]
This is the Khmer ttf file used.

**Comment by cxcxiaochuan** [comment]
I can't give you the Khmer ttf file, the platform doesn't allow it to be transferred.

We don’t support that file type.

Try again with GIF, JPEG, JPG, MOV, MP4, PNG, SVG, WEBM, CPUPROFILE, CSV, DMP, DOCX, FODG, FODP, FODS, FODT, GZ, JSON, JSONC, LOG, MD, ODF, ODG, ODP, ODS, ODT, PATCH, PDF, PPTX, TGZ, TXT, XLS, XLSX or ZIP.

**Comment by cxcxiaochuan** [comment]
This is the name of the Khmer ttf file we use: NotoSansKhmer-SemiBold.ttf

You can download it online.

**Comment by cxcxiaochuan** [comment]
This is the Khmer ttf file our app uses:
[NotoSansKhmer-SemiBold.zip](https://github.com/user-attachments/files/17913106/NotoSansKhmer-SemiBold.zip)

**Comment by rh101** [comment]
Can reproduce this issue.  

Just as a test, using the system font, it displays correctly:
![image](https://github.com/user-attachments/assets/f439b6e8-7b12-4d10-9539-569b5b235f9b)

**Comment by cxcxiaochuan** [comment]
Yes, it will display correctly when using system characters, but will display incorrectly when using ttf characters.

**Comment by rh101** [comment]
After looking into this, and as a complete guess, the problem may be in `Label::multilineTextWrap` or `FontAtlas::prepareLetterDefinitions`, but I'm not familiar with the logic to figure out why.

Also, the text that reproduces the issue can be narrowed down to the following:
`ផ្តើ`

which ends up rendering as:
![image](https://github.com/user-attachments/assets/80cfb47c-79db-4359-a548-19ec7df3aefc)

The problem could also be that the generated font atlas has bitmaps of the individual glyphs that would be combined to make up that character, but once they are in the font atlas, they look nothing like what they should be when combined together.  So, the rendering code is attempting to create a single `ផ្តើ` from individual bitmaps, and I don't understand how that would ever work, since they're all bitmap images of individual characters.  This is all assuming that the `FontAtlas` contains bitmaps, and that I am not confused about how it works (please correct me if I'm wrong).

**Comment by rh101** [comment]
@DelinWorks You may have some insight into this issue. Would something like this require a shaping engine (like Harfbuzz)?

**Comment by smilediver** [comment]
Text layout that `Label` is doing is really primitive, I don't think it will support complex languages with heavy use of diacritics, or where multiple unicode characters combine into the single one glyph, or has ligatures, etc. It only works for "simple" languages that mostly directly translate unicode's characters to visual glyphs. Diacritics may work in some cases, but probably heavily depends on the font.

I'm afraid that the only solution is to use some kind of library, where you can supply your text and get a ready image for use. Or have a custom label implementation that would support the languages you need, but that's a lot of work. Maybe using system fonts could also work.

**Comment by cxcxiaochuan** [comment]
This kind of small language is a problem. The language is too complicated. We can't understand the basic grammar and rules of the language at all, and we can't modify it specifically. We might as well give up supporting this language. Anyway, the target population of this small language is relatively small.

**Comment by cxcxiaochuan** [comment]
Do you want me to close this question? Click No and abandon the revisions to this question.

**Comment by cxcxiaochuan** [comment]
Need to close this issue? We discard revisions to this issue.

**Comment by DelinWorks** [comment]
@rh101 it's similar to vowels in the arabic language, like عَ اٍ رْ 
these are 0 width characters that have worked great with me in axmol.
I really don't know this khmer language so I can't make assumptions on how it works and if it needs a shaping engine like in the arabic lanuage

**Comment by DelinWorks** [comment]
Have you guys looked into harfbuzz? or in the unicode list https://www.compart.com/en/unicode/
and try to find out if your language have some kind of pattern to how it's displayed?
this is what I did for the arabic shaping engine but then again I can't really tell on a language I don't know

**Comment by cxcxiaochuan** [comment]
Haven't watched harfbuzz.

**Comment by cxcxiaochuan** [comment]
Does the axmol engine support Arabic TTF fonts?

**Comment by smilediver** [comment]
Arabic is right to left and there's no support for right to left languages.

**Comment by DelinWorks** [comment]
yes, axmol does support Arabic script TTF fonts, but the text will look "unconnected" and you would need to use a shaping engine like harfbuzz, I've coded a simple Arabic shaping engine for axmol a while back [https://github.com/DelinWorks/arabic-text-renderer-cpp-axmol](https://github.com/DelinWorks/arabic-text-renderer-cpp-axmol) and it works great, only in the Arabic language category like Persian , Urdu, Pashto, Kurdish and Malay but some modifications have to be made

**Comment by DelinWorks** [comment]
@smilediver 
> Arabic is right to left and there's no support for right to left languages.

there's an option in axmol to view text RTL, but as long as you shape your text you won't really need this 
`label->setHorizontalAlignment(TextHAlignment::RIGHT);`

**Comment by cxcxiaochuan** [comment]
Thanks

**Comment by smilediver** [comment]
Does it really? I think it just aligns text to the right side, but in Arabic "abc" needs to be displayed as "cba". I don't think there's support for that, unless I'm mistaken. And it's even more complicated than just reversing letters as you know. :)

**Comment by DelinWorks** [comment]
yes, that's what the shaping engine does, it reverses it like "cba" instead of "abc" so it looks right for Arabic, it also does connectives like بـت instead of ب ت

**Comment by cxcxiaochuan** [comment]
There is no way. Arabic writing is different from Chinese, English, Japanese and other languages. It is in the opposite direction.

**Comment by DelinWorks** [comment]
what do you mean there's no way? I was able to achieve it in axmol pretty easily,
even if it's in opposite direction that's not a big issue, just reverse the text and add connectives and that's basically what shaping is, this is how every major OS does it, including harfbuzz library.

**Comment by DelinWorks** [comment]
if you were talking about axmol supporting it right out of the box then no axmol doesn't, but that doesn't mean libraries like harfbuzz can't exist

**Comment by cxcxiaochuan** [comment]
It would be better if the Arabic TTF could be integrated into axmol, but it doesn't matter if it can't be integrated. The current TTF is sufficient anyway. It's just that the display in some places does not conform to the habits of Arabs. They should be able to understand it in the context. After all, most of the information they come across on the Internet is from left to right.

**Comment by rh101** [comment]
> It would be better if the Arabic TTF could be integrated into axmol, but it doesn't matter if it can't be integrated. The current TTF is sufficient anyway. It's just that the display in some places does not conform to the habits of Arabs. They should be able to understand it in the context. After all, most of the information they come across on the Internet is from left to right.

I'm not sure what you mean by some of those remarks, but they can be misconstrued.  It's also off-topic, since this issue isn't about the Arabic language or Axmol support for it.  As @DelinWorks has explained, using the Harfbuzz library, support can be added on top of Axmol or any other engine in order to generate the correct output.

If you wish to go down that path of using Harfbuzz, then look into DelinWorks' own project that was linked above to get some idea of how to implement it.

Other than that, I'm not sure that anything more can be done to fix this in Axmol at this point in time.  Perhaps in the future it will be revisited, but it's not something trivial to implement.

**Comment by cxcxiaochuan** [comment]
OK

**Comment by DelinWorks** [comment]
> It would be better if the Arabic TTF could be integrated into axmol, but it doesn't matter if it can't be integrated. The current TTF is sufficient anyway. It's just that the display in some places does not conform to the habits of Arabs. They should be able to understand it in the context. After all, most of the information they come across on the Internet is from left to right.

I'm not sure what you mean by that, it's off topic. but yeah it should be easy to implement for any other language, just different complex rulesets, with the renderer at your disposal along with an open source codebase, the sky is the limit for what you can do!

**Comment by cxcxiaochuan** [comment]
Sorry, I got off topic and jumped to another question.
