### ISSUE TITLE
UIMediaPlayer action no working problem

### ISSUE THREAD

**Issue by Sevael** [axmolengine/axmol#2253]
UIMediaPlayer function "void pause()" and "void resume()" are confuse with "void Node::pause()" and "void Node::resume()".
It cause all action attatch to UIMediaPlayer is not working, because the the Node:resume() will never call.

Is is better change the name of "UIMediaPlayer::pause()" and "UIMediaPlayer::resume()" to
something like:  "UIMediaPlayer::pauseVideo()" and  "UIMediaPlayer::resumeVideo()"

after change the name, it work fine.

Thank you.

**Comment by Sevael** [comment]
the best way to fixed this problem is:

``

void MediaPlayer::pause() {
    Widget::pause();
    pauseVideo();
}

void MediaPlayer::resume() {
    Widget::resume();
    resumeVideo();
}

void MediaPlayer::pauseVideo()
{
//blablabla
}

void MediaPlayer::resumeVideo()
{
//blablabla
}

``

**Comment by paulocoutinhox** [comment]
The `resume` will call `Widget::pause();` too?
