### ISSUE TITLE
Increase in ANR after upgrading from cocos to axmol

### ISSUE THREAD

**Issue by aryamansingh2008** [axmolengine/axmol#2281]
- Axmol version: v2.2.1

- ANR is observed on multiple devices and android versions.

- Stack trace from google play console for the main and openGL thread

Main Thread:
```
  at java.lang.Object.wait (Native method)
  at java.lang.Object.wait (Object.java:405)
  at java.lang.Object.wait (Object.java:543)
  at android.opengl.GLSurfaceView$GLThread.onWindowResize (GLSurfaceView.java:1789)
  at android.opengl.GLSurfaceView.surfaceChanged (GLSurfaceView.java:550)
  at android.view.SurfaceView.updateSurface (SurfaceView.java:1240)
  at android.view.SurfaceView.setWindowStopped (SurfaceView.java:446)
  at android.view.SurfaceView.surfaceCreated (SurfaceView.java:1942)
  at android.view.ViewRootImpl.notifySurfaceCreated (ViewRootImpl.java:2294)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:3646)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:2542)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:9556)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1326)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1334)
  at android.view.Choreographer.doCallbacks (Choreographer.java:967)
  at android.view.Choreographer.doFrame (Choreographer.java:880)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1309)
  at android.os.Handler.handleCallback (Handler.java:942)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:204)
  at android.os.Looper.loop (Looper.java:291)
  at android.app.ActivityThread.main (ActivityThread.java:8154)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:601)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1136)
```

OpenGL Thread:
```
  #00  pc 0x0000000000034b6c  /apex/com.android.runtime/lib/bionic/libc.so (syscall+28)
  #01  pc 0x00000000002106af  /apex/com.android.art/lib/libart.so (art::ConditionVariable::WaitHoldingLocks+86)
  #02  pc 0x00000000003b0091  /apex/com.android.art/lib/libart.so (art::JNI<false>::NewStringUTF+532)
  #03  pc 0x0000000001d5aecc  /data/app/~~6t2756CgQ9aGSNJsabqKzQ==/com.sample.app-lK5w-UXZWBKgtRr-kH5-XQ==/split_config.armeabi_v7a.apk (_getClassID(char const*)+80) (BuildId: 1880e46fd482ab2b499e2bd9d2f2a52daff3dbdd)
  #04  pc 0x0000000001d5b46c  /data/app/~~6t2756CgQ9aGSNJsabqKzQ==/com.sample.app-lK5w-UXZWBKgtRr-kH5-XQ==/split_config.armeabi_v7a.apk (ax::JniHelper::getStaticMethodInfo(ax::JniMethodInfo_&, char const*, char const*, char const*)+100) (BuildId: 1880e46fd482ab2b499e2bd9d2f2a52daff3dbdd)
  #05  pc 0x0000000001d5a190  /data/app/~~6t2756CgQ9aGSNJsabqKzQ==/com.sample.app-lK5w-UXZWBKgtRr-kH5-XQ==/split_config.armeabi_v7a.apk (ax::BitmapDC::getBitmapFromJavaShadowStroke(std::__ndk1::basic_string_view<char, std::__ndk1::char_traits<char>>, int, int, ax::Device::TextAlign, ax::FontDefinition const&)+52) (BuildId: 1880e46fd482ab2b499e2bd9d2f2a52daff3dbdd)
  #06  pc 0x0000000001d59db0  /data/app/~~6t2756CgQ9aGSNJsabqKzQ==/com.sample.app-lK5w-UXZWBKgtRr-kH5-XQ==/split_config.armeabi_v7a.apk (ax::Device::getTextureDataForText(std::__ndk1::basic_string_view<char, std::__ndk1::char_traits<char>>, ax::FontDefinition const&, ax::Device::TextAlign, int&, int&, bool&)+112) (BuildId: 1880e46fd482ab2b499e2bd9d2f2a52daff3dbdd)
  #07  pc 0x0000000001e27e14  /data/app/~~6t2756CgQ9aGSNJsabqKzQ==/com.sample.app-lK5w-UXZWBKgtRr-kH5-XQ==/split_config.armeabi_v7a.apk (ax::Texture2D::initWithString(std::__ndk1::basic_string_view<char, std::__ndk1::char_traits<char>>, ax::FontDefinition const&)+360) (BuildId: 1880e46fd482ab2b499e2bd9d2f2a52daff3dbdd)
  #08  pc 0x0000000001e2db94  /data/app/~~6t2756CgQ9aGSNJsabqKzQ==/com.sample.app-lK5w-UXZWBKgtRr-kH5-XQ==/split_config.armeabi_v7a.apk (ax::VolatileTextureMgr::reloadAllTextures()+572) (BuildId: 1880e46fd482ab2b499e2bd9d2f2a52daff3dbdd)
  #09  pc 0x0000000001d5ac94  /data/app/~~6t2756CgQ9aGSNJsabqKzQ==/com.sample.app-lK5w-UXZWBKgtRr-kH5-XQ==/split_config.armeabi_v7a.apk (Java_org_axmol_lib_AxmolRenderer_nativeInit+116) (BuildId: 1880e46fd482ab2b499e2bd9d2f2a52daff3dbdd)
  at org.axmol.lib.AxmolRenderer.nativeInit (Native method)
  at org.axmol.lib.AxmolRenderer.onSurfaceCreated (AxmolRenderer.java:77)
  at android.opengl.GLSurfaceView$GLThread.guardedRun (GLSurfaceView.java:1549)
  at android.opengl.GLSurfaceView$GLThread.run (GLSurfaceView.java:1280)
```

From my understanding, it looks like operations for the recovery from context loss are too heavy. Any suggestions or planned improvements to resolve this?

I was using this flow of OpenGLSurfaceView in cocos where super.onPause() wasn't being called: [Ref](https://github.com/cocos2d/cocos2d-x/blob/v4/cocos/platform/android/java/src/org/cocos2dx/lib/Cocos2dxGLSurfaceView.java)
I know this wasn't the best practise, and I am not aware of the repercussions of this but this didn't cause any ANRs or Crashes.

**Comment by rh101** [comment]
> I was using this flow of OpenGLSurfaceView in cocos where super.onPause() wasn't being called: [Ref](https://github.com/cocos2d/cocos2d-x/blob/v4/cocos/platform/android/java/src/org/cocos2dx/lib/Cocos2dxGLSurfaceView.java)
> I know this wasn't the best practise, and I am not aware of the repercussions of this but this didn't cause any ANRs or Crashes.

Not calling `super.onPause()` may not have immediate side-effects.  Take a look at the code in the `super.onPause()` to see what it does, and if not calling it is acceptable for you, then that is a possible solution, but, this specific crash is one that I personally haven't seen before.  Is the crash the same on all devices, meaning `ax::Texture2D::initWithString` is in the call stack for all device logs?

**Comment by aryamansingh2008** [comment]
To clarify, this is not a crash, it is a App Not Responsive (ANR) event defined by google as [Ref](https://developer.android.com/topic/performance/vitals/anr#:~:text=An%20ANR%20is%20triggered%20for,screen%20touch)%20within%205%20seconds.). 

**Is the crash the same on all devices, meaning ax::Texture2D::initWithString is in the call stack for all device logs?**
Yeah, the stack trace is same for all devices.

**Comment by rh101** [comment]
> To clarify, this is not a crash, it is a App Not Responsive (ANR) event defined by google as [Ref](https://developer.android.com/topic/performance/vitals/anr#:~:text=An%20ANR%20is%20triggered%20for,screen%20touch)%20within%205%20seconds.).

Fair enough, so it seems to be taking too long to recover all the textures.

> **Is the crash the same on all devices, meaning ax::Texture2D::initWithString is in the call stack for all device logs?**
> Yeah, the stack trace is same for all devices.

So it is something related to the Label textures.  Have you looked into this? Specifically, what is it attempting to recover when it calls `ax::Texture2D::initWithString` from `ax::VolatileTextureMgr::reloadAllTextures()`.

**Comment by rh101** [comment]
If you haven't been able to reproduce this, then there is a way to force it to happen.

Open [AxmolActivity.java](https://github.com/axmolengine/axmol/blob/c2ce413ad32b9ae316cb00093f6af6743e9c65a1/core/platform/android/java/src/dev/axmol/lib/AxmolActivity.java#L311), and change the `true` to a `false` in the call to `setPreserveEGLContextOnPause`:

`this.mGLSurfaceView.setPreserveEGLContextOnPause(true); // change this to false`

This will always cause the EGL context to be destroyed if the activity goes into the background, so it will trigger the texture reload etc..  It should make it easy to debug the issue in order to help you narrow down what is causing it in your application.

**Comment by rh101** [comment]
@aryamansingh2008 Any luck with tracing the source of the problem?

**Comment by aryamansingh2008** [comment]
I use axmol version 2.2.1 along with some custom changes done on top of that. Had found a potential issue due to the patch that we apply on it. Have released the client with those changes. The ANR metrics aren't present yet for that release, will update here once those metrics are available along with the issue. Thanks for the support.

**Comment by aryamansingh2008** [comment]
The issue is fixed. GLSurefaceView setPreserveEGLContextOnPause was set to false which was causing reload of all textures when app came from background to foreground which resulted in increase of ANRs. Thanks for the help.

**Comment by rh101** [comment]
> The issue is fixed. GLSurefaceView setPreserveEGLContextOnPause was set to false which was causing reload of all textures when app came from background to foreground which resulted in increase of ANRs. Thanks for the help.

`setPreserveEGLContextOnPause(true);` may minimize the number of times the ANR happens, but it will not prevent the ANR until you discover the true source of it.  The reason is that `setPreserveEGLContextOnPause(true);` doesn't completely avoid the EGL context loss, because Android can still invalidate the context under certain conditions.  The fact that it was `false`, when it should be `true`, it not entirely relevant, because the ANR should not be happening when reloading textures, so the cause of the ANR is still somewhere else in your project.

**Comment by aryamansingh2008** [comment]
It's not a crash but ANR, so by making preserveEGLContextOnPause true, I am decreasing the number of times the reload operation occurs. But yeah, there could be an underlying issue which is causing it to take more time than expected.

**Comment by rh101** [comment]
> It's not a crash but ANR, so by making preserveEGLContextOnPause true, I am decreasing the number of times the reload operation occurs. But yeah, there could be an underlying issue which is causing it to take more time than expected.

Sorry, yes, ANR, not crash. I'll update my post to reflect that.  

It would be good to find out the true cause of this.  As an alternative, you could always have the application restart, or go back to the base scene, meaning no texture reload needs to take place, completely avoiding the ANR, and since the EGL context loss should be a rare occurrence, this should have minimal impact on users.  Refer to [this](https://github.com/axmolengine/axmol/wiki/Options-for-handling-EGL-Context-loss-on-Android) wiki post for more info on the available options in dealing with this scenario.

**Comment by aryamansingh2008** [comment]
Thanks for referring the wiki post. Does AX_ENABLE_CACHE_TEXTURE_DATA being true mean that texture memory footprint is also double?

**Comment by rh101** [comment]
> Thanks for referring the wiki post. Does AX_ENABLE_CACHE_TEXTURE_DATA being true mean that texture memory footprint is also double?

I think that may be the case, and it's always been that way since Cocos2d-x.  It definitely caches any generated textures (such as from `RenderTexture` etc.), and possibly also caches textures of images loaded from storage media.
