### ISSUE TITLE
Support VS2022 preview in setup.ps1

### ISSUE THREAD

**Issue by Dilrevx** [axmolengine/axmol#2282]
I was installing axmol with error due to  $vm_installs=[] at line 777 at `find_vs`:

![image](https://github.com/user-attachments/assets/04f3c685-29ff-49bc-bb71-95bdc44c5e5b)

The original script does not have the `-prerelease` flag, so `vswhere.exe` wont return preview versions.

I suppose adding this flag shall solve the issue.

- developing environments
   - Visual Studio: 
      - VS version: 2022 preview

**Comment by halx99** [comment]
Thanks for your suggestion, done
