### ISSUE TITLE
Windows Universal Platform (UWP) Support?

### ISSUE THREAD

**Issue by Obg1** [axmolengine/axmol#232]
Can you add Windows Universal Platform (UWP)?
It was available on older Cocos2d-x 3 versions

**Comment by halx99** [comment]
Yes, we have plan to support UWP: https://github.com/c4games/engine-x/projects/2

**Comment by aismann** [comment]
Usefull for Xbox One/X Platform.

**Comment by Obg1** [comment]
Yes and also Windoes store. In the past Cocos2dx support uwp, I think it had support in version 3.15

**Comment by aismann** [comment]
Maybe this is helping to convert/add UWP to adxe:
https://github.com/Microsoft/DesktopBridgeToUWP-Samples
Desktop Conversion Extensions is a bridge that enables you to convert your classic desktop application (like Win32, Windows Forms, and WPF) or game to a Universal Windows Platform (UWP) app or game.

**Comment by balancedwolf** [comment]
It works for Desktop applications, Xbox still requires the full implementation

**Comment by appakabar** [comment]
I confirm, winRT support that allows to produce UWP format was available in 3.15 and is easy to copy/paste for support in 3.17.

**Comment by balancedwolf** [comment]
There is a problem with the audio player as of 3.17, but taking advantage of the unified OpenAL the project has, it might be easier to debug caching problems. There is also no gamepad support.

**Comment by balancedwolf** [comment]
I will share you my cocos2d-x 4.0 UWP port, and start working on a fork, I just don't have a few prebuilt libraries from the dependencies/thirdparty folder, it's stuck at the linking phase, I think I have the lua thing built already

**Comment by balancedwolf** [comment]
This one is it:

https://github.com/Greentwip/time-trio

UWP Port of 4.0 version.

Problem is some libraries need to be compiled from source, I've already compiled angle, lua, openssl I gues? But bullet, and some other need their precomps. I'll try to follow up with the adxe structure, right now I don't know how to disable glfw and purely add the missing UWP files using OpenGL.

**Comment by balancedwolf** [comment]
Not probably UWP (I'm almost done with the port) but you can try this Xbox port I've finished compiling, you'll just need the open Microsoft GDK (or sign up for the internal Microsoft GDK):

https://github.com/balancedwolf/adxe

See: CMakeGDKXboxOne.cmake and CMakeLists.txt from the time-trio repo to build your game.

**Comment by aismann** [comment]
@hal99,
Hope this is still active and part of axys 1.1

**Comment by aismann** [comment]
@halx99 
please add labels:
pinned
help wanted

**Comment by aismann** [comment]
https://github.com/Greentwip/cocos2d-x
XBOX one port

**Comment by halx99** [comment]
axmol UWP screenshot:

![image](https://user-images.githubusercontent.com/6977319/223394103-c3e102d0-c587-41c2-94ac-54c24072e30f.png)

**Comment by bensgigi** [comment]
> axmol UWP screenshot:
> 
> ![image](https://user-images.githubusercontent.com/6977319/223394103-c3e102d0-c587-41c2-94ac-54c24072e30f.png)

Amazing!

**Comment by aismann** [comment]
Time to clean my XBOX One ;)
