### ISSUE TITLE
Missing WebView2.h on new adxe project like: adxe new -p hellocpp.adxe.org -d D:\dev\projects\ -l cpp --portrait HelloCpp

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#525]
Workaround:
Copy packages folder  'adxe\build\packages' to D:\dev\projects\16+_Games\build\

Seems "packages ' is not part of the  'adxe new' command

**Comment by rh101** [comment]
The `setup.py` is what downloads the relevant NuGet packages, so you would need to run that again after updating to the latest ADXE.  You shouldn't need to copy anything manually.
