### ISSUE TITLE
Migrate engine name, huge changes

### ISSUE THREAD

**Issue by halx99** [axmolengine/axmol#724]
## source code
- [x] New namespace full name `axmol`, shorten name `ax` @halx99
   - compatible: alias ax to cocos2d: namespace cocos2d = axys; works on old projects who use cocos2dx
- [x] macros: `CC_` to `AX_`
- [ ] Remove source code file name prefix `CC`, such as `CCFileUtils` to `FileUtils`
- [x] Change all `https://adxeproject.github.io` to `https://bytedance.com`
- [x] Migrate extension `axlua` 
- [x] Migrate lua script const prefix `CC_`

## project tools
- [x] cmdline tool: rename from `adxe` to `axmol`
- [x] cmake script: everything `cocos2d` to `axmol`, `CC_` to `AX_`

## docs

- [x] readme files
- [x] docs
- [ ]  logo

**Comment by aismann** [comment]
It is the right way. Great!

**Comment by aismann** [comment]
> * [ ]  Remove source code file name prefix `CC`, such as `CCFileUtils` to `FileUtils`

Maybe prefix AC is better?  uch as `CCFileUtils` to `AXFileUtils`

**Comment by DelinWorks** [comment]
> * [ ]  Remove source code file name prefix `CC`, such as `CCFileUtils` to `FileUtils`

You can add the `breaks compatibility` label so that people know why their project won't compile.

**Comment by halx99** [comment]
I will merge all before any migrate commit to branch `release` and change github default branch to it.

Certainly, any pull request sitll and always been want merge to branch `dev`

**Comment by DelinWorks** [comment]
Should we cleanse every source file that contains `cocos2d` with the word `axis`?

**Comment by aismann** [comment]
> Should we replace every source file that contains `cocos2d` with `axis`?

I think ax:: is the namespace?

**Comment by DelinWorks** [comment]
No I mean like there are comments that contain the word `cocos2d` should we replace them?
The namespaces can be ax:: though

**Comment by halx99** [comment]
> Should we replace every source file that contains `cocos2d` with `axis`?

Yes

**Comment by aismann** [comment]
Maybe a new PR?

**Comment by halx99** [comment]
> Maybe a new PR?

Yes, needs seperate PR

**Comment by DelinWorks** [comment]
@halx99 should this be replaced with `ax` or `axis`?

![image](https://user-images.githubusercontent.com/45469625/178004602-356ea2ff-d482-44dc-8d18-eb7cee8c7711.png)

**Comment by halx99** [comment]
> @halx99 should this be replaced with `ax` or `axis`?
> 
> ![image](https://user-images.githubusercontent.com/45469625/178004602-356ea2ff-d482-44dc-8d18-eb7cee8c7711.png)

Yes, both axis or ax is ok for me, so maybe the original namespace is `axis`, then `ax` is abbv of it.

**Comment by DelinWorks** [comment]
yeah we can use `axis` as the main namespace and then shorten it with `namespace ax = ::axis;`

**Comment by DelinWorks** [comment]
@halx99 @aismann would this be a nice logo?

![image](https://user-images.githubusercontent.com/45469625/178131822-1c28dae1-c114-4157-9fa8-9f3ce4f26dda.png)

And the mini logo can be:

![image](https://user-images.githubusercontent.com/45469625/178131869-8bf4f0cb-a28e-4bd5-b9d7-00338447f467.png)

damn it's really hard thinking of a good icon. maybe the colors are a bit harsh?

**Comment by aismann** [comment]
Look good.
I will make small changes later.

**Comment by halx99** [comment]
Maybe the coord lines could be looks like perspective 45 degree

**Comment by DelinWorks** [comment]
> Looks good. I will make small changes later (only an example). ![image](https://user-images.githubusercontent.com/8652787/178137283-4a0a25e9-d828-4d20-9db3-7c1de28c7bae.png)

![image](https://user-images.githubusercontent.com/45469625/178148689-13975df4-73c9-4575-b14e-a5b2846071dc.png)

I like the pervious one because this one feels a bit off don't you think?

**Comment by DelinWorks** [comment]
> Maybe the coord lines could be looks like perspective 15/30/45 degree

It can be done with the power of 3D software 😎

**Comment by DelinWorks** [comment]
The big logo with the letter can stay is it as now but the mini logo can be 3D as @halx99 said

**Comment by DelinWorks** [comment]
@halx99 it doesn't look fitting with the 3D look to be honest

**Comment by DelinWorks** [comment]
> Maybe the coord lines could be looks like perspective 15/30/45 degree

It doesn't look right with the 3D look :/

**Comment by aismann** [comment]
> > Looks good. I will make small changes later (only an example). ![image](https://user-images.githubusercontent.com/8652787/178137283-4a0a25e9-d828-4d20-9db3-7c1de28c7bae.png)
> 
> ![image](https://user-images.githubusercontent.com/45469625/178149212-02046f00-528f-46ed-8ea1-f6df6d2f8b59.png)
> 
> I changed my mind it looks better now

Can you make an example with an lowercase i like: AXiS

**Comment by aismann** [comment]
> > Looks good. I will make small changes later (only an example). ![image](https://user-images.githubusercontent.com/8652787/178137283-4a0a25e9-d828-4d20-9db3-7c1de28c7bae.png)
> 
> ![image](https://user-images.githubusercontent.com/45469625/178149212-02046f00-528f-46ed-8ea1-f6df6d2f8b59.png)
> 
> I changed my mind it looks better now

Can you make an example with an lowercase i like: AXiS

**Comment by DelinWorks** [comment]
![image](https://user-images.githubusercontent.com/45469625/178156061-2a7727ab-65b3-4b95-85a5-33688b1249a7.png)

**Comment by aismann** [comment]
> ![image](https://user-images.githubusercontent.com/45469625/178156075-84e9540e-e90a-4ac5-98c7-19b0ca94a8e5.png)

Thanks. Looks not so good

**Comment by DelinWorks** [comment]
you mean the lowercase i or the whole design?

**Comment by aismann** [comment]
The wohl desing is good.
As longer I see the AXiS as more I like the lowercase i

**Comment by DelinWorks** [comment]
You mean closer?

**Comment by aismann** [comment]
Closer looks better.

**Comment by aismann** [comment]
Can you make the blue darker?

**Comment by DelinWorks** [comment]
which one? the one with the lowercase `i`?

**Comment by aismann** [comment]
> 
Yes. Only one is enough to see the look of the darker blue line

**Comment by aismann** [comment]
![image](https://user-images.githubusercontent.com/8652787/178466249-670d4e42-7aa7-480c-aa3a-24392d24c715.png)
Should we coloring the dot too?
maybe the blue border is to brightness

**Comment by DelinWorks** [comment]
![image](https://user-images.githubusercontent.com/45469625/178493818-bc10d6ae-04be-4d27-8f18-1449376e845d.png)

**Comment by aismann** [comment]
I like it!
I have no problem to write AXIS, axis, or AXiS, but the logo should having this lowercase "i".
Sources should have only lowercase or ax

**Comment by DelinWorks** [comment]
I think this looks better because mixed lowercase and uppercase letter look a bit weird

![image](https://user-images.githubusercontent.com/45469625/178787948-1907ef85-7aa0-4a28-93bd-454d93198dcb.png)

**Comment by aismann** [comment]
Also ok

**Comment by DelinWorks** [comment]
okay @halx99 what do you think?

The logos are:

![image](https://user-images.githubusercontent.com/45469625/178840853-ad5e71de-ec3d-4420-998e-04fe94fa50b0.png)

and the mini logo, I tried making it 3D but no matter what it just looks a bit off

![image](https://user-images.githubusercontent.com/45469625/178841274-acf27355-7a4a-4b5d-b116-72bf442740f1.png)

**Comment by halx99** [comment]
This draft is my idea:
![16577518301606701110973421307530](https://user-images.githubusercontent.com/6977319/178848884-798bc679-5103-4434-b195-5eb97de5a023.jpg)

**Comment by DelinWorks** [comment]
😮

**Comment by DelinWorks** [comment]
two designs that came up with idea

![image](https://user-images.githubusercontent.com/45469625/178850968-6f7677ee-6934-47bd-9b3e-06db05d63acf.png)

![image](https://user-images.githubusercontent.com/45469625/178851192-d8d7a2e1-4d89-4a2a-83c6-d1a26f9f3daf.png)

What do you think? of course It will be polished after it's chosen

**Comment by halx99** [comment]
I means reuse the longest line for A,X and S(if possible)

**Comment by DelinWorks** [comment]
Sorry I don't understand 😅 could you elaborate?

**Comment by DelinWorks** [comment]
[Untitled.zip](https://github.com/axis-project/axis/files/9107824/Untitled.zip)

Here is the Paint.net PDN file, tweak it based on your liking

**Comment by halx99** [comment]
How can I open the .pdn file?

**Comment by DelinWorks** [comment]
download Paint.net

**Comment by halx99** [comment]
![IMG_20220714_111441](https://user-images.githubusercontent.com/6977319/178890385-e6771541-2db0-4979-894d-8bd37ca7f3f4.jpg)

**Comment by DelinWorks** [comment]
> \>

😕 it looks a bit wanky and doesn't go with the axis xyz style, it looks like a frills design rather than before

**Comment by aismann** [comment]
macros: CC_ to AX_
 Remove source code file name prefix CC, such as CCFileUtils to FileUtils

I approve replace CC with AX on the file name.
look here as an example: why:
Without the 'CC' or new: 'AX' as an 'information on the filename, developer lose the information which 'kind of package' it is. (cp = Chipmunk2D, CC=Cocos2D)
Better remove the CC with AX  such as CCFileUtils to AXFileUtils
![image](https://user-images.githubusercontent.com/8652787/179153326-ecfaa52f-07ae-4704-9287-54ad184d1d87.png)

**Comment by halx99** [comment]
All in axis/core should be engine package

**Comment by aismann** [comment]
> All in axis/core should be engine package

cpCompat62.h has no CC and it is part of the core

**Comment by halx99** [comment]
Just keep it

**Comment by DelinWorks** [comment]
Wouldn't `axyz` be better? also, you're changing the engine's name amidst the migration which is kinda counter-productive and the work of replacement has to be done again. also I think `axis` is fit and a nice chang and `y` or `z` kinda ruin the name

**Comment by halx99** [comment]
Axys also axis, looks `Axys(Axis) Game Engine` in readme or docs files

**Comment by DelinWorks** [comment]
I think choosing one is a wise choice here because `Axys(Axis)` is confusing, everyone would think it's a typo.
Either choose `axis` or `axys`, but it's up to you, it can stay like that if you want.

**Comment by halx99** [comment]
Axys(aka. Axis) Game Engine good

**Comment by halx99** [comment]
Axys(aka. Axis) Game Engine good

**Comment by aismann** [comment]
> Axys(aka. Axis) Game Engine good

Right.
An  explanation about Axys (aka Axis) in the readme should be sufficient.

**Comment by DelinWorks** [comment]
Actually, all these names are confusing. we can stick to `axys` and leave the `axis` as it is and change it sometime soon, it would be `Axys Game Engine` and that's it! don't you think?

**Comment by qoozta** [comment]
I have a question about the new engine name, is it axys or axys1? I see axys1 is using in android package name.

**Comment by halx99** [comment]
axys1 is a temp org name

**Comment by aismann** [comment]
New idea (inspiration) for a "Logo" and an "Icon":

![image](https://user-images.githubusercontent.com/8652787/186139558-e134dd3b-c191-481f-aadc-43a070429477.png)
Icon:
![image](https://user-images.githubusercontent.com/8652787/186139636-c0eb4a1f-a647-4aa6-8c37-ccd600fab263.png)
Part of A, X and Y be smelt to one "letter" and thats is the icon.
More a startup as perfect (colors maybe also not really a good)

**Comment by aismann** [comment]
or this:
![image](https://user-images.githubusercontent.com/8652787/186142751-d06ced34-1575-456e-b5e1-9abc54d8a0c8.png)
Icon:
![image](https://user-images.githubusercontent.com/8652787/186142834-f39289b5-6372-4f31-b9b7-f27224990df8.png)

**Comment by aismann** [comment]
But anyhow:
I like this icon (I found no reason that have to looks like the logo): 
![image](https://user-images.githubusercontent.com/8652787/186143081-1d9473a8-fa09-40bf-8aea-7cfd49ed8561.png)

**Comment by aismann** [comment]
Another idea (as draft)  for the icon:
![image](https://user-images.githubusercontent.com/8652787/187364225-165490f6-dbf5-4381-99d6-06430bedb6d4.png)

**Comment by DelinWorks** [comment]
great logo! my logo is bad because it uses dark colors which makes it look like a flash game, how about we use a simple style, a gray black or gray light gray pallet? that would make sense

**Comment by DelinWorks** [comment]
or a gray and some other color like blue or something, the axis dont need to be colored after all

**Comment by aismann** [comment]
her another one (but found on internet (Copyright?))
![image](https://user-images.githubusercontent.com/8652787/187492096-cc6c93b1-3130-4239-8f1f-fe5b81471390.png)

**Comment by halx99** [comment]
> her another one (but found on internet (Copyright?)) ![image](https://user-images.githubusercontent.com/8652787/187492096-cc6c93b1-3130-4239-8f1f-fe5b81471390.png)

The logo looks good, it's already used by other?

**Comment by aismann** [comment]
> > her another one (but found on internet (Copyright?)) ![image](https://user-images.githubusercontent.com/8652787/187492096-cc6c93b1-3130-4239-8f1f-fe5b81471390.png)
> 
> The logo looks good, it's already used by other?

https://axys.mu/

**Comment by aismann** [comment]
Thats  my draft ;)
![image](https://user-images.githubusercontent.com/8652787/187609326-a9385378-c506-4e0b-a9ae-f98315f2be3a.png)

**Comment by aismann** [comment]
@halx99 
Maybe discussions board is the better place now.
Renaming the title also (Logo and Icon)

**Comment by paulocoutinhox** [comment]
None of this urls are working:
- https://adxeproject.github.io
- https://axis-project.github.io

**Comment by aismann** [comment]
I think it can be closed
No longer corosponding the actual situation
