### ISSUE TITLE
Websockets Support

### ISSUE THREAD

**Issue by theunwisewolf** [axmolengine/axmol#779]
Hi!
Why was libwebsockets support removed? What is the alternative?

**Comment by rh101** [comment]
You can add libwebsockets back into your project via CMakeList.txt, but it'll also need the uv library if I recall correctly.

I've personally been evaluating [IXWebSocket](https://github.com/machinezone/IXWebSocket), and it's been good so far.

**Comment by askamn** [comment]
I have already done that. I was asking so that I can open a PR for this.
@halx99

**Comment by paulocoutinhox** [comment]
+1

**Comment by aismann** [comment]
![image](https://github.com/axmolengine/axmol/assets/8652787/9c37e091-428d-4790-9722-fa2d1a333eeb)
@halx99 
It is part of the axmol-1.0 project?
So maybe it can closed here?
