### ISSUE TITLE
[bug] Some warnings and deprecations need be checked

### ISSUE THREAD

**Issue by paulocoutinhox** [axmolengine/axmol#842]
- axys version: dev branch
- devices test on: iPhone
- developing environments
   - Xcode version: 12.4
   - cmake version: 3.22
Steps to Reproduce:

1. create a project
2. create ios-build like docs with cmake
3. open axys.xcodeproj
4. build for any iOS device

### The launch is marked to build with iOS 7, but the project is for iOS 9

```
proj.ios_mac/ios/LaunchScreen.storyboard This file is set to build for a version older than the deployment target. Functionality may be limited.
```

Only need change here:
<img width="270" alt="image" src="https://user-images.githubusercontent.com/395096/188235531-666acc00-048c-4b11-ab0c-8dd9520d4ff4.png">

### Storyboard has an invalid reference

```
axys-proj1.build/LaunchScreen.storyboardc:1:1: Unable to validate Storyboard References for LaunchScreen.storyboard.
```

What is `LaunchScreen.storyboardc`?

### Wants full screen is deprecated:

In the code:

```
// Use RootViewController to manage CCEAGLView
_viewController                       = [[RootViewController alloc] init];
_viewController.wantsFullScreenLayout = YES;
```

```
'wantsFullScreenLayout' is deprecated: first deprecated in iOS 7.0
```

References:
- https://developer.apple.com/documentation/uikit/uiviewcontroller/1621390-wantsfullscreenlayout
- https://stackoverflow.com/questions/19190876/need-wantsfullscreenlayout-behavior-with-non-translucent-bars-on-ios-7

### Wants full screen is deprecated:

In the code:

```
[[UIApplication sharedApplication] setStatusBarHidden:true];
```

```
'setStatusBarHidden:' is deprecated: first deprecated in iOS 9.0 - Use -[UIViewController prefersStatusBarHidden]
```

### Integer precision loss

In the code:

```
for (int32_t i = strtol(cStr, &endptr, 10); endptr != cStr; i = strtol(cStr, &endptr, 10))
```

Change to:

```
for (auto i = strtol(cStr, &endptr, 10); endptr != cStr; i = strtol(cStr, &endptr, 10))
```

### All return types of AudioDecoder and AudioCache need be int64_t -  Convertion problems

In the code and others related:

```
uint32_t read(uint32_t framesToRead, char* pcmBuf); // file .h

uint32_t AudioDecoderOgg::read(uint32_t framesToRead, char* pcmBuf) // file .cpp
{
    int currentSection = 0;
    int bytesToRead    = framesToBytes(framesToRead);
    int32_t bytesRead  = ov_read(&_vf, pcmBuf, bytesToRead, 0, 2, 1, &currentSection);
    return bytesToFrames(bytesRead);
}
``` 

I change to int64_t and works.

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/395096/188237026-37c0b1f1-5efb-454a-a935-065ff8e3b5e6.png">

### TextFieldEx  - Convertion problems

In the code:

```
inline int getCharCount() const { return charCount; };
```

Change to:

```
inline size_t getCharCount() const { return charCount; };
```

Because `charCount` is `size_t`, not `int`.

### TextureML - Convertion problems

In the code:

```
auto bytesPerRow = PixelFormatUtils::computeRowPitch(_textureFormat, width);
```

Change to:

```
auto bytesPerRow = PixelFormatUtils::computeRowPitch(_textureFormat, static_cast<int32_t>(width));
```

### Other problems with number convertions

There is the same problems on some files:
- TGAlib.cpp
- RenderTargetMTL.mm
- xxsocket.hpp
- CommandBufferMTL.mm
- CCSpriteBatchNode.cpp
- CCPosixFileStream.cpp
- CCParticleStream.cpp
- CCMesh.cpp
- CCLabel.cpp
- CCImage.cpp
- CCImage-ios.mm
- CCFontFreeType.cpp
- CCFontFNT.cpp
- CCDownloader-curl.cpp
- UITextFieldEx.cpp
- TextureMTL.mm
- AudioDecoderOgg.cpp
- CCES2Renderer-ios.m
- CCCamera.cpp

### Some macro warnings

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/395096/188238125-8af23879-b043-4750-8c7f-cca4a67fbc70.png">

### Switch not cover all cases

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/395096/188238304-dce5989c-6bde-4ddb-b66c-a0f7e673a87d.png">

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/395096/188238394-06aa37d8-173b-4466-8a56-a75e3b4d6a55.png">

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/395096/188238416-c738a542-043f-4ac1-a6fb-00a5e2c437eb.png">

### Cocostudio

One deprecated line need be fixed:

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/395096/188238598-77c2189f-8f34-45cb-81d4-38a07130a824.png">

```
FLATBUFFERS_ATTRIBUTE(deprecated("call the version above instead"))
  uoffset_t EndTable(uoffset_t start, voffset_t /*numfields*/) {
    return EndTable(start);
}
```

The `above` method mentioned is:

<img width="321" alt="image" src="https://user-images.githubusercontent.com/395096/188238794-431c536c-e628-495d-a422-ae05b3c34e58.png">

### Conclusion

It cover all warning for C++, iOS and Axys things. It not cover external libraries itself.

I don't know how the governance and purpose of this project works, but I can help if you want.

**Comment by halx99** [comment]
Nice point, you can create a pr to fix these warnings.
