### ISSUE TITLE
async await

### ISSUE THREAD

**Issue by imtrobin** [axmolengine/axmol#87]
Hi, If you are modifying to latest C++, can consider await asynci instead of callbacks.

**Comment by halx99** [comment]
The await require c++20

**Comment by halx99** [comment]
- needs a coroutine queue to check them status and resume them
- should ensure coroutines resume on main thread

**Comment by halx99** [comment]
Possiable API:
- Director::getInstance()->startCoroutine
- Director::getInstance()->stopCoroutine
- Director::getInstance()->stopAllCoroutines

**Comment by aismann** [comment]
@halx99 
Can we reopen it?
Not for 1.0 Off course.

**Comment by aismann** [comment]
@halx99 
Plz add c++20 Label too

**Comment by halx99** [comment]
Yes, refer to: https://github.com/axmolengine/axmol/blob/dev/.github/stale.yml#L6

**Comment by aismann** [comment]
For the implementation (at the moment):
plz don't remove the C++17 part active (use compiler directive or so on )

**Comment by aismann** [comment]
@halx99:
Maybe it can be closed?
Because to the limits with Windows UWP (Visual Studio 2022), 
=> only support C++17

**Comment by halx99** [comment]
https://github.com/axmolengine/axmol/issues/1471
