### ISSUE TITLE
Physics3D Test in cpp-tests throws SIGABRT after fixing issue #861

### ISSUE THREAD

**Issue by cchuicchui** [axmolengine/axmol#873]
- axys version: Downloaded on 2022-09-29
- devices test on: iOS Simulator iPhone SE 15.5
- developing environments
   - NDK version: NA
   - Xcode version: 13.4.1
   - VS/msvctools version: NA
   - cmake version:  Latest
Steps to Reproduce:

Just downloaded axys compile cpp-tests then run Physics3D then move to test case 4
<img width="1389" alt="Screenshot 2022-09-29 at 9 21 05 PM" src="https://user-images.githubusercontent.com/39337211/193045578-c3987c0a-ada8-45ed-a03c-df23e5ceb27a.png">

Error message in xcode:

warning: bundle reader out of range
warning: Failed to read SkinData: boneNum  '/Users/cchui/Library/Developer/CoreSimulator/Devices/5D929E0A-EBC2-4DA5-93D2-D1B056A7685B/data/Containers/Bundle/Application/3E6B22E7-FADF-4305-8B57-F765F36579FC/cpp_tests.app/MeshRendererTest/boss.c3b'.
-[MTLDebugRenderCommandEncoder validateCommonDrawErrors:]:5252: failed assertion `Draw Errors Validation
Fragment Function(xlatMtlMain2): missing sampler binding at index 0 for _mtlsmp_u_tex0[0].
'
dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot DYLD_LIBRARY_PATH=/Users/cchui/cocos2d/axys-dev-20220929/build/lib/Debug:/Users/cchui/cocos2d/axys-dev-20220929/build/bin/cpp_tests/Debug:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMTLCapture.dylib DYLD_FRAMEWORK_PATH=/Users/cchui/cocos2d/axys-dev-20220929/build/lib/Debug:/Users/cchui/cocos2d/axys-dev-20220929/build/bin/cpp_tests/Debug
-[MTLDebugRenderCommandEncoder validateCommonDrawErrors:]:5252: failed assertion `Draw Errors Validation
Fragment Function(xlatMtlMain2): missing sampler binding at index 0 for _mtlsmp_u_tex0[0].
'
CoreSimulator 802.6.1 - Device: iPhone SE3 (5D929E0A-EBC2-4DA5-93D2-D1B056A7685B) - Runtime: iOS 15.5 (19F70) - DeviceType: iPhone SE (3rd generation)

**Comment by cchuicchui** [comment]
Also, all debug draw lines are corrupted even in test case 1-3
<img width="919" alt="Screenshot 2022-09-29 at 10 42 04 PM" src="https://user-images.githubusercontent.com/39337211/193062530-d4fa6d53-91bc-4c7d-9ec4-d4ce98f70fe0.png">

**Comment by cchuicchui** [comment]
Also, all debug draw lines are corrupted even in test case 1-3
<img width="919" alt="Screenshot 2022-09-29 at 10 42 04 PM" src="https://user-images.githubusercontent.com/39337211/193062749-ff5e7419-13e4-4ec5-bdbd-b6c708e21d69.png">

**Comment by cchuicchui** [comment]
I found that in Physics3DTest.cpp, if the following lines

         std::string boss[] = {"MeshRendererTest/boss.c3b",
                               "MeshRendererTest/boss.obj"};

are changed to

         std::string boss[] = {"MeshRendererTest/boss.c3b",
                               "MeshRendererTest/boss.c3b"};

SIGABRT will not be thrown.

In all cases, the debug draw lines (when DebugDraw ON) are still corrupted.

**Comment by halx99** [comment]
So metal require fill all attributes in vertex shader, and the boss.obj no attribute `a_normal`

**Comment by cchuicchui** [comment]
I replaced boss.obj by sphere2.obj (with normal), it works.
I replaced boss.obj by sphere3.obj (without normal), it works as well.
[sphere-files.zip](https://github.com/axmolengine/axmol/files/9676350/sphere-files.zip)
