### ISSUE TITLE
axmol.bat is missing

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#878]
- axmol version:
- devices test on:
- developing environments
   - NDK version: r19c
   - Xcode version: 12.4
   - VS/msvctools version: Visual Studio 2019(16.11)/14.29.30133
   - cmake version: 
Steps to Reproduce:

1. 
2.

**Comment by halx99** [comment]
Fixed by https://github.com/axmolengine/axmol/commit/2eea90545de41c02581c1c4c58598b0424bf2981
