### ISSUE TITLE
Sprite3D does not handle model with transparency

### ISSUE THREAD

**Issue by cchuicchui** [axmolengine/axmol#879]
- axmol version: Downloaded in 2022-09-29
- devices test on: iOS Simulator
- developing environments
   - NDK version: NA
   - Xcode version: 13.4.1
   - VS/msvctools version: NA
   - cmake version:  NA
Steps to Reproduce:

1.  Modify Physics3DKinematicDemo::init to add the code after line 310:

    floor->setSyncFlag(Physics3DComponent::PhysicsSyncFlag::NONE);

New code:

    // static object sync is not needed
    floor->setSyncFlag(Physics3DComponent::PhysicsSyncFlag::NONE);

    // NEW CODE STARTS BELOW
    {
        Physics3DRigidBodyDes rbDes;

        float scale = 12.0f;
        std::vector<Vec3> trianglesList = Bundle3D::getTrianglesList("MeshRendererTest/tree1.obj");
        for (auto& it : trianglesList) {
            it *= scale;
        }

        rbDes.mass = 0.0f;
        rbDes.shape = Physics3DShape::createMesh(&trianglesList[0], (int)trianglesList.size() / 3);
        auto rigidBody = Physics3DRigidBody::create(&rbDes);
        auto component = Physics3DComponent::create(rigidBody);
        auto sprite = Sprite3D::create("MeshRendererTest/tree1.obj");
        sprite->addComponent(component);
        sprite->setPosition3D(Vec3(20.0f, 0.0f, 0.0f));
        sprite->setScale(scale);
        sprite->setCameraMask((unsigned short)CameraFlag::USER1);
        this->addChild(sprite);
    }
    // NEW CODE ENDS HERE

    // create Kinematics
    for (unsigned int i = 0; i < 3; ++i)

2.  Add the files into tests/cpp-tests/Resources/MeshRendererTest:

[tree-model.zip](https://github.com/axmolengine/axmol/files/9691936/tree-model.zip)

3. Run test on Physical3D at test case 3:

<img width="912" alt="Screenshot 2022-10-02 at 3 11 23 PM" src="https://user-images.githubusercontent.com/39337211/193442498-c1212515-6238-4e45-8c66-a659b1829f63.png">

4. I tested the same changes in 3.17.2 and transparency is shown properly:

<img width="918" alt="Screenshot 2022-10-02 at 3 12 55 PM" src="https://user-images.githubusercontent.com/39337211/193442530-72b6fea4-376b-4e7a-8bc2-fe42f4177df1.png">

NB: Seems that a lot of things crashes since porting to Apple Metal.

Please help to fix.

**Comment by aismann** [comment]
> 4. I tested the same changes in 3.17.2 and transparency is shown properly:
Works with Cocos2d-x-4.0?

>Seems that a lot of things crashes since porting to Apple Metal.
only ios bug?

**Comment by cchuicchui** [comment]
It fails with Cocos2d-x-4.0 as well.

My current setup does not support installing in real iOS devices. Is there any setup of cpp-tests such that I can both compile and run in iOS simulator and iOS real devices in one project?

**Comment by cchuicchui** [comment]
I tried to convert tree1.obj to tree1.fbx (using blender) then convert to tree1.c3t and replaced the obj file to c3t file but nothing is displayed at all.

So the problem is not just relevant to obj file only.

**Comment by halx99** [comment]
does it works on windows? I have no Mac on my hand to check this issue.

**Comment by cchuicchui** [comment]
Sorry I don't have Windows on hand...

**Comment by aismann** [comment]
Im on it

**Comment by aismann** [comment]
Same on windows. 
![image](https://user-images.githubusercontent.com/8652787/193448074-dcd12b7b-a245-4be7-8a13-dce101c4fdb9.png)

**Comment by aismann** [comment]
@cchuicchui 
The 'tree-model.zip' content is free?
I want add it to the resource part of test-cpp

**Comment by cchuicchui** [comment]
> @cchuicchui The 'tree-model.zip' content is free? I want add it to the resource part of test-cpp

Yes, it is free

**Comment by halx99** [comment]
I can confirm, it caused by incorrect blendState set, I have enableBlend for Mesh, then the render result seems correct:

<img width="470" alt="image" src="https://user-images.githubusercontent.com/6977319/193455567-2e0b2ec2-9f30-4bff-b3b3-f0292ff415fb.png">

**Comment by cchuicchui** [comment]
> I can confirm, it caused by incorrect blendState set, I have enableBlend for Mesh, then the render result seems correct:
> 
> <img alt="image" width="470" src="https://user-images.githubusercontent.com/6977319/193455567-2e0b2ec2-9f30-4bff-b3b3-f0292ff415fb.png">

What is the code you used? Can you post here?

**Comment by halx99** [comment]
The code is:
```cpp
void Mesh::bindMeshCommand()
{
    if (_material && _meshIndexData)
    {
        _material->getStateBlock().setCullFace(true);
        _material->getStateBlock().setDepthTest(true);
        _material->getStateBlock().setBlend(true);
    }
}
```

**Comment by aismann** [comment]
works better now:
but not realy transparent (see red circle)
![image](https://user-images.githubusercontent.com/8652787/193457974-5cb80d0d-a42d-4639-9109-adcc655ae15b.png)

**Comment by aismann** [comment]
Maybe the title of this issue)  is also little bit wrong

**Comment by cchuicchui** [comment]
Many of the leaves are missing. When I view the model in blender:
<img width="420" alt="Screenshot 2022-10-02 at 10 13 01 PM" src="https://user-images.githubusercontent.com/39337211/193458581-3497f690-32ce-44dd-a7fb-e0ed45eaa5d5.png">

**Comment by halx99** [comment]
Yes, should be other some things incorrect.

**Comment by aismann** [comment]
> Many of the leaves are missing. When I view the model in blender: <img alt="Screenshot 2022-10-02 at 10 13 01 PM" width="420" src="https://user-images.githubusercontent.com/39337211/193458581-3497f690-32ce-44dd-a7fb-e0ed45eaa5d5.png">

@cchuicchui 
Can you create a c3t from the tree?

**Comment by cchuicchui** [comment]
Same result:
<img width="909" alt="Screenshot 2022-10-03 at 12 25 57 AM" src="https://user-images.githubusercontent.com/39337211/193465116-a9a78838-5ec7-4b07-a5d2-6d58dfbd6b5f.png">

The c3t generated is attached here:
[tree-model2.zip](https://github.com/axmolengine/axmol/files/9692993/tree-model2.zip)

**Comment by cchuicchui** [comment]
I think the problem here is the faces constituting the leaves are overlapping. So if the tree is rendered in the order of face, the result will be wrong.

In order to be rendered correctly, the overlapping faces must be broken down into non-overlapping faces before the sorting of the draw order of the non-overlapping faces.

On the other hand, is there any export option such that we can perform this break-down when we export the model?

**Comment by cchuicchui** [comment]
Would the problem be the overlapping of faces constituting the leaves?

**Comment by DelinWorks** [comment]
Have you tried calling `sprite->getMaterial(0)->setTransparent(true)` on it? because the transparency functionality has been moved to materials themselves

**Comment by aismann** [comment]
> sprite->getMaterial(0)->setTransparent(true)

@DelinWorks 
the code gets crashing

**Comment by DelinWorks** [comment]
I'll see what i can do on my end

**Comment by solan-solan** [comment]
The transparent objects should be sorted base on distance to the camera, since they renders with _depth write function_ disabled. But it is imposible to do when you draw tree leaves which are _intertwined_ with each other.
It is better to apply 'alpha test' in the _fragment shader_ in this case:
```
if (pixel.a < 0.5)
    discard;
```

**Comment by cchuicchui** [comment]
I think twice. Even the incorrect rendering result should not result in less leaves if your drawing of transparency pixels is additive. The leaves in the back should not be covered by background

**Comment by cchuicchui** [comment]
And to solve the overlap polygon, we may break the polygons into smaller polygons based on their intersections. This will eliminate all overlapping polygons and you may not need to change the shader at all

**Comment by solan-solan** [comment]
> The leaves in the back should not be over-drawn by background

You are right. May be _depth write function_ is enabled for some reason, and foreground polygons was rendered firstly. It could be if _render command_ was not placed to _opaque transparent render queue_, as example

> And to solve the overlap polygon, we may break the polygons into smaller polygons based on their intersections

Do you suggest to break polygons on background and foreground along the intersection lines, then draw them in the sorted order? To my understand it is not simple task for the engine. I doubt that even Unity has this feature from scratch

**Comment by aismann** [comment]
Only an idea:
Is the tree correct shown on Unity?

**Comment by halx99** [comment]
import the model to unity scene, and the results:

<img width="737" alt="image" src="https://user-images.githubusercontent.com/6977319/194271312-63a75e8b-a380-444e-b561-a00ad29e9f0d.png">

**Comment by solan-solan** [comment]
Looks like common blending with depth write disabled.

And I do not see that there is polygon sorting exists. Fix me if I wrong, but farther polygon is rendered after nearer polygon in the red square on the picture:
![image](https://user-images.githubusercontent.com/73186496/194284910-1c95c095-78ad-46e6-8e91-156f69e33542.png)

**Comment by cchuicchui** [comment]
Is something missing here?
<img width="737" alt="tree" src="https://user-images.githubusercontent.com/39337211/194372323-580dd1a3-418d-4190-8faa-e9c9712b22e7.png">

**Comment by cchuicchui** [comment]
Originally I was trying to look for a low-poly tree that is "real" enough. After some searching, this tree model is good looking yet with minimum number of faces.

If my purpose is just to find some good looking trees and put into my world, is there any other tree models that work in Axmol?

**Comment by solan-solan** [comment]
`Is something missing here?`

![image](https://user-images.githubusercontent.com/73186496/194401724-54c06c04-10f9-41a9-a52a-4d251d1a8c3f.png)

I believe that you can render good-looking tree if you apply custom fragment shader with proposed technicians (it would be better to get one of Axmol fragment shaders and add upper lines with _discard_. cpp_test will show how to create custom material).

But I really do not understand why depth write is not disabled while common transparent with blending renders. It looks bug anyway

**Comment by solan-solan** [comment]
I have got the following:
![image](https://user-images.githubusercontent.com/73186496/194563294-4b2066f5-4d7d-477e-86ff-bfa3464c9eed.png)

with this code:

```
auto sprite = Sprite3D::create("res/test/tree1.obj");
sprite->setPosition3D(Vec3(0.0f, 0.0f, 0.0f));
static_cast<Sprite3D*>(sprite->getChildren().at(1))->getMaterial(0)->setTransparent(true);
static_cast<Sprite3D*>(sprite->getChildren().at(1))->getMaterial(0)->getStateBlock().setCullFaceSide(CullFaceSide::NONE);
sprite->setScale(10.f);
sprite->setCameraMask((unsigned short)CameraFlag::USER1| (unsigned short)CameraFlag::USER2| (unsigned short)CameraFlag::USER3);
this->addChild(sprite);
```

And you need to add the following change in the Axmol engine:
![image](https://user-images.githubusercontent.com/73186496/194564187-b634328a-7918-4093-b1e2-1aefacb2f504.png)

But leaf polygons are not sorted, you need use _above_ aproach to avoid this

**Comment by aismann** [comment]
I get this now
![image](https://user-images.githubusercontent.com/8652787/194571260-7a8014d5-e12e-4558-8b13-9577a70f1b46.png)

**Comment by aismann** [comment]
Maybe not really a bug...more a wrong cpp-tests code issue?
@halx99 
should we change the labels and add cpp-test ?

**Comment by aismann** [comment]
@cchuicchui , @solan-solan  @DelinWorks  @halx99 ,
can we close it? 

What about this line  (I dont add it)?
CCMeshRenderer.cpp  `material->setTransparent(oldmaterial->isTransparent()); `

@cchuicchui  
Maybe a second obj for stable tests code will be nice?

**Comment by solan-solan** [comment]
@aismann 
`CCMeshRenderer.cpp is the old one (without: material->setTransparent(oldmaterial->isTransparent()); )`

This thing is needed if you use _light_ in the scene. The shader will be recreated in the code
![image](https://user-images.githubusercontent.com/73186496/194589349-f1c90e06-0bea-4bfb-a15c-e86233f0a887.png)

I have light in my scene and transparent is not copied to the new material without that line

**Comment by aismann** [comment]
@cchuicchui , @solan-solan @DelinWorks @halx99 ,
Have a look on it and than: 
Please give for closing a "Yes close it" ;)

**Comment by halx99** [comment]
lgtm

**Comment by solan-solan** [comment]
I think it is ready now!

**Comment by cchuicchui** [comment]
Should we set transparency as default?

What is the overhead if we set this to default? Or is there any disadvantage if we set this to default?

**Comment by aismann** [comment]
> Should we set transparency as default?
> 
> What is the overhead if we set this to default? Or is there any disadvantage if we set this to default?

It's more a (new) discussion not an issue.

**Comment by cchuicchui** [comment]
Yes, this issue is resolved. Thanks all for your hard work!
