### ISSUE TITLE
C++ 20 compile support

### ISSUE THREAD

**Issue by crazyhappygame** [axmolengine/axmol#886]
**Is your feature request related to a problem? Please describe.**
Do you plan to switch to C++20 by default?
C++ 20 is fully support on all platforms.
C++ 20 will make engine more attractive for new technology nerds.

**Describe the solution you'd like**
C++ by default in all GitHub actions 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by aismann** [comment]
I think it will come (after the 1.0 release)

**Comment by crazyhappygame** [comment]
@aismann thank you!
When 1.0 release is planned?

**Comment by halx99** [comment]
I have test `cmake -B build -DCXX_STD=20` on windows with vs 2022, the build works.

**Comment by aismann** [comment]
> 

@halx99 
Should axmol switch to c++ 20 with 1.0 or later?

**Comment by halx99** [comment]
Maybe we can switch

**Comment by aismann** [comment]
> Maybe we can switch

Do it 👍

**Comment by halx99** [comment]
Or maybe wait c++23, the c++20 still have some feature not implementd, such as the `at`, `operator[]` of `map,set` containers still doesn't support heterogeneous lookup.

**Comment by aismann** [comment]
I think we can use what exist. Not what will come
C++20 is realy a big feature.
axmol should not use all new features in time. But User can use the features in own projects.

**Comment by aismann** [comment]
Use in readme for win64 should be enough:
`cmake -S . -B build -G "Visual Studio 20 2022" -A x64`

**Comment by aismann** [comment]
we can add this lines for C++ (Windows) on readme.md
`cmake  -B build_C++20 -DCXX_STD=20 -G "Visual Studio 17 2022" -A Win32`
`cmake  -B build_C++20 -DCXX_STD=20 -G "Visual Studio 17 2022" -A x64`

**Comment by aismann** [comment]
@halx99 
Please add support for all other OS  (Im not cmake guru)

**Comment by crazyhappygame** [comment]
Agree. If we switch to C++20 we should do this for all platforms.

**Comment by aismann** [comment]
> Agree. If we switch to C++20 we should do this for all platforms.

Of course. Neverone goes alone if there a solution for all ;)

**Comment by halx99** [comment]
> Agree. If we switch to C++20 we should do this for all platforms.

let's github ci help us to check it

**Comment by aismann** [comment]
@halx99 
Is it possible to change the color of cpp20? Its Look Like bug ;)

**Comment by aismann** [comment]
@halx99 
Please adapt the description of axmol too:
... C++17/20....

**Comment by halx99** [comment]
> @halx99 Is it possible to change the color of cpp20? Its Look Like bug ;)

done

**Comment by aismann** [comment]
@halx99 
I think it can be closed.
All steps on the way or done.

**Comment by halx99** [comment]
But other platforms not check yet

**Comment by aismann** [comment]
> 

OK. And the axmol description hast only c++17 as text

**Comment by halx99** [comment]
I create a PR #890 to help us check cpp20 compilings at all platforms

**Comment by aismann** [comment]
> I create a PR #890 to help us check cpp20 compilings at all platforms

It it works this line on readme can be adapt and maybe closing this issue too.
`C++ 17/20 (C++20 VS2022 64bit Windows 11 tested)` to `C++ 17/20`

**Comment by aismann** [comment]
> It looks like only windows compiled for c++20. Please check #890

It's know. Thanks.

**Comment by aismann** [comment]
@halx99 
Good work!
