### ISSUE TITLE
Test 57 Shader - Sprite crash on iOS.

### ISSUE THREAD

**Issue by qoozta** [axmolengine/axmol#887]
- axmol version: 6e23db3
- devices test on: iPhone SE 2nd gen iOS 16
- developing environments
   - Xcode version: 14.0.1

Steps to Reproduce:
1. Generate cpp_tests project.
2. Run in Xcode.
3. Go to Test 57: Shader - Sprite

> Can not create renderpipeline state: Error Domain=AGXMetalA13 Code=3 "Function requires stage_in attributes but no descriptor was set." UserInfo={NSLocalizedDescription=Function requires stage_in attributes but no descriptor was set.}
-[MTLDebugRenderCommandEncoder setRenderPipelineState:]:1586: failed assertion `Set Render Pipeline State Validation
renderPipelineState must not be nil.
'

Crashing line in CommandBufferMTL.mm:
`[_mtlRenderEncoder setRenderPipelineState:_renderPipelineMTL->getMTLRenderPipelineState()];`

**Comment by aismann** [comment]
Works on windows.
@halx99 
Please add label :
platform ios
