### ISSUE TITLE
Dear ImGui:  v1.88 released:   https://github.com/ocornut/imgui/releases/tag/v1.88

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#895]
v1.88 [Latest](https://github.com/ocornut/imgui/releases/latest)

@[ocornut](https://github.com/ocornut) ocornut released this Jun 21, 2022
1.88: Summer maintainance release!

**Comment by aismann** [comment]
No time.

**Comment by paulocoutinhox** [comment]
???
