### ISSUE TITLE
Improve Checklist before requesting a review

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#897]
![IMG_20221005_210433](https://user-images.githubusercontent.com/8652787/194141910-7832d91e-714a-4372-93ea-88090f491439.jpg)

[ ] I have checked readme and add important infos to this PR (if it needed). 

[ ] An improved cpp-test/lua-test is not needed (plz explain why not, thanks)

**Comment by halx99** [comment]
you can edit this file: https://github.com/axmolengine/axmol/blob/dev/.github/pull_request_template.md
