### ISSUE TITLE
"Start AutoTest" crashes on UIScale9SpriteTests

### ISSUE THREAD

**Issue by crazyhappygame** [axmolengine/axmol#908]
- axmol version: commit 6220071b3bd6937556b3c5cb5bf6ea66a289fcec
- devices test on: Windows
- developing environments
   - NDK version: r19c
   - Xcode version: 12.4
   - VS/msvctools version: Visual Studio 2022 17.3.1
   - cmake version: 
Steps to Reproduce:

1. Compile cpp-test debug version on MVSC 2022
2. Press "Start AutoTest"
3. wait for tests UIScale9SpriteTests
4. Crash (null pointer)

![image](https://user-images.githubusercontent.com/13263288/194748060-1f212964-6c9b-4877-a7b3-f22677b2c2cd.png)

**Comment by aismann** [comment]
Works Test without Autotest?

**Comment by crazyhappygame** [comment]
Without AutoTest fails as well

**Comment by aismann** [comment]
@crazyhappygame 
Maybe the title ist wrong ?

**Comment by aismann** [comment]
![image](https://user-images.githubusercontent.com/8652787/194775773-2e584f61-9f65-4b62-98c6-3ff0fa9c962b.png)

**Comment by crazyhappygame** [comment]
Similar issue exist for UIImageViewIssue12249Test

Can we fix in the scope of this issue all tests?
![image](https://user-images.githubusercontent.com/13263288/195093178-0ded5673-c4c7-4cf6-93f0-85752280d032.png)
