### ISSUE TITLE
Unknown CMake command "target_precompile_headers". 

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#911]
Deleted axmol folder.
clone it again (all new, no old stuff on it)

`cmake -S . -B build_64 -G "Visual Studio 16 2019" -A x64`

-- Including Win32 support
-- AX_USE_ALSOFT=
CMake axmol target_precompile_headers
****CMake Error at** core/CMakeLists.txt:161 (target_precompile_headers):
  Unknown CMake command "target_precompile_headers".**

**Comment by halx99** [comment]
which your cmake version?

**Comment by halx99** [comment]
Maybe @crazyhappygame can help to take a look.

**Comment by aismann** [comment]
D:\_____GitHub___\_aismann\axmol>cmake -version
cmake version 3.15.0

**Comment by aismann** [comment]
> target_precompile_headers is available starting from cmake 3.16. could you update cmake Version?

@crazyhappygame 
Please update readme also

**Comment by aismann** [comment]
Updateted:
D:\_____GitHub___\_aismann\axmol>cmake -version
cmake version 3.24.2

generated:
axmol.sln

but:
CMake Error in tests/cpp-tests/CMakeLists.txt:
  Unable to resolve full path of PCH-header
  'D:/_____GitHub___/_aismann/axmol/build_64/engine/axmol/core/CMakeFiles/axmol.dir/RelWithDebInfo/cmake_pch.h'
  assigned to target cpp_tests, although its path is supposed to be known!

**Comment by aismann** [comment]
Compiling:  VS2019
11>D:\_____GitHub___\_aismann\axmol\tests\cpp-tests\Classes\ChipmunkTestBed\ChipmunkTestBed.cpp : error C2855: command-line option '/Z7' inconsistent with precompiled header

>D:\_____GitHub___\_aismann\axmol\tests\cpp-tests\Classes\ChipmunkTestBed\ChipmunkTestBed.cpp : fatal error C1903: unable to recover from previous error(s); stopping compilation
11

**Comment by aismann** [comment]
works with cmake update
