### ISSUE TITLE
VS2019/22 DEBUG :  error C2855: command-line option '/Z7' inconsistent with precompiled header

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#913]
Compiling: VS2019 64bit DEBUG  (372 errors like below)

11>D:__GitHub_aismann\axmol\tests\cpp-tests\Classes\ChipmunkTestBed\ChipmunkTestBed.cpp : error C2855: command-line option '/Z7' inconsistent with precompiled header

D:__GitHub_aismann\axmol\tests\cpp-tests\Classes\ChipmunkTestBed\ChipmunkTestBed.cpp : fatal error C1903: unable to recover from previous error(s); stopping compilation

**Comment by aismann** [comment]
I got also this:

CMake Error in tests/cpp-tests/CMakeLists.txt:
Unable to resolve full path of PCH-header
'D:/__GitHub/_aismann/axmol/build_64/engine/axmol/core/CMakeFiles/axmol.dir/RelWithDebInfo/cmake_pch.h'
assigned to target cpp_tests, although its path is supposed to be known!

**Comment by halx99** [comment]
same with you vs2022

**Comment by aismann** [comment]
> same with you vs2022
@halx99 
Why ist the Check-in Not failed?

**Comment by halx99** [comment]
I have no idea yet

**Comment by aismann** [comment]
> I have no idea yet

not a new (clean) build an every checkin?

**Comment by halx99** [comment]
No, it's clean build
