### ISSUE TITLE
VS2019 RELEASE: I got this: (mostly Chipmunk testbed only): Cannot open precompiled header file: '.pch': No such file or directory

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#914]
in release mode I got this: (mostly Chipmunk testbed )
Severity Code Description Project File Line Suppression State
Error C1083 Cannot open precompiled header file: '.pch': No such file or directory cpp_tests D:__GitHub_aismann\axmol\tests\cpp-tests\Classes\ChipmunkTestBed\demo\Chains.c 1

**Comment by halx99** [comment]
same issue: #913
