### ISSUE TITLE
Generic C++ code quality improvements (Long Terms Dev Plan)

### ISSUE THREAD

**Issue by halx99** [axmolengine/axmol#915]
- [ ] vector use, and alloc for overwrite(alloc without zero fill), #916

**Comment by aismann** [comment]
maybe label 'pinned' is useful

**Comment by aismann** [comment]
@halx99,
C++ code quality improvements is an always/permanent issue.

Whith this knowledge, this issue can be closed (its not an "its done" issue one one date). 
Improvements will be always activ.
