### ISSUE TITLE
cmake file does not include rapidjson

### ISSUE THREAD

**Issue by chadwyk** [axmolengine/axmol#925]
- axmol version:1
- devices test on: MacOS M1
- developing environments
   - NDK version: r19c
   - Xcode version: 12.4
   - VS/msvctools version: Visual Studio 2019(16.11)/14.29.30133
   - cmake version: 3.24.2
Steps to Reproduce: 

1. The library exists in the third party folder, however it isn't in the cmake file, so it doesn't get copied to the project when running cmake -S . -B build -GXcode -DCMAKE_OSX_ARCHITECTURES=arm64

**Comment by halx99** [comment]
Don't need, rapidjson is header only library

**Comment by aismann** [comment]
for using see :
[axmol](https://github.com/axmolengine/axmol/tree/7e1481224089c036c1778cb7ee7b1ecf1f00f69e)/[tests](https://github.com/axmolengine/axmol/tree/7e1481224089c036c1778cb7ee7b1ecf1f00f69e/tests)/[performance-tests](https://github.com/axmolengine/axmol/tree/7e1481224089c036c1778cb7ee7b1ecf1f00f69e/tests/performance-tests)/[Classes](https://github.com/axmolengine/axmol/tree/7e1481224089c036c1778cb7ee7b1ecf1f00f69e/tests/performance-tests/Classes)/Profile.cpp
