### ISSUE TITLE
Compile error in linux

### ISSUE THREAD

**Issue by Joilnen** [axmolengine/axmol#933]
- axmol version: 32b0c2a07bd926f8217328602349af5cbb1cbbf2
- devices test on: x86_64

[error.txt](https://github.com/axmolengine/axmol/files/9846047/error.txt)

**Comment by halx99** [comment]
What your detial compiler version and linux edition? please check we are official support ubuntu 1804+, and the latest ci check is passed: https://github.com/axmolengine/axmol/actions/runs/3306278316

**Comment by Joilnen** [comment]
I am using archlinux and I can fix this changing axmol cmake to use c++17 instead c++20, maybe this last one is not complete compatible with the code of Vector in CCVector.h
