### ISSUE TITLE
Android stuck partial wake locks - AudioMix

### ISSUE THREAD

**Issue by qoozta** [axmolengine/axmol#935]
- axmol version: f1d31a1
- devices test on: LG G6
- developing environments
   - NDK version: r23
   - Android Studio Dolphin | 2021.3.1 Patch 1
   - cmake version: 3.23.2

It shows on Google Play vital details, after replacing cocos2d-x engine with axmol (axis / axys), this battery impact start showing up. Affected session is < 1% though.

![Screenshot 2022-10-26 at 09 16 25](https://user-images.githubusercontent.com/19526933/197912211-8d2ab240-f18a-4db3-83f6-ab26f7e10485.png)

**Comment by halx99** [comment]
The `openal` support two backends `opensl, oboe` on android platform, which backend do you use?

**Comment by qoozta** [comment]
> The `openal` support two backends `opensl, oboe` on android platform, which backend do you use?

How to check it? I'm using all default settings.

**Comment by halx99** [comment]
You can check the cmake output, default should be `OpenSL`

**Comment by qoozta** [comment]
> You can check the cmake output, default should be `OpenSL`

I found in CMakeCache.txt, so using OpenSL.

//Enable OpenSL backend
ALSOFT_BACKEND_OPENSL:BOOL=ON

//The Oboe include directory
OBOE_INCLUDE_DIR:PATH=OBOE_INCLUDE_DIR-NOTFOUND

//The Oboe library
OBOE_LIBRARY:FILEPATH=OBOE_LIBRARY-NOTFOUND

//Source directory for Oboe.
OBOE_SOURCE:STRING=

**Comment by aismann** [comment]
@qoozta,
Have you a example for reproducing?
How can I use Google Play vital details?

**Comment by qoozta** [comment]
> @qoozta,
> Have you a example for reproducing?
> How can I use Google Play vital details?

Sorry, I cannot provide an example because the apps are already on Play Store for sale.
You can login to Google Play Console > select the app > Quality > Android Vitals > Overview, then scroll down and select Battery.
We have multiple apps change from Cocos2dx-4 to Axmol all having the same vitals report.

**Comment by halx99** [comment]
Latest replace android audio backend from `OpenSL` to `oboe` for `openal-soft`, you can try it.

And a question: what the android version have this vitals report on your google play dashbaord?

**Comment by qoozta** [comment]
> Latest upstream replace android audio backend from `OpenSL` to `oboe` for `openal-soft`, you can try it.
> 
> And a question: what the android version have this vitals report on your google play dashbaord?
I will have a try on the latest commit.
As for the android version it mainly affect Android 8 and 9.
![Screenshot 2023-02-27 at 11 47 27](https://user-images.githubusercontent.com/19526933/221469333-609a9ab9-7de3-4e05-a87f-4e58df762b7f.png)

**Comment by halx99** [comment]
The `oboe` will use AAudio on android 8+ devices
