### ISSUE TITLE
Memory mapped UserDefaults binary file contains multiple entries for same field

### ISSUE THREAD

**Issue by rh101** [axmolengine/axmol#940]
- axmol version: Dev branch, https://github.com/axmolengine/axmol/tree/70770d86167f658d219b6bbc4bf7c1feab05da9a
- devices test on: All
- developing environments
   - NDK version: r19c
   - Xcode version: 12.4
   - VS/msvctools version: Visual Studio 2019(16.11)/14.29.30133
   - cmake version: 
Steps to Reproduce:

1. Call `UserDefault::getInstance()->setFloatForKey("SettingName", 1);` multiple times. The "SettingName" config value will be written the same number of times to the `UserDefault.bin` memory mapped file.  

![image](https://user-images.githubusercontent.com/8603230/198507024-2088f04e-952e-492e-9cea-6a7e4657837d.png)

It has nothing to do with the float value, but rather with the way the `setStringForKey` works. It doesn't check if the key already exists prior to writing it out to the memory mapped file. 

It doesn't actually cause any major issue except for constantly increasing the size of the `UserDefaults.bin` once it gets past each page size (4kbytes per page?).  The reason it works fine is because the last value saved to the memory mapped file will always be the one used, so it's not a critical issue.

**Comment by halx99** [comment]
It by designed, once buffer used by entries(include duplicate) archive to curMapSize, will call flush to tidy entries, the duplicate entiries will removed and the map file used size will be decrease.

**Comment by rh101** [comment]
Fair enough, then this is a non-issue. Thank you for the clarification on how it works.
