### ISSUE TITLE
Extension issue - FairyGUI BMFont don't load

### ISSUE THREAD

**Issue by theSlyest** [axmolengine/axmol#972]
- axmol version: release [40e7b2cee7]
- devices test on: iOS Simulator, Samsung J5 Pro
- developing environments
   - NDK version: r23c
   - Xcode version: 14.1
   - cmake version: 

Steps to Reproduce:
1. Create a FairyGUI project
2. Import a bitmap font in the FairyGUI project
3. Use the font on a text field in a FairyGUI component
4. Load the component in a scene

The the text field does not display the selected font, and there is an error message in the console log: 
> No file found at ui://[_fairygui_url_]. Possible missing file.

**Comment by aismann** [comment]
Source snippet?

**Comment by theSlyest** [comment]
```
bool HelloWorld::init() {
    if (!Scene::init()) 
    {
        return false;
    }

    _groot = GRoot::create(this);
    _groot->retain();

    FileUtils::getInstance()->addSearchPath("fui");
    UIPackage::addPackage("Futura_White_Black_128");
    UIPackage::addPackage("HexGrid");
    GObject *grid = UIPackage::createObject("HexGrid", "HexGrid");
    grid->setPosition(_groot->getWidth() / 2.f, _groot->getHeight() / 2.f);
    _groot->addChild(grid);

    return true;
}
```

**Futura_White_Black_128** is a bitmap font. There is a text field using this font in the **HexGrid** component. The component is displayed, but the text field appears with a wrong font and I get the following message:
> axmol: fullPathForFilename: No file found at ui://6jswxvktmvpka. Possible missing file.

**Comment by aismann** [comment]
Where is this font (path correct)?

**Comment by theSlyest** [comment]
It is not the issue. This glitch is also present in the fairguy demo.

**Comment by aismann** [comment]
Wich fargui test?

**Comment by theSlyest** [comment]
axmol/tests/fairyguitest-tests

**Comment by aismann** [comment]
Which one please.

**Comment by aismann** [comment]
@halx99:
maybe a label like:
'extension issue' is also helpfully?

**Comment by aismann** [comment]
It seems to be a FairyGUI bug (see preview)
I checked it on the editor:
![image](https://user-images.githubusercontent.com/8652787/204555365-4fe4dd83-c9de-4f59-9194-8b8b47637458.png)
Here the preview on the editor (Bitmap Font is not correct)
![image](https://user-images.githubusercontent.com/8652787/204555278-207846bc-f47c-4e21-b3f1-93b11e607718.png)

**Comment by theSlyest** [comment]
I just ran it with Cocos2d-x 4.0 and it works perfectly fine. So I think the glitches are caused by some of the changes in FontAtlasCache or FileUtils.

**Comment by aismann** [comment]
@theSlyest 
maybe the title is wrong?

**Comment by rh101** [comment]
@theSlyest Any chance you could try to re-add the code removed in this commit and see if it works correctly? 

https://github.com/axmolengine/axmol/commit/6f4fe63208f768f1f297adb81dc23f8a0e1b72f7

**Comment by theSlyest** [comment]
> @theSlyest Any chance you could try to re-add the code removed in this commit and see if it works correctly?
> 
> [6f4fe63](https://github.com/axmolengine/axmol/commit/6f4fe63208f768f1f297adb81dc23f8a0e1b72f7)

Ok, I'll try

**Comment by theSlyest** [comment]
It requires more changes to be reverted. I can not test it for now.

**Comment by aismann** [comment]
> @theSlyest Any chance you could try to re-add the code removed in this commit and see if it works correctly?
> 
> [6f4fe63](https://github.com/axmolengine/axmol/commit/6f4fe63208f768f1f297adb81dc23f8a0e1b72f7)

Rebuild with the "latest" changes BEFORE [6f4fe63](https://github.com/axmolengine/axmol/commit/6f4fe63208f768f1f297adb81dc23f8a0e1b72f7)
BitmapFont issue is same 
![image](https://user-images.githubusercontent.com/8652787/205450458-eced8ea6-22be-4284-aa81-bf5bae667d08.png)

**Comment by aismann** [comment]
Test it on `axmol-adxe-1.0-b3` also.  (VS2022 64bit)
Same result: BitmapFonts on FairyGui be not correct (using system font)

I have no longer VS2019, I cannot build older versions  of axmol.

**Comment by aismann** [comment]
`adxe-1.0-a9` is the first one with the extension FairyGUI

**Comment by rh101** [comment]
> `adxe-1.0-a9` is the first one with the extension FairyGUI

I'll test out that version since I still have VS2019 installed.

**Comment by rh101** [comment]
No luck testing `adxe-1.0-a9`, since I can't download the extensions from anywhere:
```
==> Prepare to download external libraries!
==> version file doesn't exist
==> Ready to download 'v56.zip' from 'https://github.com/c4games/engine-x-3rd/archive/v56.zip'
==> Error: Could not find the file from url: 'https://github.com/c4games/engine-x-3rd/archive/v56.zip'
==> Http request failed, error code: 404, reason: Not Found
```

That link doesn't exist any longer, and I don't have copies of the external library zip files. @halx99 Would you by any chance have all the external zip files somewhere, and if possible, upload them somewhere, like the `https://github.com/axmolengine/archive` repo?

**Comment by halx99** [comment]
I prefer to check this issue in current version

**Comment by rh101** [comment]
> I prefer to check this issue in current version

Fair enough, then no point wasting time testing the older versions.
