### ISSUE TITLE
cpp-tests HttpClientTest app freeze if no network connection

### ISSUE THREAD

**Issue by qoozta** [axmolengine/axmol#973]
- axmol version: 07f9bf5
- devices test on: iPhone SE 2 iOS 16.1
- developing environments
   - Xcode version: 14.1 (14B47b)

Steps to Reproduce:

1. Generate cpp-tests Xcode project.
2. Turn off WiFi / Cellular network connection.
3. Run cpp-tests project.
4. Execute Test 16. Network Test > 1. HttpClientTest > Test Get
5. App freeze.

**Comment by halx99** [comment]
Caused by sendSync which will block main thread, it's normal behavior when your connnection not avaiable, after a long time when the sync request failed, the sendSync will return
